/*
 * Copyright (c) 2004-2026 The YAWL Foundation. All rights reserved.
 * The YAWL Foundation is a collaboration of individuals and
 * organisations who are committed to improving workflow technology.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.dspy.adaptation;

import java.io.Serializable;

/**
 * Sealed interface for runtime workflow adaptation actions.
 *
 * <p>This interface represents autonomously-suggested workflow modifications
 * generated by the {@link RuntimeAdaptationAgent} using DSPy ReAct reasoning.
 * Unlike rule-driven adaptation, these actions are AI-driven and contextual.</p>
 *
 * <h2>Action Types</h2>
 * <ul>
 *   <li><strong>SkipTask</strong>: Bypass a task due to business logic change</li>
 *   <li><strong>AddResource</strong>: Allocate additional agents to bottleneck task</li>
 *   <li><strong>ReRoute</strong>: Redirect case to alternative execution path</li>
 *   <li><strong>EscalateCase</strong>: Escalate to manual review with context</li>
 * </ul>
 *
 * <h2>Pattern Matching</h2>
 * <p>Use exhaustive switch on sealed type for type-safe action handling:</p>
 * <pre>{@code
 * AdaptationAction action = agent.decide(context);
 * switch (action) {
 *     case SkipTask skip -> netRunner.skipTask(skip.taskId());
 *     case AddResource add -> resourceManager.addAgent(add.agentId(), add.taskId());
 *     case ReRoute route -> netRunner.reroute(route.taskId(), route.alternateRoute());
 *     case EscalateCase esc -> escalationQueue.add(esc);
 * }
 * }</pre>
 *
 * @author YAWL Foundation
 * @since 6.0
 */
public sealed interface AdaptationAction extends Serializable permits
        SkipTask, AddResource, ReRoute, EscalateCase {

    /**
     * Returns the reasoning behind this adaptation action.
     * Generated by DSPy ReAct agent explaining the decision.
     *
     * @return human-readable reasoning
     */
    String reasoning();

    /**
     * Skip a task in the workflow due to changed conditions.
     *
     * @param taskId task identifier to skip
     * @param reason explanation for skipping
     */
    record SkipTask(String taskId, String reason) implements AdaptationAction {
        @Override
        public String reasoning() {
            return "Skip task " + taskId + ": " + reason;
        }
    }

    /**
     * Add computational resources (agents) to a bottleneck task.
     *
     * @param agentId identifier of agent to allocate
     * @param taskId task experiencing bottleneck
     * @param reason explanation for resource addition
     */
    record AddResource(String agentId, String taskId, String reason) implements AdaptationAction {
        @Override
        public String reasoning() {
            return "Add agent " + agentId + " to task " + taskId + ": " + reason;
        }
    }

    /**
     * Reroute a case to an alternative workflow path.
     *
     * @param taskId task to reroute from
     * @param alternateRoute destination path identifier
     * @param reason explanation for rerouting
     */
    record ReRoute(String taskId, String alternateRoute, String reason) implements AdaptationAction {
        @Override
        public String reasoning() {
            return "Reroute task " + taskId + " to " + alternateRoute + ": " + reason;
        }
    }

    /**
     * Escalate a case to human review with contextual information.
     *
     * @param caseId case identifier requiring escalation
     * @param escalationLevel escalation level (e.g., "manager", "director")
     * @param reason explanation for escalation
     */
    record EscalateCase(String caseId, String escalationLevel, String reason) implements AdaptationAction {
        @Override
        public String reasoning() {
            return "Escalate case " + caseId + " to " + escalationLevel + ": " + reason;
        }
    }
}
