/*
 * Copyright (c) 2004-2026 The YAWL Foundation. All rights reserved.
 * The YAWL Foundation is a collaboration of individuals and
 * organisations who are committed to improving workflow technology.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.dspy.adaptation;

import java.io.Serializable;

/**
 * Sealed interface for runtime workflow adaptation actions.
 *
 * <p>This interface represents autonomously-suggested workflow modifications
 * generated by the RuntimeAdaptationAgent using DSPy ReAct reasoning.
 * Unlike rule-driven adaptation, these actions are AI-driven and contextual.</p>
 *
 * <h2>Action Types</h2>
 * <ul>
 *   <li><strong>SkipTask</strong>: Bypass a task due to business logic change</li>
 *   <li><strong>AddResource</strong>: Allocate additional agents to bottleneck task</li>
 *   <li><strong>ReRoute</strong>: Redirect case to alternative execution path</li>
 *   <li><strong>EscalateCase</strong>: Escalate to manual review with context</li>
 * </ul>
 *
 * <h2>Pattern Matching</h2>
 * <p>Use exhaustive switch on sealed type for type-safe action handling:</p>
 * <pre>{@code
 * AdaptationAction action = agent.decide(context);
 * switch (action) {
 *     case SkipTask skip -> netRunner.skipTask(skip.taskId());
 *     case AddResource add -> resourceManager.addAgent(add.agentId(), add.taskId());
 *     case ReRoute route -> netRunner.reroute(route.taskId(), route.alternateRoute());
 *     case EscalateCase esc -> escalationQueue.add(esc);
 * }
 * }</pre>
 *
 * @author YAWL Foundation
 * @since 6.0
 */
public sealed interface AdaptationAction extends Serializable permits SkipTask, AddResource, ReRoute, EscalateCase {

    /**
     * Returns the reasoning behind this adaptation action.
     * Generated by DSPy ReAct agent explaining the decision.
     *
     * @return human-readable reasoning
     */
    String reasoning();
}
