/*
 * Copyright (c) 2004-2026 The YAWL Foundation. All rights reserved.
 * The YAWL Foundation is a collaboration of individuals and
 * organisations who are committed to improving workflow technology.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.dspy.forensics;

import java.time.Instant;
import java.util.List;
import java.util.Objects;

/**
 * Root Cause Analysis (RCA) report generated by AnomalyForensicsEngine.
 *
 * <p>Provides the most plausible root cause of an anomaly with supporting
 * evidence chain and actionable recommendation for resolution.</p>
 *
 * <p><b>Example Report</b></p>
 * <pre>{@code
 * ForensicsReport report = new ForensicsReport(
 *     "Resource contention from 12 concurrent cases",
 *     0.85,  // 85% confidence
 *     List.of(
 *         "metric spike +320%",
 *         "concurrent cases spike 8 -> 12",
 *         "CPU utilization 95%",
 *         "agent pool exhausted"
 *     ),
 *     "Scale up agents pool by 4 units",
 *     Instant.now()
 * );
 * }</pre>
 *
 * @param rootCause         the most likely root cause (human-readable narrative)
 * @param confidence        confidence score from 0.0 to 1.0
 * @param evidenceChain     ordered list of supporting evidence statements
 * @param recommendation    actionable recommendation for operators/engineers
 * @param generatedAt       timestamp when report was generated
 * @author YAWL Foundation
 * @version 6.0.0
 * @since 6.0.0
 */
public record ForensicsReport(
        String rootCause,
        double confidence,
        List<String> evidenceChain,
        String recommendation,
        Instant generatedAt
) {

    /**
     * Validates and constructs a ForensicsReport.
     *
     * @throws NullPointerException     if any parameter is null
     * @throws IllegalArgumentException if confidence is not in [0.0, 1.0]
     */
    public ForensicsReport {
        Objects.requireNonNull(rootCause, "rootCause must not be null");
        Objects.requireNonNull(evidenceChain, "evidenceChain must not be null");
        Objects.requireNonNull(recommendation, "recommendation must not be null");
        Objects.requireNonNull(generatedAt, "generatedAt must not be null");

        if (confidence < 0.0 || confidence > 1.0) {
            throw new IllegalArgumentException(
                    "confidence must be in [0.0, 1.0], got: " + confidence);
        }
    }

    /**
     * Returns a summary of this forensics report for logging.
     */
    @Override
    public String toString() {
        return String.format(
                "ForensicsReport{rootCause=%s, confidence=%.2f, evidence=%d items}",
                rootCause, confidence, evidenceChain.size()
        );
    }
}
