#!/bin/bash
set -euo pipefail

# SessionStart hook for YAWL in Claude Code Web
# This hook:
# 1. Installs Ant (build system)
# 2. Configures H2 database for ephemeral testing
# 3. Only runs in remote Claude Code Web environment

# Exit early if not in Claude Code Web
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  echo "Local environment detected - skipping remote setup"
  exit 0
fi

echo "🔧 Setting up YAWL for Claude Code Web..."

# Install Ant if not already present
if ! command -v ant &> /dev/null; then
  echo "📦 Installing Apache Ant..."

  # Fix /tmp permissions for apt-get (Claude Code Web security restriction)
  chmod 1777 /tmp 2>/dev/null || true

  # Use apt-get for fast installation (no sudo needed, running as root)
  apt-get update -qq > /dev/null 2>&1
  apt-get install -y ant > /dev/null 2>&1

  echo "✅ Ant $(ant -version | head -n1) installed"
else
  echo "✅ Ant already installed: $(ant -version | head -n1)"
fi

# Configure H2 database for ephemeral testing
echo "🗄️  Configuring H2 database for remote environment..."

# Create backup of original build.properties if not exists
if [ ! -f "$CLAUDE_PROJECT_DIR/build/build.properties.local" ]; then
  cp "$CLAUDE_PROJECT_DIR/build/build.properties" \
     "$CLAUDE_PROJECT_DIR/build/build.properties.local"
  echo "💾 Backed up original build.properties → build.properties.local"
fi

# Update build.properties for H2 in-memory database
cat > "$CLAUDE_PROJECT_DIR/build/build.properties.remote" << 'EOF'
# YAWL Build Properties for Claude Code Web (Remote Environment)
# Auto-generated by .claude/hooks/session-start.sh
# DO NOT EDIT - This file is regenerated on each session start

# Tomcat (not used in remote testing)
catalina.home=~/apache-tomcat-7.0.64
tomcat.treatAsDedicated=false

# Database: H2 in-memory for ephemeral testing
database.type=h2
database.path=mem:yawl;DB_CLOSE_DELAY=-1
database.user=sa
database.password=

# Logging levels (reduced verbosity for testing)
yawl.logging.level=WARN
worklet.logging.level=WARN
resource.logging.level=WARN
scheduling.logging.level=WARN
proclet.logging.level=WARN
hibernate.logging.level=ERROR
root.logging.level=ERROR
mail.logging.level=WARN

# Proxy (not needed)
proxy.host=
proxy.port=

# Build metadata (preserved from original)
yawl.build.number=1747
yawl.build.date=2026-02-14 remote
EOF

# Symlink remote properties to active build.properties
ln -sf "$CLAUDE_PROJECT_DIR/build/build.properties.remote" \
       "$CLAUDE_PROJECT_DIR/build/build.properties"

echo "✅ H2 database configured (in-memory, ephemeral)"

# Export environment variable for runtime detection
if [ -n "${CLAUDE_ENV_FILE:-}" ]; then
  echo 'export YAWL_REMOTE_ENVIRONMENT=true' >> "$CLAUDE_ENV_FILE"
  echo 'export YAWL_DATABASE_TYPE=h2' >> "$CLAUDE_ENV_FILE"
fi

echo "✨ YAWL environment ready for Claude Code Web"
echo ""
echo "📋 Environment Summary:"
echo "   • Build System: Ant $(ant -version 2>/dev/null | head -n1 | cut -d' ' -f4)"
echo "   • Database: H2 (in-memory)"
echo "   • Test Command: ant -f build/build.xml unitTest"
echo "   • Environment: Remote/Ephemeral"
echo ""
