/*
 * YAWL Process Mining Bridge - L3 Domain API
 * Zero FFI types at call site - clean Java interface
 *
 * Generated by: ggen sync from .specify/pm-bridge.ttl
 * Based on rust4pm native capabilities via FFI
 */

package org.yawlfoundation.yawl.processmining;

import java.util.List;
import java.util.Map;

/**
 * High-level Process Mining API for YAWL
 * Provides clean Java interface without FFI type exposure
 * All operations map to rust4pm native functions via ProcessMiningBridgeL2
 */
public class ProcessMiningBridge {

    private static final ProcessMiningBridgeL2 l2 = ProcessMiningBridgeL2.getInstance();

    /**
     * Parse OCEL2 JSON log format into native handle
     * @param json OCEL2 JSON string
     * @return Parse result with handle or error
     */
    public static PmParseResult parseOcel2Json(String json) {
        return l2.parseOcel2Json(json);
    }

    /**
     * Get event count from loaded OCEL log
     * @param logHandle OCEL log handle
     * @return Number of events
     */
    public static int getEventCount(long logHandle) {
        return l2.getEventCount(logHandle);
    }

    /**
     * Get all events from loaded OCEL log
     * @param logHandle OCEL log handle
     * @return OCEL events result
     */
    public static PmOcelEventsResult getEvents(long logHandle) {
        return l2.getEvents(logHandle);
    }

    /**
     * Get object count from loaded OCEL log
     * @param logHandle OCEL log handle
     * @return Number of objects
     */
    public static int getObjectCount(long logHandle) {
        return l2.getObjectCount(logHandle);
    }

    /**
     * Get all objects from loaded OCEL log
     * @param logHandle OCEL log handle
     * @return OCEL objects result
     */
    public static PmOcelObjectsResult getObjects(long logHandle) {
        return l2.getObjects(logHandle);
    }

    /**
     * Discover Direct Follow Graph from OCEL log
     * @param logHandle OCEL log handle
     * @return DFG result with JSON graph
     */
    public static PmDfgResult discoverDfg(long logHandle) {
        return l2.discoverDfg(logHandle);
    }

    /**
     * Check process conformance against model
     * @param logHandle OCEL log handle
     * @return Conformance result with fitness and precision
     */
    public static PmConformanceResult checkConformance(long logHandle) {
        return l2.checkConformance(logHandle);
    }

    /**
     * Free OCEL log handle to release native memory
     * @param logHandle OCEL log handle to free
     */
    public static void freeOcelLog(long logHandle) {
        l2.freeOcelLog(logHandle);
    }

    /**
     * Free OCEL events result to release native memory
     * @param eventsResult OCEL events result to free
     */
    public static void freeEvents(PmOcelEventsResult eventsResult) {
        l2.freeEvents(eventsResult);
    }

    /**
     * Free OCEL objects result to release native memory
     * @param objectsResult OCEL objects result to free
     */
    public static void freeObjects(PmOcelObjectsResult objectsResult) {
        l2.freeObjects(objectsResult);
    }

    /**
     * Free DFG result to release native memory
     * @param dfgResult DFG result to free
     */
    public static void freeDfg(PmDfgResult dfgResult) {
        l2.freeDfg(dfgResult);
    }

    /**
     * Free error result to release native memory
     * @param errorResult Error result to free
     */
    public static void freeError(PmErrorResult errorResult) {
        l2.freeError(errorResult);
    }

    /**
     * Calculate sizes for memory management
     * These are used for buffer allocation in Java side
     */
    public static int sizeOfOcelLogHandle() {
        return l2.sizeOfOcelLogHandle();
    }

    public static int sizeOfParseResult() {
        return l2.sizeOfParseResult();
    }

    public static int sizeOfOcelEvent() {
        return l2.sizeOfOcelEvent();
    }

    public static int sizeOfOcelEventsResult() {
        return l2.sizeOfOcelEventsResult();
    }

    public static int sizeOfOcelObject() {
        return l2.sizeOfOcelObject();
    }

    public static int sizeOfOcelObjectsResult() {
        return l2.sizeOfOcelObjectsResult();
    }

    public static int sizeOfDfgResult() {
        return l2.sizeOfDfgResult();
    }

    public static int sizeOfConformanceResult() {
        return l2.sizeOfConformanceResult();
    }

    /**
     * Get struct field offsets for direct memory access
     * Used by L2 layer for efficient data access
     */
    public static int offsetOfOcelLogHandlePtr() {
        return l2.offsetOfOcelLogHandlePtr();
    }

    public static int offsetOfParseResultHandle() {
        return l2.offsetOfParseResultHandle();
    }

    public static int offsetOfParseResultError() {
        return l2.offsetOfParseResultError();
    }

    public static int offsetOfOcelEventEventId() {
        return l2.offsetOfOcelEventEventId();
    }

    public static int offsetOfOcelEventEventType() {
        return l2.offsetOfOcelEventEventType();
    }

    public static int offsetOfOcelEventTimestampMs() {
        return l2.offsetOfOcelEventTimestampMs();
    }

    public static int offsetOfOcelEventAttrCount() {
        return l2.offsetOfOcelEventAttrCount();
    }

    public static int offsetOfOcelEventsResultEvents() {
        return l2.offsetOfOcelEventsResultEvents();
    }

    public static int offsetOfOcelEventsResultCount() {
        return l2.offsetOfOcelEventsResultCount();
    }

    public static int offsetOfOcelEventsResultError() {
        return l2.offsetOfOcelEventsResultError();
    }

    public static int offsetOfOcelObjectId() {
        return l2.offsetOfOcelObjectId();
    }

    public static int offsetOfOcelObjectType() {
        return l2.offsetOfOcelObjectType();
    }

    public static int offsetOfOcelObjectsResultObjects() {
        return l2.offsetOfOcelObjectsResultObjects();
    }

    public static int offsetOfOcelObjectsResultCount() {
        return l2.offsetOfOcelObjectsResultCount();
    }

    public static int offsetOfOcelObjectsResultError() {
        return l2.offsetOfOcelObjectsResultError();
    }

    public static int offsetOfDfgResultJson() {
        return l2.offsetOfDfgResultJson();
    }

    public static int offsetOfDfgResultError() {
        return l2.offsetOfDfgResultError();
    }

    public static int offsetOfConformanceResultFitness() {
        return l2.offsetOfConformanceResultFitness();
    }

    public static int offsetOfConformanceResultPrecision() {
        return l2.offsetOfConformanceResultPrecision();
    }

    public static int offsetOfConformanceResultError() {
        return l2.offsetOfConformanceResultError();
    }
}