# External Secrets Operator Configuration for YAWL
# Synchronizes secrets from cloud secret managers to Kubernetes
# https://external-secrets.io/

---
# ClusterSecretStore: AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  labels:
    app.kubernetes.io/name: yawl
    app.kubernetes.io/component: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
---
# ClusterSecretStore: Azure Key Vault
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault
  labels:
    app.kubernetes.io/name: yawl
spec:
  provider:
    azurekv:
      tenantId: "${AZURE_TENANT_ID}"
      vaultUrl: "https://yawl-kv.vault.azure.net/"
      authType: workloadIdentity
      serviceAccountRef:
        name: external-secrets-sa
        namespace: external-secrets
---
# ClusterSecretStore: GCP Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
  labels:
    app.kubernetes.io/name: yawl
spec:
  provider:
    gcpsm:
      projectID: ${GCP_PROJECT_ID}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
          clusterLocation: us-central1
          clusterName: yawl-cluster
---
# ClusterSecretStore: HashiCorp Vault
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: hashicorp-vault
  labels:
    app.kubernetes.io/name: yawl
spec:
  provider:
    vault:
      server: "https://vault.internal.example.com"
      path: "yawl"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "yawl-external-secrets"
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
---
# ExternalSecret: Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yawl-db-credentials
  namespace: yawl
  labels:
    app.kubernetes.io/name: yawl
    app.kubernetes.io/component: secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager  # Change based on cloud provider
  target:
    name: yawl-db-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        POSTGRES_HOST: "{{ .db_host }}"
        POSTGRES_PORT: "{{ .db_port }}"
        POSTGRES_DB: "{{ .db_name }}"
        POSTGRES_USER: "{{ .db_username }}"
        POSTGRES_PASSWORD: "{{ .db_password }}"
        JDBC_URL: "jdbc:postgresql://{{ .db_host }}:{{ .db_port }}/{{ .db_name }}"
  data:
    - secretKey: db_host
      remoteRef:
        key: yawl/database
        property: host
    - secretKey: db_port
      remoteRef:
        key: yawl/database
        property: port
    - secretKey: db_name
      remoteRef:
        key: yawl/database
        property: database
    - secretKey: db_username
      remoteRef:
        key: yawl/database
        property: username
    - secretKey: db_password
      remoteRef:
        key: yawl/database
        property: password
---
# ExternalSecret: LDAP/Active Directory Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yawl-ldap-credentials
  namespace: yawl
  labels:
    app.kubernetes.io/name: yawl
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: yawl-ldap-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        LDAP_URL: "{{ .ldap_url }}"
        LDAP_BIND_DN: "{{ .bind_dn }}"
        LDAP_BIND_PASSWORD: "{{ .bind_password }}"
        LDAP_BASE_DN: "{{ .base_dn }}"
        LDAP_USER_FILTER: "{{ .user_filter }}"
        LDAP_GROUP_FILTER: "{{ .group_filter }}"
  data:
    - secretKey: ldap_url
      remoteRef:
        key: yawl/ldap
        property: url
    - secretKey: bind_dn
      remoteRef:
        key: yawl/ldap
        property: bind_dn
    - secretKey: bind_password
      remoteRef:
        key: yawl/ldap
        property: bind_password
    - secretKey: base_dn
      remoteRef:
        key: yawl/ldap
        property: base_dn
    - secretKey: user_filter
      remoteRef:
        key: yawl/ldap
        property: user_filter
    - secretKey: group_filter
      remoteRef:
        key: yawl/ldap
        property: group_filter
---
# ExternalSecret: Encryption Key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yawl-encryption-key
  namespace: yawl
  labels:
    app.kubernetes.io/name: yawl
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: yawl-encryption-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ENCRYPTION_KEY: "{{ .key }}"
        ENCRYPTION_ALGORITHM: "AES-256-GCM"
  data:
    - secretKey: key
      remoteRef:
        key: yawl/encryption
        property: key
---
# ExternalSecret: API Keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yawl-api-keys
  namespace: yawl
  labels:
    app.kubernetes.io/name: yawl
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: yawl-api-keys
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        YAWL_API_KEY: "{{ .api_key }}"
        YAWL_ADMIN_KEY: "{{ .admin_key }}"
        WEBHOOK_SECRET: "{{ .webhook_secret }}"
  data:
    - secretKey: api_key
      remoteRef:
        key: yawl/api-keys
        property: api_key
    - secretKey: admin_key
      remoteRef:
        key: yawl/api-keys
        property: admin_key
    - secretKey: webhook_secret
      remoteRef:
        key: yawl/api-keys
        property: webhook_secret
---
# Service Account for External Secrets Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
  annotations:
    # AWS IRSA
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ExternalSecretsRole
    # Azure Workload Identity
    azure.workload.identity/client-id: "${AZURE_CLIENT_ID}"
    # GCP Workload Identity
    iam.gke.io/gcp-service-account: external-secrets@PROJECT_ID.iam.gserviceaccount.com
---
# ClusterRole for External Secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
# Deployment for External Secrets Controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-secrets
    spec:
      serviceAccountName: external-secrets-sa
      containers:
        - name: external-secrets
          image: ghcr.io/external-secrets/external-secrets:v0.9.0
          args:
            - --concurrent=1
            - --metrics-addr=:8080
            - --loglevel=info
          ports:
            - containerPort: 8080
              name: metrics
          resources:
            requests:
              cpu: 10m
              memory: 96Mi
            limits:
              cpu: 100m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
