/*
 * Copyright (c) 2004-2026 The YAWL Foundation. All rights reserved.
 * The YAWL Foundation is a collaboration of individuals and
 * organisations who are committed to improving workflow technology.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.dspy;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.io.Serializable;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.Map;
import java.util.Objects;

/**
 * Immutable, serializable model of a DSPy program.
 *
 * <p>Encapsulates a DSPy Python program with metadata, input/output schemas,
 * and a source hash for caching. Programs are typically generated by Team 1's
 * dspy_powl_generator.py and executed by PythonDspyBridge.</p>
 *
 * <h2>Cache Key</h2>
 * <p>Programs are cached by name + source hash. Two programs with same name
 * and source hash are considered identical for caching purposes.</p>
 *
 * @param name           Unique program identifier (e.g., "sentiment-analyzer")
 * @param source         Python source code of the DSPy program
 * @param inputSchema    JSON schema describing expected input parameters (optional)
 * @param outputSchema   JSON schema describing expected output structure (optional)
 * @param description    Human-readable description of the program (optional)
 * @param sourceHash     SHA-256 hash of program source (auto-computed)
 * @param generatedBy    Generator that created this program (e.g., "dspy_powl_generator v1.0")
 *
 * @author YAWL Foundation
 * @version 6.0.0
 */
public record DspyProgram(
        @JsonProperty("name")
        String name,

        @JsonProperty("source")
        String source,

        @JsonProperty("input_schema")
        @Nullable Map<String, Object> inputSchema,

        @JsonProperty("output_schema")
        @Nullable Map<String, Object> outputSchema,

        @JsonProperty("description")
        @Nullable String description,

        @JsonProperty("source_hash")
        String sourceHash,

        @JsonProperty("generated_by")
        @Nullable String generatedBy
) implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Compact constructor with validation.
     */
    public DspyProgram {
        Objects.requireNonNull(name, "Program name must not be null");
        Objects.requireNonNull(source, "Program source must not be null");
        if (name.isBlank()) {
            throw new IllegalArgumentException("Program name must not be blank");
        }
        if (source.isBlank()) {
            throw new IllegalArgumentException("Program source must not be blank");
        }
    }

    /**
     * Creates a new builder for DspyProgram.
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder for DspyProgram with fluent API.
     */
    public static final class Builder {
        private String name;
        private String source;
        private @Nullable Map<String, Object> inputSchema;
        private @Nullable Map<String, Object> outputSchema;
        private @Nullable String description;
        private @Nullable String generatedBy;

        /**
         * Sets the program name.
         */
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * Sets the Python source code.
         */
        public Builder source(String source) {
            this.source = Objects.requireNonNull(source, "source must not be null");
            return this;
        }

        /**
         * Sets the input schema (optional).
         */
        public Builder inputSchema(@Nullable Map<String, Object> schema) {
            this.inputSchema = schema;
            return this;
        }

        /**
         * Sets the output schema (optional).
         */
        public Builder outputSchema(@Nullable Map<String, Object> schema) {
            this.outputSchema = schema;
            return this;
        }

        /**
         * Sets the description (optional).
         */
        public Builder description(@Nullable String desc) {
            this.description = desc;
            return this;
        }

        /**
         * Sets the generator metadata (optional).
         */
        public Builder generatedBy(@Nullable String generator) {
            this.generatedBy = generator;
            return this;
        }

        /**
         * Builds the DspyProgram with auto-computed source hash.
         *
         * @throws IllegalStateException if name or source is not set
         */
        public DspyProgram build() {
            if (name == null) {
                throw new IllegalStateException("Program name must be set");
            }
            if (source == null) {
                throw new IllegalStateException("Program source must be set");
            }
            String hash = computeSourceHash(source);
            return new DspyProgram(name, source, inputSchema, outputSchema, description, hash, generatedBy);
        }
    }

    /**
     * Computes SHA-256 hash of the program source.
     *
     * @param source the Python source code
     * @return hex-encoded SHA-256 hash
     */
    private static String computeSourceHash(String source) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] digest = md.digest(source.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(digest);
        } catch (NoSuchAlgorithmException e) {
            // SHA-256 is guaranteed to exist in Java; treat as impossible
            throw new AssertionError("SHA-256 algorithm not available", e);
        }
    }

    /**
     * Returns a cache key combining program name and source hash.
     *
     * <p>Two programs with the same name and source hash are considered
     * identical for caching purposes.</p>
     */
    public String cacheKey() {
        return name + ":" + sourceHash;
    }

    /**
     * Returns the first 100 characters of source code (for logging).
     */
    public String sourcePreview() {
        int len = Math.min(100, source.length());
        String preview = source.substring(0, len).replaceAll("\n", " ");
        return source.length() > 100 ? preview + "..." : preview;
    }
}
