#!/usr/bin/env bash
# ci-cd/scripts/update-baseline.sh
#
# Record a new performance baseline from the current build environment.
# Run this manually after a known-good build to anchor future regressions.
#
# Usage:
#   ./ci-cd/scripts/update-baseline.sh [--output ci-cd/baselines/pipeline-baseline.json]
#
# Output JSON:
#   {
#     "updated_at": "2026-02-18T12:00:00Z",
#     "git_sha": "abc1234",
#     "cpu_cores": 16,
#     "compile_ms": 42000,
#     "unit_test_ms": 38000
#   }

set -euo pipefail

OUTPUT_FILE="ci-cd/baselines/pipeline-baseline.json"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT_FILE="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

mkdir -p "$(dirname "${OUTPUT_FILE}")"

CPU_CORES=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)
GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "Measuring compile time..."
COMPILE_START=$(date +%s%N)
mvn -T 1.5C clean compile -DskipTests -q
COMPILE_END=$(date +%s%N)
COMPILE_MS=$(( (COMPILE_END - COMPILE_START) / 1000000 ))
echo "  Compile: ${COMPILE_MS}ms"

echo "Measuring unit test time..."
TEST_START=$(date +%s%N)
mvn -T 1.5C test -q \
  -Dsurefire.threadCount=1C \
  -Djunit.jupiter.execution.parallel.enabled=true \
  -Djunit.jupiter.execution.parallel.mode.default=concurrent \
  -Djunit.jupiter.execution.parallel.config.strategy=dynamic \
  -Djunit.jupiter.execution.parallel.config.dynamic.factor=1.5
TEST_END=$(date +%s%N)
TEST_MS=$(( (TEST_END - TEST_START) / 1000000 ))
echo "  Unit tests: ${TEST_MS}ms"

cat > "${OUTPUT_FILE}" << JSON_EOF
{
  "updated_at": "${NOW}",
  "git_sha": "${GIT_SHA}",
  "cpu_cores": ${CPU_CORES},
  "java_version": "25",
  "maven_flags": "-T 1.5C",
  "surefire_thread_count": "1C",
  "compile_ms": ${COMPILE_MS},
  "unit_test_ms": ${TEST_MS},
  "notes": "Generated by update-baseline.sh on $(hostname)"
}
JSON_EOF

echo ""
echo "Baseline written to: ${OUTPUT_FILE}"
cat "${OUTPUT_FILE}"
