/*
 * Copyright (c) 2004-2026 The YAWL Foundation. All rights reserved.
 * The YAWL Foundation is a collaboration of individuals and
 * organisations who are committed to improving workflow technology.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.datamodelling.bridge;

import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;
import java.nio.file.Path;
import java.util.Optional;

/**
 * DataModellingL2 — Layer 2 FFI transport for {@code libdata_modelling_ffi.so}.
 *
 * <p>Thin wrapper over Panama FFM downcall handles. Maps directly to 7 native symbols:
 * <ul>
 *   <li>{@code dm_call} — dispatcher for all 67 data-modelling-sdk operations</li>
 *   <li>{@code dm_result_free} — releases heap-allocated DmResult</li>
 *   <li>{@code dm_sizeof_dm_result} — struct size probe (correctness-by-construction)</li>
 *   <li>{@code dm_offsetof_data} — field offset probe</li>
 *   <li>{@code dm_offsetof_data_len} — field offset probe</li>
 *   <li>{@code dm_offsetof_error} — field offset probe</li>
 *   <li>{@code dm_offsetof_error_len} — field offset probe</li>
 * </ul>
 *
 * <p>Graceful degradation: all methods throw {@link UnsupportedOperationException}
 * when the native library is not loaded. Set system property
 * {@code -Ddatamodelling.library.path=/path/to/libdata_modelling_ffi.so} to enable.
 *
 * @generated by ggen from ontology
 * @pattern WCP-NB-03
 * @see DataModellingL3
 */
@DataModellingMapsToCapability(value = DataModellingCapability.PARSE_ODCS_YAML, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_SQL, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_ODCS_YAML_V2, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.CONVERT_TO_ODCS, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.CREATE_WORKSPACE, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.CREATE_DECISION, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.CREATE_KNOWLEDGE_ARTICLE, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.CREATE_SKETCH, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_ODPS, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.REFINE_SCHEMA_WITH_LLM_OFFLINE, layer = "L2")
public final class DataModellingL2 implements AutoCloseable {

    /** System property for the path to {@code libdata_modelling_ffi.so}. */
    public static final String LIB_PATH_PROP = "datamodelling.library.path";

    private static final Linker LINKER = Linker.nativeLinker();
    private static final Logger log = LoggerFactory.getLogger(DataModellingL2.class);

    private final Arena                  arena;
    private final Optional<SymbolLookup> library;
    private final NativeLibraryExtractor extractor;

    /** Downcall handle for {@code dm_call}. */
    private final MethodHandle hDmCall;
    /** Downcall handle for {@code dm_result_free}. */
    private final MethodHandle hDmResultFree;
    /** Downcall handle for {@code dm_sizeof_dm_result}. */
    private final MethodHandle hDmSizeof;
    /** Downcall handle for {@code dm_offsetof_data}. */
    private final MethodHandle hDmOffsetofData;
    /** Downcall handle for {@code dm_offsetof_data_len}. */
    private final MethodHandle hDmOffsetofDataLen;
    /** Downcall handle for {@code dm_offsetof_error}. */
    private final MethodHandle hDmOffsetofError;
    /** Downcall handle for {@code dm_offsetof_error_len}. */
    private final MethodHandle hDmOffsetofErrorLen;

    /**
     * Creates an L2 transport using the three-tier loading strategy:
     * <ol>
     *   <li>Explicit {@code -Ddatamodelling.library.path} system property</li>
     *   <li>Bundled classpath resource ({@code native/<os-arch>/libdata_modelling_ffi.so})</li>
     *   <li>Degraded mode — {@link #isLibraryLoaded()} returns false</li>
     * </ol>
     *
     * @param explicitPath absolute library path override, or null to use classpath/degraded
     * @return a new L2 instance
     */
    public static DataModellingL2 load(@Nullable String explicitPath) {
        if (explicitPath != null && !explicitPath.isBlank()) {
            return new DataModellingL2(explicitPath, null);
        }
        try {
            NativeLibraryExtractor ext = NativeLibraryExtractor.extract();
            return new DataModellingL2(ext.absolutePath(), ext);
        } catch (Exception e) {
            log.warn("libdata_modelling_ffi not found on classpath ({}); running in degraded mode. "
                    + "Set -D{}=<path> or rebuild with skipRustBuild=false.",
                    e.getMessage(), LIB_PATH_PROP);
            return new DataModellingL2(null, null);
        }
    }

    /**
     * Creates an L2 transport, loading the native library from the given path.
     * If the path is null or blank, all operations throw {@link UnsupportedOperationException}.
     *
     * @param libraryPath absolute path to {@code libdata_modelling_ffi.so}, or null to operate degraded
     */
    public DataModellingL2(String libraryPath) {
        this(libraryPath, null);
    }

    private DataModellingL2(String libraryPath, NativeLibraryExtractor extractor) {
        this.extractor = extractor;
        this.arena = Arena.ofShared();
        Optional<SymbolLookup> lib = Optional.empty();
        if (libraryPath != null && !libraryPath.isBlank()) {
            lib = Optional.of(SymbolLookup.libraryLookup(Path.of(libraryPath), arena));
        }
        this.library = lib;

        boolean loaded = library.isPresent();

        this.hDmCall = loaded ? resolveHandle("dm_call",
                FunctionDescriptor.of(ValueLayout.ADDRESS,
                        ValueLayout.ADDRESS, ValueLayout.JAVA_LONG,
                        ValueLayout.ADDRESS, ValueLayout.JAVA_LONG)) : null;

        this.hDmResultFree = loaded ? resolveHandle("dm_result_free",
                FunctionDescriptor.ofVoid(ValueLayout.ADDRESS)) : null;

        this.hDmSizeof = loaded ? resolveHandle("dm_sizeof_dm_result",
                FunctionDescriptor.of(ValueLayout.JAVA_LONG)) : null;

        this.hDmOffsetofData = loaded ? resolveHandle("dm_offsetof_data",
                FunctionDescriptor.of(ValueLayout.JAVA_LONG)) : null;

        this.hDmOffsetofDataLen = loaded ? resolveHandle("dm_offsetof_data_len",
                FunctionDescriptor.of(ValueLayout.JAVA_LONG)) : null;

        this.hDmOffsetofError = loaded ? resolveHandle("dm_offsetof_error",
                FunctionDescriptor.of(ValueLayout.JAVA_LONG)) : null;

        this.hDmOffsetofErrorLen = loaded ? resolveHandle("dm_offsetof_error_len",
                FunctionDescriptor.of(ValueLayout.JAVA_LONG)) : null;

        if (loaded) {
            DataModellingFFI.validateLayout(this);
        }
    }

    // ── Dispatch ─────────────────────────────────────────────────────────────

    /**
     * Calls {@code dm_call} — dispatches a data-modelling-sdk operation by name.
     *
     * @param fnName     pointer to the function name string (UTF-8, not null-terminated past len)
     * @param fnNameLen  byte length of fnName
     * @param argsJson   pointer to the JSON array of string arguments
     * @param argsLen    byte length of argsJson
     * @return pointer to a heap-allocated DmResult; caller must free via {@link #dmResultFree}
     * @throws UnsupportedOperationException if the native library is not loaded
     */
    public MemorySegment dmCall(MemorySegment fnName, long fnNameLen,
                                MemorySegment argsJson, long argsLen) {
        requireLibrary();
        try {
            return (MemorySegment) hDmCall.invokeExact(fnName, fnNameLen, argsJson, argsLen);
        } catch (Throwable t) {
            throw new AssertionError("dm_call invocation failed", t);
        }
    }

    /**
     * Calls {@code dm_result_free} — releases a DmResult allocated by dm_call.
     *
     * @param result pointer to the DmResult to free; ignored if null
     * @throws UnsupportedOperationException if the native library is not loaded
     */
    public void dmResultFree(MemorySegment result) {
        requireLibrary();
        try {
            hDmResultFree.invokeExact(result);
        } catch (Throwable t) {
            throw new AssertionError("dm_result_free invocation failed", t);
        }
    }

    // ── Struct layout probes (correctness-by-construction) ───────────────────

    /**
     * Returns the native sizeof(DmResult) for layout validation.
     *
     * @throws UnsupportedOperationException if the native library is not loaded
     */
    public long dmSizeofDmResult() {
        requireLibrary();
        try {
            return (long) hDmSizeof.invokeExact();
        } catch (Throwable t) {
            throw new AssertionError("dm_sizeof_dm_result invocation failed", t);
        }
    }

    /**
     * Returns offsetof(DmResult, data) for layout validation.
     *
     * @throws UnsupportedOperationException if the native library is not loaded
     */
    public long dmOffsetofData() {
        requireLibrary();
        try {
            return (long) hDmOffsetofData.invokeExact();
        } catch (Throwable t) {
            throw new AssertionError("dm_offsetof_data invocation failed", t);
        }
    }

    /**
     * Returns offsetof(DmResult, data_len) for layout validation.
     *
     * @throws UnsupportedOperationException if the native library is not loaded
     */
    public long dmOffsetofDataLen() {
        requireLibrary();
        try {
            return (long) hDmOffsetofDataLen.invokeExact();
        } catch (Throwable t) {
            throw new AssertionError("dm_offsetof_data_len invocation failed", t);
        }
    }

    /**
     * Returns offsetof(DmResult, error) for layout validation.
     *
     * @throws UnsupportedOperationException if the native library is not loaded
     */
    public long dmOffsetofError() {
        requireLibrary();
        try {
            return (long) hDmOffsetofError.invokeExact();
        } catch (Throwable t) {
            throw new AssertionError("dm_offsetof_error invocation failed", t);
        }
    }

    /**
     * Returns offsetof(DmResult, error_len) for layout validation.
     *
     * @throws UnsupportedOperationException if the native library is not loaded
     */
    public long dmOffsetofErrorLen() {
        requireLibrary();
        try {
            return (long) hDmOffsetofErrorLen.invokeExact();
        } catch (Throwable t) {
            throw new AssertionError("dm_offsetof_error_len invocation failed", t);
        }
    }

    // ── Library lifecycle ─────────────────────────────────────────────────────

    /**
     * Returns true if the native library was successfully loaded.
     */
    public boolean isLibraryLoaded() {
        return library.isPresent();
    }

    /**
     * Releases the shared Arena and deletes any extracted temp library file.
     */
    @Override
    public void close() {
        arena.close();
        if (extractor != null) {
            extractor.close();
        }
    }

    // ── Private ───────────────────────────────────────────────────────────────

    private MethodHandle resolveHandle(String symbol, FunctionDescriptor descriptor) {
        return library.get().find(symbol)
                .map(seg -> LINKER.downcallHandle(seg, descriptor))
                .orElseThrow(() -> new UnsatisfiedLinkError(
                        symbol + " not found in libdata_modelling_ffi.so"));
    }

    private void requireLibrary() {
        if (library.isEmpty()) {
            throw new UnsupportedOperationException(
                    "libdata_modelling_ffi not loaded. "
                    + "Either bundle the native library in the JAR (rebuild with skipRustBuild=false) "
                    + "or set -D" + LIB_PATH_PROP + "=/path/to/libdata_modelling_ffi.so. "
                    + "Use DataModellingL2.load() or DataModellingL3.fromSystemProperty() "
                    + "to enable automatic classpath extraction.");
        }
    }
}
