/*
 * Copyright (c) 2004-2026 The YAWL Foundation. All rights reserved.
 * The YAWL Foundation is a collaboration of individuals and
 * organisations who are committed to improving workflow technology.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.datamodelling.bridge;

import org.yawlfoundation.yawl.datamodelling.DataModellingException;
import org.yawlfoundation.yawl.datamodelling.llm.LlmConfig;
import org.yawlfoundation.yawl.datamodelling.pipeline.InferenceConfig;
import org.yawlfoundation.yawl.datamodelling.pipeline.MappingConfig;

import org.jspecify.annotations.Nullable;
import java.util.Objects;

/**
 * DataModellingL3 — Layer 3 domain API for the DataModelling native Panama FFM bridge.
 *
 * <p>High-level facade over {@link DataModellingL2} FFI transport. All 67 data-modelling-sdk
 * operations are exposed as type-safe Java methods, each annotated with
 * {@link DataModellingMapsToCapability} for registry validation.
 *
 * <p>Delegates all SDK calls to {@link DataModellingFFI#call} or {@link DataModellingFFI#callVoid},
 * which marshal arguments to JSON and handle error checking.
 *
 * <p>Error handling: All methods declare {@code throws DataModellingException}. Void methods use
 * {@code callVoid}, which checks only the error field. Non-void methods use {@code call}, which
 * extracts the data field or throws on error/missing data.
 *
 * <p>Graceful degradation: Operations throw {@link DataModellingException} if the native library
 * is not loaded. Use {@link #isAvailable()} to check availability before calling.
 *
 * <h2>Example usage</h2>
 * <pre>{@code
 * try (DataModellingL3 api = DataModellingL3.fromSystemProperty()) {
 *     String result = api.parseOdcsYaml(yamlContent);
 *     System.out.println(result);
 * }
 * }</pre>
 *
 * @generated by ggen from ontology
 * @pattern WCP-NB-04
 * @see DataModellingL2
 * @see DataModellingFFI
 */
@DataModellingMapsToCapability(value = DataModellingCapability.PARSE_ODCS_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.PARSE_ODCS_YAML_V2, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_SQL, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_AVRO, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_JSON_SCHEMA, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_PROTOBUF, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_CADS, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_ODPS, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_BPMN_MODEL, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_DMN_MODEL, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_OPENAPI_SPEC, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_ODCS_YAML_V2, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_TO_SQL, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_BPMN_MODEL, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_DMN_MODEL, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_ODCS_YAML_TO_MARKDOWN, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_ODPS_TO_MARKDOWN, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.CONVERT_TO_ODCS, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.CONVERT_OPENAPI_TO_ODCS, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.ANALYZE_OPENAPI_CONVERSION, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.MIGRATE_DATAFLOW_TO_DOMAIN, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.CREATE_WORKSPACE, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.PARSE_WORKSPACE_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.ADD_RELATIONSHIP_TO_WORKSPACE, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.REMOVE_RELATIONSHIP_FROM_WORKSPACE, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.CREATE_DOMAIN, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.ADD_DOMAIN_TO_WORKSPACE, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.REMOVE_DOMAIN_FROM_WORKSPACE, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.ADD_SYSTEM_TO_DOMAIN, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.ADD_ODCS_NODE_TO_DOMAIN, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.ADD_CADS_NODE_TO_DOMAIN, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.CREATE_DECISION, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.CREATE_DECISION_INDEX, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.PARSE_DECISION_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_DECISION_TO_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_DECISION_TO_MARKDOWN, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.PARSE_DECISION_INDEX_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_DECISION_INDEX_TO_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.ADD_DECISION_TO_INDEX, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.CREATE_KNOWLEDGE_ARTICLE, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.CREATE_KNOWLEDGE_INDEX, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.PARSE_KNOWLEDGE_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_KNOWLEDGE_TO_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_KNOWLEDGE_TO_MARKDOWN, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.PARSE_KNOWLEDGE_INDEX_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_KNOWLEDGE_INDEX_TO_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.ADD_ARTICLE_TO_KNOWLEDGE_INDEX, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.SEARCH_KNOWLEDGE_ARTICLES, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.CREATE_SKETCH, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.CREATE_SKETCH_INDEX, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.PARSE_SKETCH_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_SKETCH_TO_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.PARSE_SKETCH_INDEX_YAML, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.ADD_SKETCH_TO_INDEX, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.SEARCH_SKETCHES, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_ODPS, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_TABLE_NAME, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_COLUMN_NAME, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_DATA_TYPE, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.CHECK_CIRCULAR_DEPENDENCY, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.DETECT_NAMING_CONFLICTS, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.REFINE_SCHEMA_WITH_LLM_OFFLINE, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.REFINE_SCHEMA_WITH_LLM_ONLINE, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.MATCH_FIELDS_WITH_LLM, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.ENRICH_DOCUMENTATION_WITH_LLM, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.DETECT_PATTERNS_WITH_LLM, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.CHECK_LLM_AVAILABILITY, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.INFER_SCHEMA_FROM_JSON, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.MAP_SCHEMAS, layer = "L3")
@DataModellingMapsToCapability(value = DataModellingCapability.GENERATE_TRANSFORM, layer = "L3")
public final class DataModellingL3 implements AutoCloseable {

    private final DataModellingL2 transport;
    private volatile boolean closed = false;

    /**
     * Creates a new L3 API bound to the given L2 transport.
     *
     * @param transport the L2 FFI transport; must not be null
     */
    public DataModellingL3(DataModellingL2 transport) {
        this.transport = Objects.requireNonNull(transport, "transport must not be null");
    }

    /**
     * Creates a new L3 API by reading the library path from system property
     * {@code datamodelling.library.path}.
     *
     * @return a new L3 instance with L2 transport initialized from system property
     */
    public static DataModellingL3 fromSystemProperty() {
        String libPath = System.getProperty(DataModellingL2.LIB_PATH_PROP);
        return new DataModellingL3(new DataModellingL2(libPath));
    }

    /**
     * Checks if the native library is loaded and available.
     *
     * @return true if library is loaded, false otherwise
     */
    public boolean isAvailable() {
        return transport.isLibraryLoaded();
    }

    @Override
    public void close() {
        closed = true;
        if (transport != null) {
            try {
                transport.close();
            } catch (Exception e) {
                Thread.currentThread().getUncaughtExceptionHandler()
                        .uncaughtException(Thread.currentThread(), e);
            }
        }
    }

    /**
     * Asserts that this API is still open.
     *
     * @throws DataModellingException if closed
     */
    private void requireOpen() throws DataModellingException {
        if (closed) {
            throw new DataModellingException(
                    "DataModellingL3 is closed",
                    DataModellingException.ErrorKind.CLOSED_ERROR);
        }
    }

    // ── Schema import (11) ────────────────────────────────────────────────────

    /**
     * Parse ODCS YAML (v3.1.0 or v2.x) into workspace JSON.
     *
     * @param yaml the ODCS YAML content; must not be null
     * @return workspace JSON; never null
     * @throws DataModellingException on parse error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.PARSE_ODCS_YAML, layer = "L3")
    public String parseOdcsYaml(String yaml) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(yaml, "yaml must not be null");
        return DataModellingFFI.call(transport, "parse_odcs_yaml", yaml);
    }

    /**
     * Parse ODCS YAML v2 with extended field preservation.
     *
     * @param yaml the ODCS YAML v2 content; must not be null
     * @return workspace JSON; never null
     * @throws DataModellingException on parse error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.PARSE_ODCS_YAML_V2, layer = "L3")
    public String parseOdcsYamlV2(String yaml) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(yaml, "yaml must not be null");
        return DataModellingFFI.call(transport, "parse_odcs_yaml_v2", yaml);
    }

    /**
     * Import SQL DDL statements into workspace JSON.
     *
     * @param sql the SQL DDL content; must not be null
     * @param dialect the SQL dialect (e.g. "postgresql", "mysql"); must not be null
     * @return workspace JSON; never null
     * @throws DataModellingException on import error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_SQL, layer = "L3")
    public String importFromSql(String sql, String dialect) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(sql, "sql must not be null");
        Objects.requireNonNull(dialect, "dialect must not be null");
        return DataModellingFFI.call(transport, "import_from_sql", sql, dialect);
    }

    /**
     * Import Avro schema into workspace JSON.
     *
     * @param avroContent the Avro schema content; must not be null
     * @return workspace JSON; never null
     * @throws DataModellingException on import error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_AVRO, layer = "L3")
    public String importFromAvro(String avroContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(avroContent, "avroContent must not be null");
        return DataModellingFFI.call(transport, "import_from_avro", avroContent);
    }

    /**
     * Import JSON Schema into workspace JSON.
     *
     * @param jsonSchemaContent the JSON Schema content; must not be null
     * @return workspace JSON; never null
     * @throws DataModellingException on import error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_JSON_SCHEMA, layer = "L3")
    public String importFromJsonSchema(String jsonSchemaContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(jsonSchemaContent, "jsonSchemaContent must not be null");
        return DataModellingFFI.call(transport, "import_from_json_schema", jsonSchemaContent);
    }

    /**
     * Import Protobuf schema into workspace JSON.
     *
     * @param protobufContent the Protobuf schema content; must not be null
     * @return workspace JSON; never null
     * @throws DataModellingException on import error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_PROTOBUF, layer = "L3")
    public String importFromProtobuf(String protobufContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(protobufContent, "protobufContent must not be null");
        return DataModellingFFI.call(transport, "import_from_protobuf", protobufContent);
    }

    /**
     * Import CADS YAML into workspace JSON.
     *
     * @param yamlContent the CADS YAML content; must not be null
     * @return workspace JSON; never null
     * @throws DataModellingException on import error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_CADS, layer = "L3")
    public String importFromCads(String yamlContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(yamlContent, "yamlContent must not be null");
        return DataModellingFFI.call(transport, "import_from_cads", yamlContent);
    }

    /**
     * Import ODPS YAML into workspace JSON.
     *
     * @param yamlContent the ODPS YAML content; must not be null
     * @return workspace JSON; never null
     * @throws DataModellingException on import error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_FROM_ODPS, layer = "L3")
    public String importFromOdps(String yamlContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(yamlContent, "yamlContent must not be null");
        return DataModellingFFI.call(transport, "import_from_odps", yamlContent);
    }

    /**
     * Import BPMN model into domain.
     *
     * @param domainId the domain ID; must not be null
     * @param xmlContent the BPMN XML content; must not be null
     * @param modelName optional model name; may be null
     * @return domain JSON; never null
     * @throws DataModellingException on import error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_BPMN_MODEL, layer = "L3")
    public String importBpmnModel(String domainId, String xmlContent,
                                   @Nullable String modelName) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(domainId, "domainId must not be null");
        Objects.requireNonNull(xmlContent, "xmlContent must not be null");
        return DataModellingFFI.call(transport, "import_bpmn_model", domainId, xmlContent,
                modelName != null ? modelName : "");
    }

    /**
     * Import DMN model into domain.
     *
     * @param domainId the domain ID; must not be null
     * @param xmlContent the DMN XML content; must not be null
     * @param modelName optional model name; may be null
     * @return domain JSON; never null
     * @throws DataModellingException on import error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_DMN_MODEL, layer = "L3")
    public String importDmnModel(String domainId, String xmlContent,
                                  @Nullable String modelName) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(domainId, "domainId must not be null");
        Objects.requireNonNull(xmlContent, "xmlContent must not be null");
        return DataModellingFFI.call(transport, "import_dmn_model", domainId, xmlContent,
                modelName != null ? modelName : "");
    }

    /**
     * Import OpenAPI specification into domain.
     *
     * @param domainId the domain ID; must not be null
     * @param content the OpenAPI specification content; must not be null
     * @param apiName optional API name; may be null
     * @return domain JSON; never null
     * @throws DataModellingException on import error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_OPENAPI_SPEC, layer = "L3")
    public String importOpenapiSpec(String domainId, String content,
                                     @Nullable String apiName) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(domainId, "domainId must not be null");
        Objects.requireNonNull(content, "content must not be null");
        return DataModellingFFI.call(transport, "import_openapi_spec", domainId, content,
                apiName != null ? apiName : "");
    }

    // ── Schema export (6) ─────────────────────────────────────────────────────

    /**
     * Export workspace to ODCS YAML v2.
     *
     * @param contractJson the contract JSON; must not be null
     * @return ODCS YAML v2; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_ODCS_YAML_V2, layer = "L3")
    public String exportOdcsYamlV2(String contractJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(contractJson, "contractJson must not be null");
        return DataModellingFFI.call(transport, "export_odcs_yaml_v2", contractJson);
    }

    /**
     * Export workspace to SQL DDL.
     *
     * @param workspaceJson the workspace JSON; must not be null
     * @param dialect the SQL dialect (e.g. "postgresql", "mysql"); must not be null
     * @return SQL DDL; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_TO_SQL, layer = "L3")
    public String exportToSql(String workspaceJson, String dialect) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(workspaceJson, "workspaceJson must not be null");
        Objects.requireNonNull(dialect, "dialect must not be null");
        return DataModellingFFI.call(transport, "export_to_sql", workspaceJson, dialect);
    }

    /**
     * Export BPMN model.
     *
     * @param xmlContent the BPMN XML content; must not be null
     * @return exported BPMN XML; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_BPMN_MODEL, layer = "L3")
    public String exportBpmnModel(String xmlContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(xmlContent, "xmlContent must not be null");
        return DataModellingFFI.call(transport, "export_bpmn_model", xmlContent);
    }

    /**
     * Export DMN model.
     *
     * @param xmlContent the DMN XML content; must not be null
     * @return exported DMN XML; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_DMN_MODEL, layer = "L3")
    public String exportDmnModel(String xmlContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(xmlContent, "xmlContent must not be null");
        return DataModellingFFI.call(transport, "export_dmn_model", xmlContent);
    }

    /**
     * Export ODCS YAML to Markdown.
     *
     * @param odcsYaml the ODCS YAML content; must not be null
     * @return Markdown documentation; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_ODCS_YAML_TO_MARKDOWN, layer = "L3")
    public String exportOdcsYamlToMarkdown(String odcsYaml) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(odcsYaml, "odcsYaml must not be null");
        return DataModellingFFI.call(transport, "export_odcs_yaml_to_markdown", odcsYaml);
    }

    /**
     * Export ODPS product to Markdown.
     *
     * @param productJson the product JSON; must not be null
     * @return Markdown documentation; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_ODPS_TO_MARKDOWN, layer = "L3")
    public String exportOdpsToMarkdown(String productJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(productJson, "productJson must not be null");
        return DataModellingFFI.call(transport, "export_odps_to_markdown", productJson);
    }

    // ── Format conversion (4) ─────────────────────────────────────────────────

    /**
     * Convert input to ODCS format.
     *
     * @param input the input content; must not be null
     * @param format optional input format identifier; may be null
     * @return ODCS JSON; never null
     * @throws DataModellingException on conversion error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.CONVERT_TO_ODCS, layer = "L3")
    public String convertToOdcs(String input, @Nullable String format) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(input, "input must not be null");
        return DataModellingFFI.call(transport, "convert_to_odcs", input,
                format != null ? format : "");
    }

    /**
     * Convert OpenAPI specification to ODCS.
     *
     * @param openapiContent the OpenAPI content; must not be null
     * @param componentName the component name; must not be null
     * @param tableName optional table name for ODCS mapping; may be null
     * @return ODCS JSON; never null
     * @throws DataModellingException on conversion error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.CONVERT_OPENAPI_TO_ODCS, layer = "L3")
    public String convertOpenapiToOdcs(String openapiContent, String componentName,
                                        @Nullable String tableName) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(openapiContent, "openapiContent must not be null");
        Objects.requireNonNull(componentName, "componentName must not be null");
        return DataModellingFFI.call(transport, "convert_openapi_to_odcs", openapiContent,
                componentName, tableName != null ? tableName : "");
    }

    /**
     * Analyze OpenAPI conversion feasibility.
     *
     * @param openapiContent the OpenAPI content; must not be null
     * @param componentName the component name; must not be null
     * @return analysis JSON; never null
     * @throws DataModellingException on analysis error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.ANALYZE_OPENAPI_CONVERSION, layer = "L3")
    public String analyzeOpenapiConversion(String openapiContent,
                                            String componentName) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(openapiContent, "openapiContent must not be null");
        Objects.requireNonNull(componentName, "componentName must not be null");
        return DataModellingFFI.call(transport, "analyze_openapi_conversion", openapiContent,
                componentName);
    }

    /**
     * Migrate Dataflow to Domain representation.
     *
     * @param dataflowYaml the dataflow YAML content; must not be null
     * @param domainName optional domain name; may be null
     * @return domain JSON; never null
     * @throws DataModellingException on migration error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.MIGRATE_DATAFLOW_TO_DOMAIN, layer = "L3")
    public String migrateDataflowToDomain(String dataflowYaml,
                                           @Nullable String domainName) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(dataflowYaml, "dataflowYaml must not be null");
        return DataModellingFFI.call(transport, "migrate_dataflow_to_domain", dataflowYaml,
                domainName != null ? domainName : "");
    }

    // ── Workspace (10) ────────────────────────────────────────────────────────

    /**
     * Create a new workspace.
     *
     * @param name the workspace name; must not be null
     * @param ownerId the owner ID; must not be null
     * @return workspace JSON; never null
     * @throws DataModellingException on creation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.CREATE_WORKSPACE, layer = "L3")
    public String createWorkspace(String name, String ownerId) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(name, "name must not be null");
        Objects.requireNonNull(ownerId, "ownerId must not be null");
        return DataModellingFFI.call(transport, "create_workspace", name, ownerId);
    }

    /**
     * Parse workspace YAML.
     *
     * @param yamlContent the workspace YAML content; must not be null
     * @return workspace JSON; never null
     * @throws DataModellingException on parse error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.PARSE_WORKSPACE_YAML, layer = "L3")
    public String parseWorkspaceYaml(String yamlContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(yamlContent, "yamlContent must not be null");
        return DataModellingFFI.call(transport, "parse_workspace_yaml", yamlContent);
    }

    /**
     * Add relationship to workspace.
     *
     * @param workspaceJson the workspace JSON; must not be null
     * @param relationshipJson the relationship JSON; must not be null
     * @return updated workspace JSON; never null
     * @throws DataModellingException on operation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.ADD_RELATIONSHIP_TO_WORKSPACE, layer = "L3")
    public String addRelationshipToWorkspace(String workspaceJson,
                                              String relationshipJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(workspaceJson, "workspaceJson must not be null");
        Objects.requireNonNull(relationshipJson, "relationshipJson must not be null");
        return DataModellingFFI.call(transport, "add_relationship_to_workspace", workspaceJson,
                relationshipJson);
    }

    /**
     * Remove relationship from workspace.
     *
     * @param workspaceJson the workspace JSON; must not be null
     * @param relationshipId the relationship ID; must not be null
     * @return updated workspace JSON; never null
     * @throws DataModellingException on operation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.REMOVE_RELATIONSHIP_FROM_WORKSPACE, layer = "L3")
    public String removeRelationshipFromWorkspace(String workspaceJson,
                                                   String relationshipId) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(workspaceJson, "workspaceJson must not be null");
        Objects.requireNonNull(relationshipId, "relationshipId must not be null");
        return DataModellingFFI.call(transport, "remove_relationship_from_workspace", workspaceJson,
                relationshipId);
    }

    /**
     * Create a new domain.
     *
     * @param name the domain name; must not be null
     * @return domain JSON; never null
     * @throws DataModellingException on creation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.CREATE_DOMAIN, layer = "L3")
    public String createDomain(String name) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(name, "name must not be null");
        return DataModellingFFI.call(transport, "create_domain", name);
    }

    /**
     * Add domain to workspace.
     *
     * @param workspaceJson the workspace JSON; must not be null
     * @param domainId the domain ID; must not be null
     * @param domainName the domain name; must not be null
     * @return updated workspace JSON; never null
     * @throws DataModellingException on operation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.ADD_DOMAIN_TO_WORKSPACE, layer = "L3")
    public String addDomainToWorkspace(String workspaceJson, String domainId,
                                        String domainName) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(workspaceJson, "workspaceJson must not be null");
        Objects.requireNonNull(domainId, "domainId must not be null");
        Objects.requireNonNull(domainName, "domainName must not be null");
        return DataModellingFFI.call(transport, "add_domain_to_workspace", workspaceJson, domainId,
                domainName);
    }

    /**
     * Remove domain from workspace.
     *
     * @param workspaceJson the workspace JSON; must not be null
     * @param domainId the domain ID; must not be null
     * @return updated workspace JSON; never null
     * @throws DataModellingException on operation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.REMOVE_DOMAIN_FROM_WORKSPACE, layer = "L3")
    public String removeDomainFromWorkspace(String workspaceJson,
                                             String domainId) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(workspaceJson, "workspaceJson must not be null");
        Objects.requireNonNull(domainId, "domainId must not be null");
        return DataModellingFFI.call(transport, "remove_domain_from_workspace", workspaceJson,
                domainId);
    }

    /**
     * Add system to domain.
     *
     * @param workspaceJson the workspace JSON; must not be null
     * @param domainId the domain ID; must not be null
     * @param systemJson the system JSON; must not be null
     * @return updated workspace JSON; never null
     * @throws DataModellingException on operation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.ADD_SYSTEM_TO_DOMAIN, layer = "L3")
    public String addSystemToDomain(String workspaceJson, String domainId,
                                     String systemJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(workspaceJson, "workspaceJson must not be null");
        Objects.requireNonNull(domainId, "domainId must not be null");
        Objects.requireNonNull(systemJson, "systemJson must not be null");
        return DataModellingFFI.call(transport, "add_system_to_domain", workspaceJson, domainId,
                systemJson);
    }

    /**
     * Add ODCS node to domain.
     *
     * @param workspaceJson the workspace JSON; must not be null
     * @param domainId the domain ID; must not be null
     * @param nodeJson the node JSON; must not be null
     * @return updated workspace JSON; never null
     * @throws DataModellingException on operation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.ADD_ODCS_NODE_TO_DOMAIN, layer = "L3")
    public String addOdcsNodeToDomain(String workspaceJson, String domainId,
                                       String nodeJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(workspaceJson, "workspaceJson must not be null");
        Objects.requireNonNull(domainId, "domainId must not be null");
        Objects.requireNonNull(nodeJson, "nodeJson must not be null");
        return DataModellingFFI.call(transport, "add_odcs_node_to_domain", workspaceJson, domainId,
                nodeJson);
    }

    /**
     * Add CADS node to domain.
     *
     * @param workspaceJson the workspace JSON; must not be null
     * @param domainId the domain ID; must not be null
     * @param nodeJson the node JSON; must not be null
     * @return updated workspace JSON; never null
     * @throws DataModellingException on operation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.ADD_CADS_NODE_TO_DOMAIN, layer = "L3")
    public String addCadsNodeToDomain(String workspaceJson, String domainId,
                                       String nodeJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(workspaceJson, "workspaceJson must not be null");
        Objects.requireNonNull(domainId, "domainId must not be null");
        Objects.requireNonNull(nodeJson, "nodeJson must not be null");
        return DataModellingFFI.call(transport, "add_cads_node_to_domain", workspaceJson, domainId,
                nodeJson);
    }

    // ── Decision records (8) ──────────────────────────────────────────────────

    /**
     * Create a decision record.
     *
     * @param number the decision number
     * @param title the decision title; must not be null
     * @param context the decision context; must not be null
     * @param decision the decision text; must not be null
     * @param author the author; must not be null
     * @return decision JSON; never null
     * @throws DataModellingException on creation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.CREATE_DECISION, layer = "L3")
    public String createDecision(int number, String title, String context, String decision,
                                  String author) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(title, "title must not be null");
        Objects.requireNonNull(context, "context must not be null");
        Objects.requireNonNull(decision, "decision must not be null");
        Objects.requireNonNull(author, "author must not be null");
        return DataModellingFFI.call(transport, "create_decision", String.valueOf(number), title,
                context, decision, author);
    }

    /**
     * Create a decision index.
     *
     * @return index JSON; never null
     * @throws DataModellingException on creation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.CREATE_DECISION_INDEX, layer = "L3")
    public String createDecisionIndex() throws DataModellingException {
        requireOpen();
        return DataModellingFFI.call(transport, "create_decision_index");
    }

    /**
     * Parse decision YAML.
     *
     * @param yamlContent the YAML content; must not be null
     * @return decision JSON; never null
     * @throws DataModellingException on parse error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.PARSE_DECISION_YAML, layer = "L3")
    public String parseDecisionYaml(String yamlContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(yamlContent, "yamlContent must not be null");
        return DataModellingFFI.call(transport, "parse_decision_yaml", yamlContent);
    }

    /**
     * Export decision to YAML.
     *
     * @param decisionJson the decision JSON; must not be null
     * @return YAML string; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_DECISION_TO_YAML, layer = "L3")
    public String exportDecisionToYaml(String decisionJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(decisionJson, "decisionJson must not be null");
        return DataModellingFFI.call(transport, "export_decision_to_yaml", decisionJson);
    }

    /**
     * Export decision to Markdown.
     *
     * @param decisionJson the decision JSON; must not be null
     * @return Markdown string; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_DECISION_TO_MARKDOWN, layer = "L3")
    public String exportDecisionToMarkdown(String decisionJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(decisionJson, "decisionJson must not be null");
        return DataModellingFFI.call(transport, "export_decision_to_markdown", decisionJson);
    }

    /**
     * Parse decision index YAML.
     *
     * @param yamlContent the YAML content; must not be null
     * @return index JSON; never null
     * @throws DataModellingException on parse error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.PARSE_DECISION_INDEX_YAML, layer = "L3")
    public String parseDecisionIndexYaml(String yamlContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(yamlContent, "yamlContent must not be null");
        return DataModellingFFI.call(transport, "parse_decision_index_yaml", yamlContent);
    }

    /**
     * Export decision index to YAML.
     *
     * @param indexJson the index JSON; must not be null
     * @return YAML string; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_DECISION_INDEX_TO_YAML, layer = "L3")
    public String exportDecisionIndexToYaml(String indexJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(indexJson, "indexJson must not be null");
        return DataModellingFFI.call(transport, "export_decision_index_to_yaml", indexJson);
    }

    /**
     * Add decision to index.
     *
     * @param indexJson the index JSON; must not be null
     * @param decisionJson the decision JSON; must not be null
     * @param filename the filename; must not be null
     * @return updated index JSON; never null
     * @throws DataModellingException on operation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.ADD_DECISION_TO_INDEX, layer = "L3")
    public String addDecisionToIndex(String indexJson, String decisionJson,
                                      String filename) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(indexJson, "indexJson must not be null");
        Objects.requireNonNull(decisionJson, "decisionJson must not be null");
        Objects.requireNonNull(filename, "filename must not be null");
        return DataModellingFFI.call(transport, "add_decision_to_index", indexJson, decisionJson,
                filename);
    }

    // ── Knowledge base (9) ────────────────────────────────────────────────────

    /**
     * Create a knowledge article.
     *
     * @param number the article number
     * @param title the article title; must not be null
     * @param summary the article summary; must not be null
     * @param content the article content; must not be null
     * @param author the author; must not be null
     * @return article JSON; never null
     * @throws DataModellingException on creation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.CREATE_KNOWLEDGE_ARTICLE, layer = "L3")
    public String createKnowledgeArticle(int number, String title, String summary,
                                          String content, String author) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(title, "title must not be null");
        Objects.requireNonNull(summary, "summary must not be null");
        Objects.requireNonNull(content, "content must not be null");
        Objects.requireNonNull(author, "author must not be null");
        return DataModellingFFI.call(transport, "create_knowledge_article", String.valueOf(number),
                title, summary, content, author);
    }

    /**
     * Create a knowledge index.
     *
     * @return index JSON; never null
     * @throws DataModellingException on creation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.CREATE_KNOWLEDGE_INDEX, layer = "L3")
    public String createKnowledgeIndex() throws DataModellingException {
        requireOpen();
        return DataModellingFFI.call(transport, "create_knowledge_index");
    }

    /**
     * Parse knowledge article YAML.
     *
     * @param yamlContent the YAML content; must not be null
     * @return article JSON; never null
     * @throws DataModellingException on parse error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.PARSE_KNOWLEDGE_YAML, layer = "L3")
    public String parseKnowledgeYaml(String yamlContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(yamlContent, "yamlContent must not be null");
        return DataModellingFFI.call(transport, "parse_knowledge_yaml", yamlContent);
    }

    /**
     * Export knowledge article to YAML.
     *
     * @param articleJson the article JSON; must not be null
     * @return YAML string; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_KNOWLEDGE_TO_YAML, layer = "L3")
    public String exportKnowledgeToYaml(String articleJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(articleJson, "articleJson must not be null");
        return DataModellingFFI.call(transport, "export_knowledge_to_yaml", articleJson);
    }

    /**
     * Export knowledge article to Markdown.
     *
     * @param articleJson the article JSON; must not be null
     * @return Markdown string; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_KNOWLEDGE_TO_MARKDOWN, layer = "L3")
    public String exportKnowledgeToMarkdown(String articleJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(articleJson, "articleJson must not be null");
        return DataModellingFFI.call(transport, "export_knowledge_to_markdown", articleJson);
    }

    /**
     * Parse knowledge index YAML.
     *
     * @param yamlContent the YAML content; must not be null
     * @return index JSON; never null
     * @throws DataModellingException on parse error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.PARSE_KNOWLEDGE_INDEX_YAML, layer = "L3")
    public String parseKnowledgeIndexYaml(String yamlContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(yamlContent, "yamlContent must not be null");
        return DataModellingFFI.call(transport, "parse_knowledge_index_yaml", yamlContent);
    }

    /**
     * Export knowledge index to YAML.
     *
     * @param indexJson the index JSON; must not be null
     * @return YAML string; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_KNOWLEDGE_INDEX_TO_YAML, layer = "L3")
    public String exportKnowledgeIndexToYaml(String indexJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(indexJson, "indexJson must not be null");
        return DataModellingFFI.call(transport, "export_knowledge_index_to_yaml", indexJson);
    }

    /**
     * Add article to knowledge index.
     *
     * @param indexJson the index JSON; must not be null
     * @param articleJson the article JSON; must not be null
     * @param filename the filename; must not be null
     * @return updated index JSON; never null
     * @throws DataModellingException on operation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.ADD_ARTICLE_TO_KNOWLEDGE_INDEX, layer = "L3")
    public String addArticleToKnowledgeIndex(String indexJson, String articleJson,
                                              String filename) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(indexJson, "indexJson must not be null");
        Objects.requireNonNull(articleJson, "articleJson must not be null");
        Objects.requireNonNull(filename, "filename must not be null");
        return DataModellingFFI.call(transport, "add_article_to_knowledge_index", indexJson,
                articleJson, filename);
    }

    /**
     * Search knowledge articles.
     *
     * @param articlesJson the articles JSON; must not be null
     * @param query the search query; must not be null
     * @return search results JSON; never null
     * @throws DataModellingException on search error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.SEARCH_KNOWLEDGE_ARTICLES, layer = "L3")
    public String searchKnowledgeArticles(String articlesJson, String query) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(articlesJson, "articlesJson must not be null");
        Objects.requireNonNull(query, "query must not be null");
        return DataModellingFFI.call(transport, "search_knowledge_articles", articlesJson, query);
    }

    // ── Sketch (7) ────────────────────────────────────────────────────────────

    /**
     * Create a sketch.
     *
     * @param number the sketch number
     * @param title the sketch title; must not be null
     * @param sketchType the sketch type; must not be null
     * @param excalidrawData the Excalidraw data; must not be null
     * @return sketch JSON; never null
     * @throws DataModellingException on creation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.CREATE_SKETCH, layer = "L3")
    public String createSketch(int number, String title, String sketchType,
                                String excalidrawData) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(title, "title must not be null");
        Objects.requireNonNull(sketchType, "sketchType must not be null");
        Objects.requireNonNull(excalidrawData, "excalidrawData must not be null");
        return DataModellingFFI.call(transport, "create_sketch", String.valueOf(number), title,
                sketchType, excalidrawData);
    }

    /**
     * Create a sketch index.
     *
     * @return index JSON; never null
     * @throws DataModellingException on creation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.CREATE_SKETCH_INDEX, layer = "L3")
    public String createSketchIndex() throws DataModellingException {
        requireOpen();
        return DataModellingFFI.call(transport, "create_sketch_index");
    }

    /**
     * Parse sketch YAML.
     *
     * @param yamlContent the YAML content; must not be null
     * @return sketch JSON; never null
     * @throws DataModellingException on parse error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.PARSE_SKETCH_YAML, layer = "L3")
    public String parseSketchYaml(String yamlContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(yamlContent, "yamlContent must not be null");
        return DataModellingFFI.call(transport, "parse_sketch_yaml", yamlContent);
    }

    /**
     * Export sketch to YAML.
     *
     * @param sketchJson the sketch JSON; must not be null
     * @return YAML string; never null
     * @throws DataModellingException on export error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_SKETCH_TO_YAML, layer = "L3")
    public String exportSketchToYaml(String sketchJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(sketchJson, "sketchJson must not be null");
        return DataModellingFFI.call(transport, "export_sketch_to_yaml", sketchJson);
    }

    /**
     * Parse sketch index YAML.
     *
     * @param yamlContent the YAML content; must not be null
     * @return index JSON; never null
     * @throws DataModellingException on parse error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.PARSE_SKETCH_INDEX_YAML, layer = "L3")
    public String parseSketchIndexYaml(String yamlContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(yamlContent, "yamlContent must not be null");
        return DataModellingFFI.call(transport, "parse_sketch_index_yaml", yamlContent);
    }

    /**
     * Add sketch to index.
     *
     * @param indexJson the index JSON; must not be null
     * @param sketchJson the sketch JSON; must not be null
     * @param filename the filename; must not be null
     * @return updated index JSON; never null
     * @throws DataModellingException on operation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.ADD_SKETCH_TO_INDEX, layer = "L3")
    public String addSketchToIndex(String indexJson, String sketchJson,
                                    String filename) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(indexJson, "indexJson must not be null");
        Objects.requireNonNull(sketchJson, "sketchJson must not be null");
        Objects.requireNonNull(filename, "filename must not be null");
        return DataModellingFFI.call(transport, "add_sketch_to_index", indexJson, sketchJson,
                filename);
    }

    /**
     * Search sketches.
     *
     * @param sketchesJson the sketches JSON; must not be null
     * @param query the search query; must not be null
     * @return search results JSON; never null
     * @throws DataModellingException on search error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.SEARCH_SKETCHES, layer = "L3")
    public String searchSketches(String sketchesJson, String query) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(sketchesJson, "sketchesJson must not be null");
        Objects.requireNonNull(query, "query must not be null");
        return DataModellingFFI.call(transport, "search_sketches", sketchesJson, query);
    }

    // ── Validation (6) ────────────────────────────────────────────────────────

    /**
     * Validate ODPS YAML content.
     *
     * @param yamlContent the ODPS YAML content; must not be null
     * @throws DataModellingException on validation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_ODPS, layer = "L3")
    public void validateOdps(String yamlContent) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(yamlContent, "yamlContent must not be null");
        DataModellingFFI.callVoid(transport, "validate_odps", yamlContent);
    }

    /**
     * Validate table name.
     *
     * @param name the table name; must not be null
     * @return validation result JSON; never null
     * @throws DataModellingException on validation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_TABLE_NAME, layer = "L3")
    public String validateTableName(String name) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(name, "name must not be null");
        return DataModellingFFI.call(transport, "validate_table_name", name);
    }

    /**
     * Validate column name.
     *
     * @param name the column name; must not be null
     * @return validation result JSON; never null
     * @throws DataModellingException on validation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_COLUMN_NAME, layer = "L3")
    public String validateColumnName(String name) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(name, "name must not be null");
        return DataModellingFFI.call(transport, "validate_column_name", name);
    }

    /**
     * Validate data type.
     *
     * @param dataType the data type string; must not be null
     * @return validation result JSON; never null
     * @throws DataModellingException on validation error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_DATA_TYPE, layer = "L3")
    public String validateDataType(String dataType) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(dataType, "dataType must not be null");
        return DataModellingFFI.call(transport, "validate_data_type", dataType);
    }

    /**
     * Check for circular dependencies in relationships.
     *
     * @param relationshipsJson the relationships JSON; must not be null
     * @param sourceTableId the source table ID; must not be null
     * @param targetTableId the target table ID; must not be null
     * @return check result JSON; never null
     * @throws DataModellingException on check error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.CHECK_CIRCULAR_DEPENDENCY, layer = "L3")
    public String checkCircularDependency(String relationshipsJson, String sourceTableId,
                                           String targetTableId) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(relationshipsJson, "relationshipsJson must not be null");
        Objects.requireNonNull(sourceTableId, "sourceTableId must not be null");
        Objects.requireNonNull(targetTableId, "targetTableId must not be null");
        return DataModellingFFI.call(transport, "check_circular_dependency", relationshipsJson,
                sourceTableId, targetTableId);
    }

    /**
     * Detect naming conflicts between tables.
     *
     * @param existingTablesJson the existing tables JSON; must not be null
     * @param newTablesJson the new tables JSON; must not be null
     * @return conflicts JSON; never null
     * @throws DataModellingException on detection error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.DETECT_NAMING_CONFLICTS, layer = "L3")
    public String detectNamingConflicts(String existingTablesJson,
                                         String newTablesJson) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(existingTablesJson, "existingTablesJson must not be null");
        Objects.requireNonNull(newTablesJson, "newTablesJson must not be null");
        return DataModellingFFI.call(transport, "detect_naming_conflicts", existingTablesJson,
                newTablesJson);
    }

    // ── LLM integration (6) ───────────────────────────────────────────────────

    /**
     * Refine schema using LLM in offline mode.
     *
     * @param schema the schema JSON; must not be null
     * @param samples optional sample data; may be null
     * @param objectives optional refinement objectives; may be null
     * @param context optional context; may be null
     * @param config LLM configuration; must not be null
     * @return refined schema JSON; never null
     * @throws DataModellingException on refinement error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.REFINE_SCHEMA_WITH_LLM_OFFLINE, layer = "L3")
    public String refineSchemaWithLlmOffline(String schema, @Nullable String[] samples,
                                              @Nullable String[] objectives, @Nullable String context,
                                              LlmConfig config) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(schema, "schema must not be null");
        Objects.requireNonNull(config, "config must not be null");
        return DataModellingFFI.call(transport, "refine_schema_with_llm_offline", schema,
                DataModellingFFI.toJsonArray(samples != null ? samples : new String[0]),
                DataModellingFFI.toJsonArray(objectives != null ? objectives : new String[0]),
                context != null ? context : "",
                config.getModel() != null ? config.getModel() : "",
                String.valueOf(config.getTemperature()),
                String.valueOf(config.getMaxTokens()));
    }

    /**
     * Refine schema using LLM in online mode.
     *
     * @param schema the schema JSON; must not be null
     * @param samples optional sample data; may be null
     * @param objectives optional refinement objectives; may be null
     * @param context optional context; may be null
     * @param config LLM configuration; must not be null
     * @return refined schema JSON; never null
     * @throws DataModellingException on refinement error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.REFINE_SCHEMA_WITH_LLM_ONLINE, layer = "L3")
    public String refineSchemaWithLlmOnline(String schema, @Nullable String[] samples,
                                             @Nullable String[] objectives, @Nullable String context,
                                             LlmConfig config) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(schema, "schema must not be null");
        Objects.requireNonNull(config, "config must not be null");
        return DataModellingFFI.call(transport, "refine_schema_with_llm_online", schema,
                DataModellingFFI.toJsonArray(samples != null ? samples : new String[0]),
                DataModellingFFI.toJsonArray(objectives != null ? objectives : new String[0]),
                context != null ? context : "",
                config.getModel() != null ? config.getModel() : "",
                config.getBaseUrl(),
                String.valueOf(config.getTemperature()),
                String.valueOf(config.getMaxTokens()),
                String.valueOf(config.getTimeoutSeconds()));
    }

    /**
     * Match fields between source and target schemas using LLM.
     *
     * @param sourceSchema the source schema JSON; must not be null
     * @param targetSchema the target schema JSON; must not be null
     * @param config LLM configuration; must not be null
     * @return field mappings JSON; never null
     * @throws DataModellingException on matching error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.MATCH_FIELDS_WITH_LLM, layer = "L3")
    public String matchFieldsWithLlm(String sourceSchema, String targetSchema,
                                      LlmConfig config) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(sourceSchema, "sourceSchema must not be null");
        Objects.requireNonNull(targetSchema, "targetSchema must not be null");
        Objects.requireNonNull(config, "config must not be null");
        return DataModellingFFI.call(transport, "match_fields_with_llm", sourceSchema, targetSchema,
                config.getModel() != null ? config.getModel() : "",
                String.valueOf(config.getTemperature()),
                config.getBaseUrl());
    }

    /**
     * Enrich schema documentation using LLM.
     *
     * @param schema the schema JSON; must not be null
     * @param config LLM configuration; must not be null
     * @return enriched schema JSON; never null
     * @throws DataModellingException on enrichment error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.ENRICH_DOCUMENTATION_WITH_LLM, layer = "L3")
    public String enrichDocumentationWithLlm(String schema, LlmConfig config) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(schema, "schema must not be null");
        Objects.requireNonNull(config, "config must not be null");
        return DataModellingFFI.call(transport, "enrich_documentation_with_llm", schema,
                config.getModel() != null ? config.getModel() : "",
                String.valueOf(config.getTemperature()),
                config.getBaseUrl());
    }

    /**
     * Detect patterns in schema using LLM.
     *
     * @param schema the schema JSON; must not be null
     * @param config LLM configuration; must not be null
     * @return detected patterns JSON; never null
     * @throws DataModellingException on detection error or library unavailability
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.DETECT_PATTERNS_WITH_LLM, layer = "L3")
    public String detectPatternsWithLlm(String schema, LlmConfig config) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(schema, "schema must not be null");
        Objects.requireNonNull(config, "config must not be null");
        return DataModellingFFI.call(transport, "detect_patterns_with_llm", schema,
                config.getModel() != null ? config.getModel() : "",
                String.valueOf(config.getTemperature()),
                config.getBaseUrl());
    }

    /**
     * Check LLM availability with the given configuration.
     *
     * <p>Per Javadoc contract: availability check returns "false" on any failure.
     * This is specified behavior, not a fallback.</p>
     *
     * @param config LLM configuration; must not be null
     * @return "true" if available, "false" otherwise
     * @throws DataModellingException only on API invocation failure (not availability check)
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.CHECK_LLM_AVAILABILITY, layer = "L3")
    public String checkLlmAvailability(LlmConfig config) throws DataModellingException {
        requireOpen();
        Objects.requireNonNull(config, "config must not be null");
        try {
            return DataModellingFFI.call(transport, "check_llm_availability",
                    config.getModel() != null ? config.getModel() : "",
                    String.valueOf(config.getTemperature()),
                    config.getBaseUrl());
        } catch (DataModellingException e) {
            // Per Javadoc contract: availability check returns "false" on any failure
            return "false";
        }
    }

    // ── Pipeline — unsupported (3) ────────────────────────────────────────────

    /**
     * Infer schema from JSON data.
     *
     * <p>This capability is not yet exposed by data-modelling-sdk v2.3.0.
     * Implement when SDK adds infer_schema_from_json() function.</p>
     *
     * @param jsonData the JSON data; must not be null
     * @param config inference configuration; must not be null
     * @return inferred schema JSON; never null
     * @throws UnsupportedOperationException always, until SDK support is added
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.INFER_SCHEMA_FROM_JSON, layer = "L3")
    public String inferSchemaFromJson(String jsonData, InferenceConfig config) {
        throw new UnsupportedOperationException(
                "Schema inference from JSON is not yet exposed by data-modelling-sdk v2.3.0. " +
                "Implement when SDK adds infer_schema_from_json() function.");
    }

    /**
     * Map fields between source and target schemas.
     *
     * <p>This capability is not yet exposed by data-modelling-sdk v2.3.0.
     * Implement when SDK adds map_schemas() function.</p>
     *
     * @param sourceSchema the source schema JSON; must not be null
     * @param targetSchema the target schema JSON; must not be null
     * @param config mapping configuration; must not be null
     * @return field mappings JSON; never null
     * @throws UnsupportedOperationException always, until SDK support is added
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.MAP_SCHEMAS, layer = "L3")
    public String mapSchemas(String sourceSchema, String targetSchema, MappingConfig config) {
        throw new UnsupportedOperationException(
                "Schema field mapping is not yet exposed by data-modelling-sdk v2.3.0. " +
                "Implement when SDK adds map_schemas() function.");
    }

    /**
     * Generate transformation script from mapping result.
     *
     * <p>This capability is not yet exposed by data-modelling-sdk v2.3.0.
     * Implement when SDK adds generate_transform() function.</p>
     *
     * @param mappingResultJson the mapping result JSON; must not be null
     * @param format the output format (e.g. "sql", "python"); must not be null
     * @return transformation script; never null
     * @throws UnsupportedOperationException always, until SDK support is added
     */
    @DataModellingMapsToCapability(value = DataModellingCapability.GENERATE_TRANSFORM, layer = "L3")
    public String generateTransform(String mappingResultJson, String format) {
        throw new UnsupportedOperationException(
                "Transformation script generation is not yet exposed by data-modelling-sdk v2.3.0. " +
                "Implement when SDK adds generate_transform() function.");
    }
}
