/*
 * Copyright (c) 2004-2026 The YAWL Foundation. All rights reserved.
 * The YAWL Foundation is a collaboration of individuals and
 * organisations who are committed to improving workflow technology.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.datamodelling.bridge;

import java.lang.reflect.Method;
import java.util.EnumSet;
import java.util.Set;

/**
 * Startup gate that validates L3 domain-method coverage for every DataModelling capability.
 *
 * <p>Call {@link #validate()} once at application startup (or in test setUp).
 * Throws {@link CapabilityRegistryException} if any supported {@link DataModellingCapability}
 * lacks an L3 method annotated with {@link DataModellingMapsToCapability}.
 *
 * <p>L2 coverage is not checked per-capability because {@link DataModellingL2} uses a
 * dispatcher pattern — a single {@code dm_call} native function handles all 67 SDK
 * operations. L2 is validated structurally at construction time via struct-layout probes.
 *
 * <p>Pipeline capabilities ({@code INFER_SCHEMA_FROM_JSON}, {@code MAP_SCHEMAS},
 * {@code GENERATE_TRANSFORM}) are excluded from the gate: they throw
 * {@link UnsupportedOperationException} by design until the SDK exposes them.
 *
 * @generated by ggen from ontology
 * @pattern WCP-NB-02
 */
public final class DataModellingCapabilityRegistry {

    /** Capabilities not yet exposed by data-modelling-sdk v2.3.0 — excluded from gate. */
    private static final Set<DataModellingCapability> UNSUPPORTED = EnumSet.of(
            DataModellingCapability.INFER_SCHEMA_FROM_JSON,
            DataModellingCapability.MAP_SCHEMAS,
            DataModellingCapability.GENERATE_TRANSFORM);

    /**
     * Validates that every supported capability has at least one L3 method implementation.
     *
     * @throws CapabilityRegistryException if any supported capability lacks L3 coverage
     */
    public static void validate() {
        Set<DataModellingCapability> coveredL3 = EnumSet.noneOf(DataModellingCapability.class);
        collectL3Coverage(DataModellingL3.class, coveredL3);

        StringBuilder missing = new StringBuilder();
        for (DataModellingCapability cap : DataModellingCapability.values()) {
            if (UNSUPPORTED.contains(cap)) {
                continue;
            }
            if (!coveredL3.contains(cap)) {
                missing.append("\n  ").append(cap.name()).append(" [missing L3 @DataModellingMapsToCapability]");
            }
        }

        if (!missing.isEmpty()) {
            throw new CapabilityRegistryException(
                    "DataModelling L3 capability coverage gaps:" + missing
                    + "\nAnnotate each DataModellingL3 method with @DataModellingMapsToCapability.");
        }
    }

    private static void collectL3Coverage(Class<?> clazz, Set<DataModellingCapability> covered) {
        for (Method method : clazz.getDeclaredMethods()) {
            for (DataModellingMapsToCapability a :
                    method.getAnnotationsByType(DataModellingMapsToCapability.class)) {
                if ("L3".equals(a.layer())) {
                    covered.add(a.value());
                }
            }
        }
    }

    private DataModellingCapabilityRegistry() {}

    /**
     * Thrown when a capability lacks L3 coverage at startup validation.
     */
    public static final class CapabilityRegistryException extends RuntimeException {
        CapabilityRegistryException(String message) {
            super(message);
        }
    }
}
