%% Generated by gen-ttl. DO NOT EDIT.
%% process_mining_bridge: gen_server wrapping the process_mining Rust NIF.
%% State: map of UUID (binary) → opaque resource.
-module(process_mining_bridge).
-behaviour(gen_server).

-export([start_link/0, stop/0]).
-export([init/1, handle_call/3, handle_cast/2, handle_info/2,
terminate/2, code_change/3]).

%% Public capability exports (one per capability)
-export([
    get_dotted_chart/2,
    get_event_timestamps/2,
    get_object_attribute_changes/2,
    oc_declare_conformance/2,
    discover_alpha_ppp/2,
    discover_dfg/1,
    discover_dfg_from_ocel/1,
    discover_oc_declare/2,
    add_init_exit_events_to_ocel/1,
    export_dfg_image_png/2,
    export_dfg_image_svg/2,
    export_dfg_png/2,
    export_petri_net_image_png/2,
    export_petri_net_image_svg/2,
    flatten_ocel_on/2,
    log_to_activity_projection/1,
    locel_add_e2o/4,
    locel_add_event/6,
    locel_add_event_type/3,
    locel_add_o2o/4,
    locel_add_object/5,
    locel_add_object_type/3,
    locel_construct_ocel/1,
    locel_delete_e2o/3,
    locel_delete_o2o/3,
    locel_get_e2o/2,
    locel_get_e2o_rev/2,
    locel_get_ev_attr_val/3,
    locel_get_ev_by_id/2,
    locel_get_ev_id/2,
    locel_get_ev_time/2,
    locel_get_ev_type/2,
    locel_get_ev_type_of/2,
    locel_get_ev_types/1,
    locel_get_evs_of_type/2,
    locel_get_full_ev/2,
    locel_get_full_ob/2,
    locel_get_o2o/2,
    locel_get_o2o_rev/2,
    locel_get_ob_attr_vals/3,
    locel_get_ob_by_id/2,
    locel_get_ob_id/2,
    locel_get_ob_type/2,
    locel_get_ob_type_of/2,
    locel_get_ob_types/1,
    locel_get_obs_of_type/2,
    locel_new/0,
    index_link_ocel/1,
    num_events/1,
    num_objects/1,
    ocel_type_stats/1,
    slim_link_ocel/1,
    test_some_inputs/5
]).

-define(SERVER, ?MODULE).

%%% ─── Public API ──────────────────────────────────────────

start_link() ->
    gen_server:start_link({local, ?SERVER}, ?MODULE, [], []).

stop() ->
    gen_server:stop(?SERVER).

get_dotted_chart(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {get_dotted_chart, Uuid0, Arg1}).

get_event_timestamps(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {get_event_timestamps, Uuid0, Arg1}).

get_object_attribute_changes(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {get_object_attribute_changes, Uuid0, Arg1}).

oc_declare_conformance(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {oc_declare_conformance, Uuid0, Arg1}).

discover_alpha_ppp(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {discover_alpha_ppp, Uuid0, Arg1}).

discover_dfg(Uuid0) ->
    gen_server:call(?SERVER, {discover_dfg, Uuid0}).

discover_dfg_from_ocel(Uuid0) ->
    gen_server:call(?SERVER, {discover_dfg_from_ocel, Uuid0}).

discover_oc_declare(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {discover_oc_declare, Uuid0, Arg1}).

add_init_exit_events_to_ocel(Uuid0) ->
    gen_server:call(?SERVER, {add_init_exit_events_to_ocel, Uuid0}).

export_dfg_image_png(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {export_dfg_image_png, Uuid0, Arg1}).

export_dfg_image_svg(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {export_dfg_image_svg, Uuid0, Arg1}).

export_dfg_png(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {export_dfg_png, Uuid0, Arg1}).

export_petri_net_image_png(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {export_petri_net_image_png, Uuid0, Arg1}).

export_petri_net_image_svg(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {export_petri_net_image_svg, Uuid0, Arg1}).

flatten_ocel_on(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {flatten_ocel_on, Uuid0, Arg1}).

log_to_activity_projection(Uuid0) ->
    gen_server:call(?SERVER, {log_to_activity_projection, Uuid0}).

locel_add_e2o(Uuid0, Arg1, Arg2, Arg3) ->
    gen_server:call(?SERVER, {locel_add_e2o, Uuid0, Arg1, Arg2, Arg3}).

locel_add_event(Uuid0, Arg1, Arg2, Arg3, Arg4, Arg5) ->
    gen_server:call(?SERVER, {locel_add_event, Uuid0, Arg1, Arg2, Arg3, Arg4, Arg5}).

locel_add_event_type(Uuid0, Arg1, Arg2) ->
    gen_server:call(?SERVER, {locel_add_event_type, Uuid0, Arg1, Arg2}).

locel_add_o2o(Uuid0, Arg1, Arg2, Arg3) ->
    gen_server:call(?SERVER, {locel_add_o2o, Uuid0, Arg1, Arg2, Arg3}).

locel_add_object(Uuid0, Arg1, Arg2, Arg3, Arg4) ->
    gen_server:call(?SERVER, {locel_add_object, Uuid0, Arg1, Arg2, Arg3, Arg4}).

locel_add_object_type(Uuid0, Arg1, Arg2) ->
    gen_server:call(?SERVER, {locel_add_object_type, Uuid0, Arg1, Arg2}).

locel_construct_ocel(Uuid0) ->
    gen_server:call(?SERVER, {locel_construct_ocel, Uuid0}).

locel_delete_e2o(Uuid0, Arg1, Arg2) ->
    gen_server:call(?SERVER, {locel_delete_e2o, Uuid0, Arg1, Arg2}).

locel_delete_o2o(Uuid0, Arg1, Arg2) ->
    gen_server:call(?SERVER, {locel_delete_o2o, Uuid0, Arg1, Arg2}).

locel_get_e2o(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_e2o, Uuid0, Arg1}).

locel_get_e2o_rev(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_e2o_rev, Uuid0, Arg1}).

locel_get_ev_attr_val(Uuid0, Arg1, Arg2) ->
    gen_server:call(?SERVER, {locel_get_ev_attr_val, Uuid0, Arg1, Arg2}).

locel_get_ev_by_id(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_ev_by_id, Uuid0, Arg1}).

locel_get_ev_id(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_ev_id, Uuid0, Arg1}).

locel_get_ev_time(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_ev_time, Uuid0, Arg1}).

locel_get_ev_type(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_ev_type, Uuid0, Arg1}).

locel_get_ev_type_of(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_ev_type_of, Uuid0, Arg1}).

locel_get_ev_types(Uuid0) ->
    gen_server:call(?SERVER, {locel_get_ev_types, Uuid0}).

locel_get_evs_of_type(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_evs_of_type, Uuid0, Arg1}).

locel_get_full_ev(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_full_ev, Uuid0, Arg1}).

locel_get_full_ob(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_full_ob, Uuid0, Arg1}).

locel_get_o2o(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_o2o, Uuid0, Arg1}).

locel_get_o2o_rev(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_o2o_rev, Uuid0, Arg1}).

locel_get_ob_attr_vals(Uuid0, Arg1, Arg2) ->
    gen_server:call(?SERVER, {locel_get_ob_attr_vals, Uuid0, Arg1, Arg2}).

locel_get_ob_by_id(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_ob_by_id, Uuid0, Arg1}).

locel_get_ob_id(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_ob_id, Uuid0, Arg1}).

locel_get_ob_type(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_ob_type, Uuid0, Arg1}).

locel_get_ob_type_of(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_ob_type_of, Uuid0, Arg1}).

locel_get_ob_types(Uuid0) ->
    gen_server:call(?SERVER, {locel_get_ob_types, Uuid0}).

locel_get_obs_of_type(Uuid0, Arg1) ->
    gen_server:call(?SERVER, {locel_get_obs_of_type, Uuid0, Arg1}).

locel_new() ->
    gen_server:call(?SERVER, {locel_new}).

index_link_ocel(Uuid0) ->
    gen_server:call(?SERVER, {index_link_ocel, Uuid0}).

num_events(Uuid0) ->
    gen_server:call(?SERVER, {num_events, Uuid0}).

num_objects(Uuid0) ->
    gen_server:call(?SERVER, {num_objects, Uuid0}).

ocel_type_stats(Uuid0) ->
    gen_server:call(?SERVER, {ocel_type_stats, Uuid0}).

slim_link_ocel(Uuid0) ->
    gen_server:call(?SERVER, {slim_link_ocel, Uuid0}).

test_some_inputs(Arg0, Arg1, Arg2, Arg3, Arg4) ->
    gen_server:call(?SERVER, {test_some_inputs, Arg0, Arg1, Arg2, Arg3, Arg4}).

%%% ─── gen_server callbacks ───────────────────────────────

init([]) -> {ok, #{}}.

handle_cast(_Msg, State) -> {noreply, State}.

handle_info(_Info, State) -> {noreply, State}.

terminate(_Reason, _State) -> ok.

code_change(_OldVsn, State, _Extra) -> {ok, State}.

%%% ─── handle_call dispatch ───────────────────────────────

handle_call({get_dotted_chart, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:get_dotted_chart(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({get_event_timestamps, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:get_event_timestamps(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({get_object_attribute_changes, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:get_object_attribute_changes(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({oc_declare_conformance, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:oc_declare_conformance(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({discover_alpha_ppp, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
NewResource = process_mining_nif:discover_alpha_ppp(Uuid0, Arg1),
NewUuid = uuid(),
State1 = maps:put(NewUuid, NewResource, State),
{reply, {ok, NewUuid}, State1}
end;

handle_call({discover_dfg, Uuid0}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
NewResource = process_mining_nif:discover_dfg(Uuid0),
NewUuid = uuid(),
State1 = maps:put(NewUuid, NewResource, State),
{reply, {ok, NewUuid}, State1}
end;

handle_call({discover_dfg_from_ocel, Uuid0}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
NewResource = process_mining_nif:discover_dfg_from_ocel(Uuid0),
NewUuid = uuid(),
State1 = maps:put(NewUuid, NewResource, State),
{reply, {ok, NewUuid}, State1}
end;

handle_call({discover_oc_declare, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:discover_oc_declare(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({add_init_exit_events_to_ocel, Uuid0}, _From, State) ->
case maps:take(Uuid0, State) of
error -> {reply, {error, not_found}, State};
{_OldResource, State0} ->
NewResource = process_mining_nif:add_init_exit_events_to_ocel(Uuid0),
NewUuid = uuid(),
State1 = maps:put(NewUuid, NewResource, State0),
{reply, {ok, NewUuid}, State1}
end;

handle_call({export_dfg_image_png, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:export_dfg_image_png(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({export_dfg_image_svg, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:export_dfg_image_svg(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({export_dfg_png, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:export_dfg_png(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({export_petri_net_image_png, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:export_petri_net_image_png(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({export_petri_net_image_svg, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:export_petri_net_image_svg(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({flatten_ocel_on, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
NewResource = process_mining_nif:flatten_ocel_on(Uuid0, Arg1),
NewUuid = uuid(),
State1 = maps:put(NewUuid, NewResource, State),
{reply, {ok, NewUuid}, State1}
end;

handle_call({log_to_activity_projection, Uuid0}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
NewResource = process_mining_nif:log_to_activity_projection(Uuid0),
NewUuid = uuid(),
State1 = maps:put(NewUuid, NewResource, State),
{reply, {ok, NewUuid}, State1}
end;

handle_call({locel_add_e2o, Uuid0, Arg1, Arg2, Arg3}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_add_e2o(Uuid0, Arg1, Arg2, Arg3),
{reply, Result, State}
end;

handle_call({locel_add_event, Uuid0, Arg1, Arg2, Arg3, Arg4, Arg5}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_add_event(Uuid0, Arg1, Arg2, Arg3, Arg4, Arg5),
{reply, Result, State}
end;

handle_call({locel_add_event_type, Uuid0, Arg1, Arg2}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_add_event_type(Uuid0, Arg1, Arg2),
{reply, Result, State}
end;

handle_call({locel_add_o2o, Uuid0, Arg1, Arg2, Arg3}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_add_o2o(Uuid0, Arg1, Arg2, Arg3),
{reply, Result, State}
end;

handle_call({locel_add_object, Uuid0, Arg1, Arg2, Arg3, Arg4}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_add_object(Uuid0, Arg1, Arg2, Arg3, Arg4),
{reply, Result, State}
end;

handle_call({locel_add_object_type, Uuid0, Arg1, Arg2}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_add_object_type(Uuid0, Arg1, Arg2),
{reply, Result, State}
end;

handle_call({locel_construct_ocel, Uuid0}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
NewResource = process_mining_nif:locel_construct_ocel(Uuid0),
NewUuid = uuid(),
State1 = maps:put(NewUuid, NewResource, State),
{reply, {ok, NewUuid}, State1}
end;

handle_call({locel_delete_e2o, Uuid0, Arg1, Arg2}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_delete_e2o(Uuid0, Arg1, Arg2),
{reply, Result, State}
end;

handle_call({locel_delete_o2o, Uuid0, Arg1, Arg2}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_delete_o2o(Uuid0, Arg1, Arg2),
{reply, Result, State}
end;

handle_call({locel_get_e2o, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_e2o(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_e2o_rev, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_e2o_rev(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_ev_attr_val, Uuid0, Arg1, Arg2}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ev_attr_val(Uuid0, Arg1, Arg2),
{reply, Result, State}
end;

handle_call({locel_get_ev_by_id, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ev_by_id(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_ev_id, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ev_id(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_ev_time, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ev_time(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_ev_type, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ev_type(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_ev_type_of, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ev_type_of(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_ev_types, Uuid0}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ev_types(Uuid0),
{reply, Result, State}
end;

handle_call({locel_get_evs_of_type, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_evs_of_type(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_full_ev, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_full_ev(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_full_ob, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_full_ob(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_o2o, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_o2o(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_o2o_rev, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_o2o_rev(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_ob_attr_vals, Uuid0, Arg1, Arg2}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ob_attr_vals(Uuid0, Arg1, Arg2),
{reply, Result, State}
end;

handle_call({locel_get_ob_by_id, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ob_by_id(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_ob_id, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ob_id(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_ob_type, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ob_type(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_ob_type_of, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ob_type_of(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_get_ob_types, Uuid0}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_ob_types(Uuid0),
{reply, Result, State}
end;

handle_call({locel_get_obs_of_type, Uuid0, Arg1}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:locel_get_obs_of_type(Uuid0, Arg1),
{reply, Result, State}
end;

handle_call({locel_new}, _From, State) ->
Resource = process_mining_nif:locel_new(),
Uuid = uuid(),
State1 = maps:put(Uuid, Resource, State),
{reply, {ok, Uuid}, State1};

handle_call({index_link_ocel, Uuid0}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
NewResource = process_mining_nif:index_link_ocel(Uuid0),
NewUuid = uuid(),
State1 = maps:put(NewUuid, NewResource, State),
{reply, {ok, NewUuid}, State1}
end;

handle_call({num_events, Uuid0}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:num_events(Uuid0),
{reply, Result, State}
end;

handle_call({num_objects, Uuid0}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:num_objects(Uuid0),
{reply, Result, State}
end;

handle_call({ocel_type_stats, Uuid0}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
Result = process_mining_nif:ocel_type_stats(Uuid0),
{reply, Result, State}
end;

handle_call({slim_link_ocel, Uuid0}, _From, State) ->
case maps:get(Uuid0, State, not_found) of
not_found -> {reply, {error, not_found}, State};
_Resource ->
NewResource = process_mining_nif:slim_link_ocel(Uuid0),
NewUuid = uuid(),
State1 = maps:put(NewUuid, NewResource, State),
{reply, {ok, NewUuid}, State1}
end;

handle_call({test_some_inputs, Arg0, Arg1, Arg2, Arg3, Arg4}, _From, State) ->
Result = process_mining_nif:test_some_inputs(Arg0, Arg1, Arg2, Arg3, Arg4),
{reply, Result, State};

%% Catch-all
handle_call(Unknown, _From, State) ->
{reply, {error, {unknown_call, Unknown}}, State}.

%%% ─── Internal helpers ───────────────────────────────────

%% Generate a UUID v4 using crypto (OTP 28, no external deps).
uuid() ->
<<A:32, B:16, C:16, D:16, E:48>> = crypto:strong_rand_bytes(16),
C1 = (C band 16#0FFF) bor 16#4000,
D1 = (D band 16#3FFF) bor 16#8000,
iolist_to_binary(io_lib:format(
"~8.16.0b-~4.16.0b-~4.16.0b-~4.16.0b-~12.16.0b",
[A, B, C1, D1, E])).
