# YAWL v6.0.0 Quality Gates GitHub Actions Workflow
# ==================================================
# Orchestrates all five quality infrastructure components:
#   1. PIT mutation testing (nightly)
#   2. Pact contract generation and verification
#   3. ArchUnit architecture enforcement (every PR)
#   4. OWASP ZAP DAST + Trivy container scan
#   5. Test quality metrics collection
#
# Triggers:
#   push to main         -> full quality gate
#   pull_request         -> architecture + contract + fast security checks
#   schedule (nightly)   -> mutation testing + full DAST scan

name: YAWL Quality Gates

on:
  push:
    branches: [main, "release/**"]
  pull_request:
    branches: [main]
  schedule:
    # Nightly at 02:00 UTC
    - cron: "0 2 * * *"

env:
  JAVA_VERSION: "21"
  MAVEN_OPTS: "-Xmx2g -XX:+UseG1GC"

jobs:

  # ─────────────────────────────────────────────────────────────────────────
  # JOB 1: Architecture Tests (every push and PR - fast gate)
  # ─────────────────────────────────────────────────────────────────────────
  architecture-tests:
    name: Architecture Enforcement (ArchUnit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: Compile production and test sources
        run: mvn clean test-compile --no-transfer-progress

      - name: Run ArchUnit layer and cycle detection tests
        run: |
          mvn -P architecture-test surefire:test \
            -Dtest="YawlLayerArchitectureTest,YawlPackageBoundaryTest,YawlCycleDetectionTest" \
            --no-transfer-progress

      - name: Upload ArchUnit results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: archunit-results
          path: target/surefire-reports/

  # ─────────────────────────────────────────────────────────────────────────
  # JOB 2: Contract Tests (PRs and main)
  # ─────────────────────────────────────────────────────────────────────────
  contract-tests:
    name: Pact Contract Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: Run consumer contract tests and generate pacts
        run: |
          mvn -P contract clean test \
            -Dtest="EngineApiConsumerContractTest,StatelessApiConsumerContractTest,IntegrationApiConsumerContractTest" \
            --no-transfer-progress
        env:
          PACT_BROKER_URL: ${{ vars.PACT_BROKER_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

      - name: Publish pacts to broker
        if: github.ref == 'refs/heads/main'
        run: mvn -P contract pact:publish --no-transfer-progress
        env:
          PACT_BROKER_URL: ${{ vars.PACT_BROKER_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

      - name: Upload generated pact files
        uses: actions/upload-artifact@v4
        with:
          name: pact-files
          path: target/pacts/

  # ─────────────────────────────────────────────────────────────────────────
  # JOB 3: Dependency Security Scan (every push)
  # ─────────────────────────────────────────────────────────────────────────
  dependency-security:
    name: Dependency CVE Scan (OWASP)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: Run OWASP Dependency-Check
        run: |
          mvn -P prod dependency-check:check --no-transfer-progress
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - name: Enforce dependency security policy
        run: |
          mvn surefire:test \
            -Dtest=DependencySecurityPolicyTest \
            -Dowasp.report.path=target/dependency-check-report.xml \
            --no-transfer-progress

      - name: Upload OWASP reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: owasp-reports
          path: target/dependency-check-report.*

  # ─────────────────────────────────────────────────────────────────────────
  # JOB 4: Container Security Scan (main branch and releases)
  # ─────────────────────────────────────────────────────────────────────────
  container-security:
    name: Container Vulnerability Scan (Trivy)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: Build container image
        run: |
          mvn clean package -DskipTests --no-transfer-progress
          docker build -t yawl-engine:${{ github.sha }} .

      - name: Run Trivy container scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: "yawl-engine:${{ github.sha }}"
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          trivy-config: quality/security-scanning/trivy-scan-config.yaml

      - name: Upload Trivy SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  # ─────────────────────────────────────────────────────────────────────────
  # JOB 5: DAST Security Scan (nightly only)
  # ─────────────────────────────────────────────────────────────────────────
  dast-security:
    name: OWASP ZAP DAST Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: Start YAWL engine in background
        run: |
          mvn clean package -DskipTests --no-transfer-progress
          java -jar target/yawl-engine-*.jar &
          # Wait for engine to be ready
          timeout 120 bash -c 'until curl -sf http://localhost:8080/actuator/health; do sleep 3; done'

      - name: Run OWASP ZAP automation scan
        uses: zaproxy/action-af@v0.10.0
        with:
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          autorun_file: quality/security-scanning/zap-scan-config.yaml
        env:
          ZAP_TEST_PASSWORD: ${{ secrets.ZAP_TEST_PASSWORD }}

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-reports
          path: target/zap-reports/

  # ─────────────────────────────────────────────────────────────────────────
  # JOB 6: Mutation Testing (nightly only)
  # ─────────────────────────────────────────────────────────────────────────
  mutation-testing:
    name: PIT Mutation Testing
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: Restore PIT history cache
        uses: actions/cache@v4
        with:
          path: target/pit-history.bin
          key: pit-history-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            pit-history-${{ github.ref }}-
            pit-history-main-

      - name: Run PIT mutation analysis
        run: |
          mvn -P mutation clean test-compile \
            org.pitest:pitest-maven:mutationCoverage \
            -DwithHistory \
            --no-transfer-progress
        timeout-minutes: 120

      - name: Enforce mutation kill-rate thresholds
        run: |
          mvn surefire:test \
            -Dtest=MutationCoverageVerifier \
            -Dpit.reports.dir=target/pit-reports \
            --no-transfer-progress

      - name: Upload PIT HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pit-reports
          path: target/pit-reports/

      - name: Save PIT history cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: target/pit-history.bin
          key: pit-history-${{ github.ref }}-${{ github.sha }}

  # ─────────────────────────────────────────────────────────────────────────
  # JOB 7: Test Quality Metrics (main branch)
  # ─────────────────────────────────────────────────────────────────────────
  test-quality-metrics:
    name: Test Quality Metrics
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: Run full test suite with Surefire reports
        run: mvn clean test --no-transfer-progress

      - name: Analyze test execution times
        run: |
          mvn surefire:test \
            -Dtest=TestExecutionTimeAnalyzer \
            -Dsurefire.reports.dir=target/surefire-reports \
            --no-transfer-progress

      - name: Score test maintenance quality
        run: |
          mvn surefire:test \
            -Dtest=TestMaintenanceScorer \
            -Dtest.sources.dir=test \
            --no-transfer-progress
