# Reusable Workflow - Deploy to Kubernetes
# YAWL Workflow Engine CI/CD
#
# Usage:
#   jobs:
#     deploy:
#       uses: ./.github/workflows/reusable-deploy.yaml
#       with:
#         environment: production
#         version: '5.2.0'
#         cloud_provider: aws
#       secrets: inherit

name: Reusable Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: string
      version:
        description: 'Version to deploy'
        required: true
        type: string
      cloud_provider:
        description: 'Cloud provider (aws|gcp|azure)'
        required: true
        type: string
      image_tag:
        description: 'Container image tag'
        required: false
        default: ''
        type: string
      helm_values_file:
        description: 'Helm values file path'
        required: false
        default: ''
        type: string
      timeout_minutes:
        description: 'Deployment timeout in minutes'
        required: false
        default: 15
        type: number
      dry_run:
        description: 'Dry run (skip actual deployment)'
        required: false
        default: false
        type: boolean
    outputs:
      deployment_url:
        description: 'Deployment URL'
        value: ${{ jobs.deploy.outputs.url }}
      deployment_status:
        description: 'Deployment status'
        value: ${{ jobs.deploy.outputs.status }}

env:
  HELM_VERSION: '3.14.0'
  KUBECTL_VERSION: '1.29.0'

jobs:
  deploy:
    name: Deploy to ${{ inputs.cloud_provider }}
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.output.outputs.url }}
      status: ${{ steps.output.outputs.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image tag
        id: image
        run: |
          IMAGE_TAG="${{ inputs.image_tag }}"
          if [ -z "$IMAGE_TAG" ]; then
            IMAGE_TAG="${{ inputs.version }}"
          fi
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      # AWS Authentication
      - name: Configure AWS credentials (OIDC)
        if: inputs.cloud_provider == 'aws'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
          role-session-name: yawl-deploy-${{ github.run_id }}

      - name: Update kubeconfig for EKS
        if: inputs.cloud_provider == 'aws'
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION || 'us-east-1' }}

      # GCP Authentication
      - name: Authenticate to Google Cloud (OIDC)
        if: inputs.cloud_provider == 'gcp'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: 'access_token'

      - name: Set up Cloud SDK
        if: inputs.cloud_provider == 'gcp'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get GKE credentials
        if: inputs.cloud_provider == 'gcp'
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GCP_REGION || 'us-central1' }}

      # Azure Authentication
      - name: Azure Login (OIDC)
        if: inputs.cloud_provider == 'azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        if: inputs.cloud_provider == 'azure'
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_CLUSTER_NAME }} \
            --overwrite-existing

      # Common deployment steps
      - name: Create namespace
        run: |
          kubectl create namespace yawl-${{ inputs.environment }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create image pull secret
        if: inputs.cloud_provider != 'gcp'
        run: |
          if [ "${{ inputs.cloud_provider }}" == "aws" ]; then
            kubectl create secret docker-registry regcred \
              --namespace=yawl-${{ inputs.environment }} \
              --docker-server=${{ secrets.ECR_REGISTRY }} \
              --docker-username=AWS \
              --docker-password=$(aws ecr get-login-password) \
              --dry-run=client -o yaml | kubectl apply -f -
          elif [ "${{ inputs.cloud_provider }}" == "azure" ]; then
            kubectl create secret docker-registry regcred \
              --namespace=yawl-${{ inputs.environment }} \
              --docker-server=${{ secrets.ACR_REGISTRY }} \
              --docker-username=${{ secrets.ACR_USERNAME }} \
              --docker-password=${{ secrets.ACR_PASSWORD }} \
              --dry-run=client -o yaml | kubectl apply -f -
          fi

      - name: Set Helm values file
        id: values
        run: |
          VALUES_FILE="${{ inputs.helm_values_file }}"
          if [ -z "$VALUES_FILE" ]; then
            if [ "${{ inputs.cloud_provider }}" == "aws" ]; then
              VALUES_FILE="helm/yawl/values-aws.yaml"
            elif [ "${{ inputs.cloud_provider }}" == "gcp" ]; then
              VALUES_FILE="helm/yawl/values-gcp.yaml"
            elif [ "${{ inputs.cloud_provider }}" == "azure" ]; then
              VALUES_FILE="helm/yawl/values-azure.yaml"
            else
              VALUES_FILE="helm/yawl/values.yaml"
            fi
          fi
          echo "file=$VALUES_FILE" >> $GITHUB_OUTPUT

      - name: Helm deployment (dry-run)
        if: inputs.dry_run
        run: |
          helm upgrade --install yawl ./helm/yawl \
            --namespace yawl-${{ inputs.environment }} \
            --set image.tag=${{ steps.image.outputs.tag }} \
            --set environment=${{ inputs.environment }} \
            --values ${{ steps.values.outputs.file }} \
            --dry-run \
            --debug

      - name: Helm deployment
        if: ${{ !inputs.dry_run }}
        run: |
          helm upgrade --install yawl ./helm/yawl \
            --namespace yawl-${{ inputs.environment }} \
            --set image.tag=${{ steps.image.outputs.tag }} \
            --set environment=${{ inputs.environment }} \
            --values ${{ steps.values.outputs.file }} \
            --wait \
            --timeout ${{ inputs.timeout_minutes }}m \
            --history-max 10

      - name: Wait for deployment rollout
        if: ${{ !inputs.dry_run }}
        run: |
          kubectl rollout status deployment/yawl \
            --namespace=yawl-${{ inputs.environment }} \
            --timeout=${{ inputs.timeout_minutes }}m

      - name: Verify deployment
        if: ${{ !inputs.dry_run }}
        run: |
          echo "=== Deployment Status ==="
          kubectl get pods -n yawl-${{ inputs.environment }} -l app.kubernetes.io/name=yawl

          echo "=== Service Status ==="
          kubectl get services -n yawl-${{ inputs.environment }}

      - name: Get deployment URL
        id: output
        if: ${{ !inputs.dry_run }}
        run: |
          # Try to get the ingress URL
          URL=$(kubectl get ingress -n yawl-${{ inputs.environment }} yawl -o jsonpath='{.spec.rules[0].host}' 2>/dev/null || echo "")

          if [ -z "$URL" ]; then
            # Try load balancer
            URL=$(kubectl get service yawl -n yawl-${{ inputs.environment }} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || \
                  kubectl get service yawl -n yawl-${{ inputs.environment }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "")
          fi

          if [ -n "$URL" ]; then
            echo "url=https://$URL" >> $GITHUB_OUTPUT
          else
            echo "url=pending" >> $GITHUB_OUTPUT
          fi

          echo "status=deployed" >> $GITHUB_OUTPUT

      - name: Deployment summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Parameter | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Environment | ${{ inputs.environment }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Version | ${{ inputs.version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Cloud Provider | ${{ inputs.cloud_provider }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Image Tag | ${{ steps.image.outputs.tag }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Status | ${{ job.status }} |" >> $GITHUB_STEP_SUMMARY
