/*
 * Copyright (c) 2004-2026 The YAWL Foundation. All rights reserved.
 * The YAWL Foundation is a collaboration of individuals and
 * organisations who are committed to improving workflow technology.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.integration.gateway.kong;

import org.yawlfoundation.yawl.integration.gateway.GatewayCircuitBreakerConfig;
import org.yawlfoundation.yawl.integration.gateway.GatewayRouteDefinition;

import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * Generates Kong Gateway declarative YAML configuration for YAWL API routes.
 *
 * <p>Produces a complete {@code kong.yml} (Kong 3.x deck format) covering:
 * <ul>
 *   <li>Service definition pointing to the YAWL engine upstream</li>
 *   <li>Route definitions with path matching and HTTP method restrictions</li>
 *   <li>Rate-limiting plugin per route (per-consumer, Redis-backed)</li>
 *   <li>JWT plugin for OAuth2 bearer token verification on authenticated routes</li>
 *   <li>Correlation-ID plugin for distributed tracing</li>
 *   <li>Prometheus plugin for metrics collection</li>
 *   <li>Upstream health check configuration (circuit breaker)</li>
 * </ul>
 *
 * <h2>Usage</h2>
 * <pre>
 * {@code
 * String kongYaml = KongConfigurationGenerator.generate(
 *     "http://yawl-engine:8080",
 *     "https://keycloak.example.com/realms/yawl",
 *     "yawl-api",
 *     GatewayCircuitBreakerConfig.kongDefault()
 * );
 * Files.writeString(Path.of("kong.yml"), kongYaml);
 * // Deploy: deck sync --config kong.yml
 * }
 * </pre>
 *
 * @author YAWL Foundation
 * @version 6.0.0
 * @since 6.0.0
 */
public final class KongConfigurationGenerator {

    private KongConfigurationGenerator() {
        throw new UnsupportedOperationException(
                "KongConfigurationGenerator is a utility class and cannot be instantiated.");
    }

    /**
     * Generate a complete Kong 3.x declarative YAML configuration for YAWL.
     *
     * @param upstreamBaseUrl  YAWL engine base URL (e.g. {@code http://yawl-engine:8080})
     * @param oidcIssuerUri    OIDC provider issuer URI for JWT validation
     * @param audience         expected JWT audience claim
     * @param circuitBreaker   circuit breaker configuration for the upstream
     * @return complete Kong declarative YAML string
     */
    public static String generate(String upstreamBaseUrl, String oidcIssuerUri,
                                  String audience, GatewayCircuitBreakerConfig circuitBreaker) {
        Objects.requireNonNull(upstreamBaseUrl, "upstreamBaseUrl must not be null");
        Objects.requireNonNull(oidcIssuerUri,   "oidcIssuerUri must not be null");
        Objects.requireNonNull(audience,         "audience must not be null");
        Objects.requireNonNull(circuitBreaker,   "circuitBreaker must not be null");

        List<GatewayRouteDefinition> routes =
                GatewayRouteDefinition.yawlV1Routes(upstreamBaseUrl);

        StringBuilder yaml = new StringBuilder();
        appendHeader(yaml);
        appendServices(yaml, upstreamBaseUrl, circuitBreaker, routes);
        appendGlobalPlugins(yaml);

        return yaml.toString();
    }

    // -------------------------------------------------------------------------
    // YAML sections
    // -------------------------------------------------------------------------

    private static void appendHeader(StringBuilder yaml) {
        yaml.append("# YAWL v6.0.0 Kong Gateway Configuration\n");
        yaml.append("# Generated by KongConfigurationGenerator\n");
        yaml.append("# Deploy with: deck sync --config kong.yml\n");
        yaml.append("#\n");
        yaml.append("_format_version: \"3.0\"\n");
        yaml.append("_transform: true\n\n");
    }

    private static void appendServices(StringBuilder yaml, String upstreamBaseUrl,
                                       GatewayCircuitBreakerConfig cb,
                                       List<GatewayRouteDefinition> routes) {
        yaml.append("services:\n");
        yaml.append("  - name: yawl-engine\n");
        yaml.append("    url: ").append(upstreamBaseUrl).append("\n");
        yaml.append("    connect_timeout: 10000\n");
        yaml.append("    read_timeout: 30000\n");
        yaml.append("    write_timeout: 30000\n");
        yaml.append("    retries: 0  # Retries handled by YAWL resilience layer\n");
        yaml.append("    routes:\n");

        for (GatewayRouteDefinition route : routes) {
            appendRoute(yaml, route);
        }
        yaml.append("\n");

        appendUpstreamHealthChecks(yaml, cb);
    }

    private static void appendRoute(StringBuilder yaml, GatewayRouteDefinition route) {
        yaml.append("      - name: ").append(route.getRouteId()).append("\n");
        yaml.append("        paths:\n");

        // Convert path template params to regex: {caseId} -> (?<caseId>[^/]+)
        String pathPattern = route.getPathPattern().replaceAll("\\{([^}]+)}", "(?<$1>[^/]+)");
        yaml.append("          - ~/").append(stripLeadingSlash(pathPattern)).append("\n");

        if (!route.getMethods().isEmpty()) {
            yaml.append("        methods:\n");
            for (GatewayRouteDefinition.HttpMethod m : route.getMethods()) {
                yaml.append("          - ").append(m.name()).append("\n");
            }
        }
        yaml.append("        strip_path: false\n");
        yaml.append("        plugins:\n");

        // Rate limiting plugin
        appendRateLimitPlugin(yaml, route.getRateLimitTier());

        // JWT authentication plugin (if required)
        if (route.isRequiresAuthentication()) {
            appendJwtPlugin(yaml);
        }

        // Correlation ID plugin on all routes
        appendCorrelationIdPlugin(yaml);
    }

    private static void appendRateLimitPlugin(StringBuilder yaml,
                                              GatewayRouteDefinition.RateLimitTier tier) {
        yaml.append("          - name: rate-limiting\n");
        yaml.append("            config:\n");
        yaml.append("              minute: ").append(tier.getRequestsPerWindow()).append("\n");
        yaml.append("              policy: redis\n");
        yaml.append("              redis_host: ${REDIS_HOST:-redis}\n");
        yaml.append("              redis_port: 6379\n");
        yaml.append("              fault_tolerant: false\n");
        yaml.append("              hide_client_headers: false\n");
        yaml.append("              error_code: 429\n");
        yaml.append("              error_message: \"YAWL API rate limit exceeded. "
                    + "Tier: ").append(tier.name()).append("\"\n");
    }

    private static void appendJwtPlugin(StringBuilder yaml) {
        yaml.append("          - name: jwt\n");
        yaml.append("            config:\n");
        yaml.append("              key_claim_name: iss\n");
        yaml.append("              claims_to_verify:\n");
        yaml.append("                - exp\n");
        yaml.append("                - nbf\n");
        yaml.append("              maximum_expiration: 86400\n");
        yaml.append("              header_names:\n");
        yaml.append("                - authorization\n");
        yaml.append("              run_on_preflight: false\n");
    }

    private static void appendCorrelationIdPlugin(StringBuilder yaml) {
        yaml.append("          - name: correlation-id\n");
        yaml.append("            config:\n");
        yaml.append("              header_name: X-Request-ID\n");
        yaml.append("              generator: uuid#counter\n");
        yaml.append("              echo_downstream: true\n");
    }

    private static void appendUpstreamHealthChecks(StringBuilder yaml,
                                                   GatewayCircuitBreakerConfig cb) {
        yaml.append("upstreams:\n");
        yaml.append("  - name: yawl-engine\n");
        yaml.append("    algorithm: round-robin\n");
        yaml.append("    slots: 100\n");
        yaml.append("    healthchecks:\n");
        yaml.append("      active:\n");
        yaml.append("        type: http\n");
        yaml.append("        http_path: /yawl/actuator/health\n");
        yaml.append("        healthy:\n");
        yaml.append("          interval: ").append(cb.getCheckPeriodSeconds()).append("\n");
        yaml.append("          successes: 2\n");
        yaml.append("        unhealthy:\n");
        yaml.append("          interval: ").append(cb.getCheckPeriodSeconds()).append("\n");
        yaml.append("          http_failures: ").append(cb.getHttpFailureThreshold()).append("\n");
        yaml.append("          timeouts: ").append(cb.getHttpFailureThreshold()).append("\n");
        yaml.append("      passive:\n");
        yaml.append("        healthy:\n");
        yaml.append("          successes: 5\n");
        yaml.append("        unhealthy:\n");
        yaml.append("          http_failures: ").append(cb.getHttpFailureThreshold()).append("\n");
        yaml.append("          http_statuses: [429, 500, 502, 503, 504]\n");
        yaml.append("          timeouts: ").append(cb.getHttpFailureThreshold()).append("\n\n");
    }

    private static void appendGlobalPlugins(StringBuilder yaml) {
        yaml.append("plugins:\n");
        yaml.append("  # Prometheus metrics - global\n");
        yaml.append("  - name: prometheus\n");
        yaml.append("    config:\n");
        yaml.append("      per_consumer: true\n");
        yaml.append("      status_code_metrics: true\n");
        yaml.append("      latency_metrics: true\n");
        yaml.append("      bandwidth_metrics: true\n");
        yaml.append("      upstream_health_metrics: true\n\n");
        yaml.append("  # Request ID propagation - global\n");
        yaml.append("  - name: request-id\n");
        yaml.append("    config:\n");
        yaml.append("      header_name: X-Request-ID\n");
        yaml.append("      generator: uuid\n");
        yaml.append("      echo_downstream: true\n");
    }

    private static String stripLeadingSlash(String path) {
        return path.startsWith("/") ? path.substring(1) : path;
    }
}
