apiVersion: v1
kind: ConfigMap
metadata:
  name: security-policy
  namespace: kube-system
  labels:
    app: security
    compliance: hipaa,soc2,pci-dss
data:
  policy.yaml: |
    # YAWL Security Policy Configuration
    # Compliance Standards: HIPAA, SOC2, PCI-DSS

    security:
      versioning: "1.0"
      last_updated: "2026-02-14"
      compliance_frameworks:
        - hipaa
        - soc2
        - pci-dss

    authentication:
      # HIPAA: §164.312(a)(2)(i) - Unique user identification
      # SOC2: CC6.1, CC6.2 - User access controls
      # PCI-DSS: 8.1.1, 8.1.4 - User identification and authentication
      methods:
        - oauth2
        - saml2
        - mfa
        - certificate-based
      mfa_required: true
      mfa_grace_period_days: 0
      password_policy:
        minimum_length: 14
        require_uppercase: true
        require_lowercase: true
        require_numbers: true
        require_special_chars: true
        expiration_days: 90
        history_count: 12
        lockout_threshold: 5
        lockout_duration_minutes: 30

    authorization:
      # HIPAA: §164.312(a)(2)(ii) - Emergency access procedure
      # SOC2: CC6.3 - Role-based access control
      # PCI-DSS: 7.1 - Need-to-know access principle
      model: role-based-access-control
      principle: principle-of-least-privilege
      access_review_frequency_months: 3
      just_in_time_access: true
      approval_required_roles:
        - admin
        - security
        - compliance

    encryption:
      # HIPAA: §164.312(a)(2)(iv) - Encryption and decryption
      # SOC2: CC6.1 - Cryptographic controls
      # PCI-DSS: 3.4 - Encryption of data in transit and at rest
      at_rest:
        enabled: true
        algorithm: AES-256-GCM
        key_rotation_days: 90
        key_manager: kms
      in_transit:
        enabled: true
        minimum_tls_version: "1.3"
        cipher_suites:
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      key_management:
        provider: cloud-kms
        rotation_enabled: true
        rotation_frequency_days: 90
        backup_enabled: true

    audit:
      # HIPAA: §164.312(b) - Audit controls
      # SOC2: CC7.2 - System monitoring and logging
      # PCI-DSS: 10 - Logging and monitoring
      enabled: true
      log_retention_days: 2555  # 7 years for HIPAA
      log_integrity_verification: true
      centralized_logging: true
      audit_events:
        - authentication_attempts
        - authorization_changes
        - data_access
        - configuration_changes
        - encryption_key_changes
        - user_privilege_escalation
        - deletion_events
        - policy_violations
      real_time_alerting: true
      alert_severity_levels:
        - critical
        - high
        - medium

    data_protection:
      # HIPAA: §164.308(a)(3) - Workforce security
      # SOC2: CC7.3 - Detecting and investigating anomalies
      # PCI-DSS: 3.2, 3.3 - Data protection
      data_classification_enabled: true
      pii_detection_enabled: true
      pii_masking_enabled: true
      data_minimization: true
      retention_policy:
        default_retention_days: 1825  # 5 years
        sensitive_retention_days: 2555  # 7 years
      deletion_verification: true

    network_security:
      # HIPAA: §164.312(a)(1) - Access controls
      # SOC2: CC7.4 - System monitoring
      # PCI-DSS: 1 - Network segmentation
      network_segmentation: true
      firewall_enabled: true
      ddos_protection: true
      waf_enabled: true
      ip_whitelist_enabled: true
      vpn_required: false
      api_rate_limiting: true
      api_throttling: true

    incident_response:
      # HIPAA: §164.308(a)(6) - Incident procedures
      # SOC2: CC7.1 - Risk management
      # PCI-DSS: 12.10 - Incident response procedures
      enabled: true
      response_time_hours: 1
      investigation_retention_days: 2555
      escalation_procedures: true
      notification_procedures: true
      forensics_enabled: true
      backup_retention_days: 2555

    vendor_management:
      # HIPAA: §164.308(a)(3)(ii)(B) - Workforce clearance
      # SOC2: CC9.2 - Third-party risks
      # PCI-DSS: 12.8 - Vendor management
      vendor_assessment_required: true
      vendor_audit_frequency_months: 12
      data_processing_agreements: true
      nda_required: true
      vendor_compliance_frameworks:
        - hipaa
        - soc2
        - pci-dss

    vulnerability_management:
      # HIPAA: §164.308(a)(1)(ii)(B) - Security awareness training
      # SOC2: CC6.2 - Personnel security
      # PCI-DSS: 6.2 - Security patches and updates
      scanning_frequency: "daily"
      penetration_testing_frequency_months: 3
      patching_timeline_days: 30
      critical_patching_timeline_days: 7
      vulnerability_disclosure: true
      responsible_disclosure_policy: true

    access_control:
      # HIPAA: §164.312(a)(2) - User access policies
      # SOC2: CC6 - Logical access controls
      # PCI-DSS: 8 - User identification and access management
      session_timeout_minutes: 30
      concurrent_session_limit: 1
      admin_approval_for_elevated_access: true
      temporary_access_expiration: true
      periodic_access_review: true
      access_review_frequency_days: 90
      inactive_account_lockout_days: 90
