package org.yawlfoundation.yawl.util.java25.records;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for auto-generated record methods.
 *
 * Chicago TDD: Validates that records correctly implement
 * equals(), hashCode(), toString(), and accessor methods.
 */
@DisplayName("Record Auto-Generated Methods")
class RecordAutoGeneratedMethodsTest {

    record TaskDefinition(String taskId, String taskName, String description) {
    }

    record WorkItemStatus(String caseId, String itemId, String status, long timestamp) {
    }

    record Coordinates(double latitude, double longitude, double elevation) {
    }

    @Test
    @DisplayName("Record auto-generates equals() method")
    void testRecordEqualsMethod() {
        TaskDefinition t1 = new TaskDefinition("task-1", "Review", "Manual review");
        TaskDefinition t2 = new TaskDefinition("task-1", "Review", "Manual review");
        TaskDefinition t3 = new TaskDefinition("task-2", "Approve", "Approval");

        assertEquals(t1, t2);
        assertNotEquals(t1, t3);
    }

    @Test
    @DisplayName("Record equals() is reflexive")
    void testRecordEqualsReflexive() {
        TaskDefinition t = new TaskDefinition("task-1", "Review", "Manual");
        assertEquals(t, t);
    }

    @Test
    @DisplayName("Record equals() is symmetric")
    void testRecordEqualsSymmetric() {
        TaskDefinition t1 = new TaskDefinition("task-1", "Review", "Manual");
        TaskDefinition t2 = new TaskDefinition("task-1", "Review", "Manual");

        assertEquals(t1, t2);
        assertEquals(t2, t1);
    }

    @Test
    @DisplayName("Record equals() is transitive")
    void testRecordEqualsTransitive() {
        TaskDefinition t1 = new TaskDefinition("task-1", "Review", "Manual");
        TaskDefinition t2 = new TaskDefinition("task-1", "Review", "Manual");
        TaskDefinition t3 = new TaskDefinition("task-1", "Review", "Manual");

        assertEquals(t1, t2);
        assertEquals(t2, t3);
        assertEquals(t1, t3);
    }

    @Test
    @DisplayName("Record equals() handles null values")
    void testRecordEqualsWithNulls() {
        TaskDefinition t1 = new TaskDefinition("task-1", null, "description");
        TaskDefinition t2 = new TaskDefinition("task-1", null, "description");
        TaskDefinition t3 = new TaskDefinition("task-1", "Name", "description");

        assertEquals(t1, t2);
        assertNotEquals(t1, t3);
    }

    @Test
    @DisplayName("Record equals() returns false for different type")
    void testRecordEqualsWithDifferentType() {
        TaskDefinition t = new TaskDefinition("task-1", "Review", "Manual");

        assertNotEquals(t, "task-1");
        assertNotEquals(t, 123);
        assertNotEquals(t, null);
    }

    @Test
    @DisplayName("Record auto-generates hashCode() method")
    void testRecordHashCode() {
        TaskDefinition t1 = new TaskDefinition("task-1", "Review", "Manual");
        TaskDefinition t2 = new TaskDefinition("task-1", "Review", "Manual");

        assertEquals(t1.hashCode(), t2.hashCode());
    }

    @Test
    @DisplayName("Equal records have equal hash codes")
    void testRecordHashCodeConsistency() {
        TaskDefinition t1 = new TaskDefinition("task-1", "Review", "Manual");
        TaskDefinition t2 = new TaskDefinition("task-1", "Review", "Manual");

        assertEquals(t1, t2);
        assertEquals(t1.hashCode(), t2.hashCode());
    }

    @Test
    @DisplayName("Different records usually have different hash codes")
    void testRecordHashCodeDifference() {
        TaskDefinition t1 = new TaskDefinition("task-1", "Review", "Manual");
        TaskDefinition t2 = new TaskDefinition("task-2", "Approve", "Approval");
        TaskDefinition t3 = new TaskDefinition("task-1", "Review", "Different");

        assertNotEquals(t1.hashCode(), t2.hashCode());
        assertNotEquals(t1.hashCode(), t3.hashCode());
    }

    @Test
    @DisplayName("Records work correctly in HashMap")
    void testRecordInHashMap() {
        Map<TaskDefinition, String> map = new HashMap<>();

        TaskDefinition key1 = new TaskDefinition("task-1", "Review", "Manual");
        TaskDefinition key2 = new TaskDefinition("task-1", "Review", "Manual");

        map.put(key1, "value1");
        assertEquals("value1", map.get(key2));
    }

    @Test
    @DisplayName("Records work correctly in HashSet")
    void testRecordInHashSet() {
        Set<TaskDefinition> set = new HashSet<>();

        TaskDefinition t1 = new TaskDefinition("task-1", "Review", "Manual");
        TaskDefinition t2 = new TaskDefinition("task-1", "Review", "Manual");
        TaskDefinition t3 = new TaskDefinition("task-2", "Approve", "Approval");

        set.add(t1);
        set.add(t2);
        set.add(t3);

        assertEquals(2, set.size());
        assertTrue(set.contains(t1));
        assertTrue(set.contains(t2));
        assertTrue(set.contains(t3));
    }

    @Test
    @DisplayName("Record auto-generates toString() method")
    void testRecordToString() {
        TaskDefinition t = new TaskDefinition("task-1", "Review", "Manual review");

        String str = t.toString();

        assertTrue(str.contains("TaskDefinition"));
        assertTrue(str.contains("task-1"));
        assertTrue(str.contains("Review"));
        assertTrue(str.contains("Manual review"));
    }

    @Test
    @DisplayName("Record toString() includes all fields")
    void testRecordToStringCompleteness() {
        WorkItemStatus status = new WorkItemStatus("case-001", "item-123", "active", 1708876800L);

        String str = status.toString();

        assertTrue(str.contains("case-001"));
        assertTrue(str.contains("item-123"));
        assertTrue(str.contains("active"));
        assertTrue(str.contains("1708876800"));
    }

    @Test
    @DisplayName("Record toString() handles null values")
    void testRecordToStringWithNulls() {
        TaskDefinition t = new TaskDefinition("task-1", null, null);

        String str = t.toString();

        assertTrue(str.contains("task-1"));
        assertTrue(str.contains("null"));
    }

    @Test
    @DisplayName("Record auto-generates accessor methods")
    void testRecordAccessorMethods() {
        TaskDefinition t = new TaskDefinition("task-1", "Review", "Manual");

        assertEquals("task-1", t.taskId());
        assertEquals("Review", t.taskName());
        assertEquals("Manual", t.description());
    }

    @Test
    @DisplayName("Record accessors return same values consistently")
    void testRecordAccessorConsistency() {
        WorkItemStatus status = new WorkItemStatus("case-001", "item-123", "active", 123456L);

        assertEquals("case-001", status.caseId());
        assertEquals("case-001", status.caseId());

        assertEquals("item-123", status.itemId());
        assertEquals("item-123", status.itemId());

        assertEquals("active", status.status());
        assertEquals("active", status.status());
    }

    @Test
    @DisplayName("Record accessors return all field values")
    void testRecordAccessorsReturnAllFields() {
        Coordinates coords = new Coordinates(51.5074, -0.1278, 15.0);

        assertTrue(coords.latitude() > 0);
        assertTrue(coords.longitude() < 0);
        assertTrue(coords.elevation() > 0);
    }

    @Test
    @DisplayName("Record maintains field order in accessors")
    void testRecordFieldOrder() {
        TaskDefinition t = new TaskDefinition("id", "name", "desc");

        assertEquals("id", t.taskId());
        assertEquals("name", t.taskName());
        assertEquals("desc", t.description());
    }

    @Test
    @DisplayName("Multiple record instances have independent states")
    void testRecordIndependence() {
        TaskDefinition t1 = new TaskDefinition("task-1", "Review", "Manual");
        TaskDefinition t2 = new TaskDefinition("task-2", "Approve", "Approval");

        assertEquals("task-1", t1.taskId());
        assertEquals("task-2", t2.taskId());

        assertNotEquals(t1.taskId(), t2.taskId());
    }

    @Test
    @DisplayName("Record with numeric fields computes hash correctly")
    void testRecordWithNumericFieldsHashCode() {
        Coordinates c1 = new Coordinates(51.5074, -0.1278, 15.0);
        Coordinates c2 = new Coordinates(51.5074, -0.1278, 15.0);

        assertEquals(c1.hashCode(), c2.hashCode());
    }

    @Test
    @DisplayName("Record toString() output is parseable-like")
    void testRecordToStringFormatting() {
        WorkItemStatus status = new WorkItemStatus("case-1", "item-1", "pending", System.currentTimeMillis());

        String str = status.toString();

        assertTrue(str.startsWith("WorkItemStatus"));
        assertTrue(str.contains("("));
        assertTrue(str.contains(")"));
    }

    @Test
    @DisplayName("Record equals() is deterministic across calls")
    void testRecordEqualsDeterministic() {
        TaskDefinition t1 = new TaskDefinition("task-1", "Review", "Manual");
        TaskDefinition t2 = new TaskDefinition("task-1", "Review", "Manual");

        for (int i = 0; i < 1000; i++) {
            assertEquals(t1, t2);
            assertEquals(t1.hashCode(), t2.hashCode());
        }
    }
}
