/*
 * Copyright (c) 2004-2026 The YAWL Foundation. All rights reserved.
 * The YAWL Foundation is a collaboration of individuals and
 * organisations who are committed to improving workflow technology.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.dspy.email;

import java.time.Instant;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Immutable email value object for Chicago TDD email-driven integration tests.
 *
 * <p>Represents an email generated by DSPy reporting components, enabling
 * assertions on email content, recipients, and metadata.</p>
 *
 * @param from sender email address
 * @param to recipient email address(es)
 * @param cc CC recipients (may be empty)
 * @param subject email subject line
 * @param body email body content (plain text)
 * @param timestamp when email was generated
 *
 * @author YAWL Foundation
 * @version 6.0.0
 */
public record Email(
        String from,
        String to,
        List<String> cc,
        String subject,
        String body,
        Instant timestamp
) {
    /**
     * Compact constructor with validation.
     */
    public Email {
        Objects.requireNonNull(from, "from must not be null");
        Objects.requireNonNull(to, "to must not be null");
        Objects.requireNonNull(subject, "subject must not be null");
        Objects.requireNonNull(body, "body must not be null");
        Objects.requireNonNull(timestamp, "timestamp must not be null");
        cc = cc == null ? Collections.emptyList() : List.copyOf(cc);
    }

    /**
     * Creates a new builder for Email.
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Returns the full email as RFC 5322 formatted text.
     */
    public String toRfc5322() {
        StringBuilder sb = new StringBuilder();
        sb.append("From: ").append(from).append("\n");
        sb.append("To: ").append(to).append("\n");
        if (!cc.isEmpty()) {
            sb.append("Cc: ").append(String.join(", ", cc)).append("\n");
        }
        sb.append("Subject: ").append(subject).append("\n");
        sb.append("Date: ").append(timestamp).append("\n");
        sb.append("\n");
        sb.append(body);
        return sb.toString();
    }

    /**
     * Builder for Email.
     */
    public static final class Builder {
        private String from = "noreply@yawlfoundation.org";
        private String to;
        private List<String> cc = Collections.emptyList();
        private String subject;
        private String body;
        private Instant timestamp = Instant.now();

        public Builder from(String from) {
            this.from = from;
            return this;
        }

        public Builder to(String to) {
            this.to = to;
            return this;
        }

        public Builder cc(List<String> cc) {
            this.cc = cc;
            return this;
        }

        public Builder subject(String subject) {
            this.subject = subject;
            return this;
        }

        public Builder body(String body) {
            this.body = body;
            return this;
        }

        public Builder timestamp(Instant timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        public Email build() {
            return new Email(from, to, cc, subject, body, timestamp);
        }
    }
}
