#!/bin/bash

# YAWL ECS Fargate Quick Start Script
# This script automates the initial setup and deployment

set -e

echo "=========================================="
echo "YAWL ECS Fargate Quick Start"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
echo -e "${YELLOW}Checking prerequisites...${NC}"

if ! command -v terraform &> /dev/null; then
    echo -e "${RED}ERROR: Terraform is not installed${NC}"
    exit 1
fi

if ! command -v aws &> /dev/null; then
    echo -e "${RED}ERROR: AWS CLI is not installed${NC}"
    exit 1
fi

if ! command -v docker &> /dev/null; then
    echo -e "${RED}ERROR: Docker is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✓ All prerequisites are met${NC}"
echo ""

# Get AWS Account ID
echo -e "${YELLOW}Detecting AWS account...${NC}"
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo -e "${GREEN}✓ AWS Account ID: $AWS_ACCOUNT_ID${NC}"
echo ""

# Initialize Terraform
echo -e "${YELLOW}Initializing Terraform...${NC}"
terraform init
echo -e "${GREEN}✓ Terraform initialized${NC}"
echo ""

# Check if terraform.tfvars exists
if [ -f "terraform.tfvars" ]; then
    echo -e "${YELLOW}terraform.tfvars already exists${NC}"
    read -p "Do you want to overwrite it? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm terraform.tfvars
    fi
fi

# Create terraform.tfvars if it doesn't exist
if [ ! -f "terraform.tfvars" ]; then
    echo -e "${YELLOW}Creating terraform.tfvars...${NC}"

    # Get environment preference
    echo "Select environment:"
    echo "1) dev"
    echo "2) staging"
    echo "3) prod"
    read -p "Enter choice [1-3]: " env_choice

    case $env_choice in
        1) ENVIRONMENT="dev" ;;
        2) ENVIRONMENT="staging" ;;
        3) ENVIRONMENT="prod" ;;
        *) ENVIRONMENT="dev" ;;
    esac

    # Get container image
    echo ""
    echo -e "${YELLOW}Container Image Configuration${NC}"
    read -p "Enter ECR repository name (default: yawl): " ECR_REPO
    ECR_REPO=${ECR_REPO:-yawl}

    ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPO:latest"
    echo "ECR URI: $ECR_URI"

    # Get notification email
    echo ""
    echo -e "${YELLOW}Monitoring Configuration${NC}"
    read -p "Enter email for CloudWatch alarms (optional): " ALARM_EMAIL

    # Generate secure password
    RDS_PASSWORD=$(openssl rand -base64 12)

    # Create tfvars file
    cat > terraform.tfvars << EOF
# YAWL ECS Fargate Configuration
# Auto-generated by quickstart.sh

aws_region     = "us-east-1"
aws_account_id = "$AWS_ACCOUNT_ID"
environment    = "$ENVIRONMENT"

# VPC Configuration
vpc_cidr           = "10.0.0.0/16"
availability_zones = ["us-east-1a", "us-east-1b", "us-east-1c"]
public_subnets    = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
private_subnets   = ["10.0.11.0/24", "10.0.12.0/24", "10.0.13.0/24"]

# RDS Configuration
rds_allocated_storage      = 100
rds_instance_class         = "db.t3.medium"
rds_engine_version         = "15.3"
rds_master_username        = "yawlroot"
rds_master_password        = "$RDS_PASSWORD"
rds_multi_az               = true
rds_backup_retention_period = 7
rds_deletion_protection    = true

# ECS Configuration
container_image            = "$ECR_URI"
container_port             = 8080
task_cpu                   = 1024
task_memory                = 2048
desired_count              = 2
min_capacity               = 2
max_capacity               = 10
target_cpu_utilization     = 70
target_memory_utilization  = 80

# ECS Environment Variables
ecs_environment_variables = {
  LOG_LEVEL = "INFO"
  APP_NAME  = "YAWL"
  DEBUG     = "false"
}

# ALB Configuration
alb_target_port           = 8080
health_check_path        = "/"
health_check_matcher     = "200-299"

# Monitoring
enable_monitoring         = true
alarm_email               = "$ALARM_EMAIL"
monitoring_log_retention_days = 7

# Tags
tags = {
  Team       = "DevOps"
  CostCenter = "Engineering"
}
EOF

    echo -e "${GREEN}✓ terraform.tfvars created${NC}"
    echo ""
    echo -e "${YELLOW}RDS Master Password: $RDS_PASSWORD${NC}"
    echo -e "${YELLOW}Please save this password securely!${NC}"
    echo ""
fi

# Validate configuration
echo -e "${YELLOW}Validating Terraform configuration...${NC}"
terraform validate
echo -e "${GREEN}✓ Configuration is valid${NC}"
echo ""

# Show plan
echo -e "${YELLOW}Generating Terraform plan...${NC}"
terraform plan -out=tfplan
echo ""

# Confirm deployment
echo -e "${YELLOW}Ready to deploy YAWL ECS Fargate infrastructure${NC}"
read -p "Do you want to continue with deployment? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Deployment cancelled"
    exit 1
fi

# Apply configuration
echo -e "${YELLOW}Applying Terraform configuration...${NC}"
terraform apply tfplan
echo -e "${GREEN}✓ Infrastructure deployed successfully!${NC}"
echo ""

# Display outputs
echo -e "${GREEN}=========================================="
echo "Deployment Complete"
echo "=========================================${NC}"
echo ""
terraform output
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "1. Get ALB DNS name: terraform output alb_dns_name"
echo "2. Test application: curl http://\$(terraform output -raw alb_dns_name)"
echo "3. View logs: aws logs tail /ecs/$(terraform output -raw deployment_info | grep environment | cut -d'=' -f2 | tr -d ' ')-yawl --follow"
echo "4. Monitor: terraform output cloudwatch_dashboard_url"
echo ""
echo -e "${YELLOW}For more information, see README.md${NC}"
