/* rust4pm NIF - generated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Parse OCEL2 JSON string (C interface)
 */
void *rust4pm_parse_ocel2_json(const char *json, uintptr_t json_len);

/**
 * Discover Directly Follows Graph (C interface)
 */
char *rust4pm_discover_dfg(const void *handle);

/**
 * Check conformance with PNML (C interface)
 */
void *rust4pm_check_conformance(const void *handle, const char *pnml, uintptr_t pnml_len);

/**
 * Free OCEL handle (C interface)
 */
void rust4pm_free_ocel(void *handle);

/**
 * Free C string (C interface)
 */
void rust4pm_free_string(char *s);

/**
 * Free conformance result (C interface)
 */
void rust4pm_free_conformance(void *result);
