/*
 * Copyright (c) 2004-2026 The YAWL Foundation. All rights reserved.
 * The YAWL Foundation is a collaboration of individuals and
 * organisations who are committed to improving workflow technology.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.integration.temporal;

import java.time.Instant;
import java.util.List;

/**
 * Represents a single fork execution path within a case temporal exploration.
 *
 * <p>A {@code CaseFork} is an immutable snapshot of one execution path taken when
 * exploring alternative task sequences in a workflow case. It captures the decision
 * path (ordered task IDs chosen), the resulting case state (serialized XML), and
 * execution metadata (duration, completion status, timestamp).</p>
 *
 * <p>Forks are produced by {@link TemporalForkEngine#fork(String, ForkPolicy, java.time.Duration)}
 * and collected in {@link TemporalForkResult}. They enable comparative case analysis
 * by preserving alternative execution trajectories.</p>
 *
 * @param forkId unique identifier for this fork (UUID string)
 * @param decisionPath ordered list of task IDs executed in this fork's path
 * @param outcomeXml serialized case state (XML) at fork termination or current point
 * @param terminatedNormally true if fork completed normally; false if stopped early
 * @param durationMs wall-clock milliseconds for this fork's execution
 * @param completedAt instant when fork execution completed
 *
 * @since YAWL 6.0
 */
public record CaseFork(
    String forkId,
    List<String> decisionPath,
    String outcomeXml,
    boolean terminatedNormally,
    long durationMs,
    Instant completedAt
) {
    /**
     * Compact object header representation for memory efficiency.
     * Auto-generated by Java 21+ with -XX:+UseCompactObjectHeaders.
     */
}
