// GENERATED BY ggen — WCP-NB-08
// Source: dm-bridge-ggen/ontology/dm-jtbd.ttl
// DO NOT EDIT — edit ontology/dm-jtbd.ttl and regenerate
package org.yawlfoundation.yawl.datamodelling.bridge;

/**
 * Machine-readable registry of Jobs To Be Done (JTBD) for the DataModelling
 * native bridge. Generated from ontology/dm-jtbd.ttl.
 *
 * <p>Each constant encodes one L4 JTBD job:
 * <ul>
 *   <li>{@code actorRole()} — the business role that performs the job</li>
 *   <li>{@code trigger()} — the business event that initiates the job</li>
 * </ul>
 *
 * <p>Used by {@code @JTBDTest} to annotate L4 test methods and by
 * {@code DataModellingJTBDTest} to drive workflow job assertions.
 *
 * @see DataModellingL3
 */
public enum DataModellingJTBDJob {

    /**
     * A data engineer publishes API documentation by converting an ODCS schema to OpenAPI format.
     * Role: DataEngineer | Trigger: ApiDocumentationUpdate
     */
    SCHEMA_DOCUMENTATION_PUBLISHING("DataEngineer", "ApiDocumentationUpdate"),

    /**
     * A business analyst extracts decision logic from a BPMN process and converts it to DMN for governance review.
     * Role: BusinessAnalyst | Trigger: DecisionGovernanceReview
     */
    PROCESS_DECISION_EXTRACTION("BusinessAnalyst", "DecisionGovernanceReview"),

    /**
     * A data steward harmonizes vocabularies into ODCS format during an open-data compliance audit.
     * Role: DataSteward | Trigger: OpenDataComplianceAudit
     */
    VOCABULARY_HARMONIZATION("DataSteward", "OpenDataComplianceAudit"),

    /**
     * A data governance officer discovers schema constraints after a data quality incident.
     * Role: DataGovernanceOfficer | Trigger: DataQualityIncident
     */
    SCHEMA_CONSTRAINT_DISCOVERY("DataGovernanceOfficer", "DataQualityIncident"),

    /**
     * A knowledge engineer identifies gaps in domain knowledge during a domain model refactoring.
     * Role: KnowledgeEngineer | Trigger: DomainModelRefactoring
     */
    KNOWLEDGE_GAP_ANALYSIS("KnowledgeEngineer", "DomainModelRefactoring");

    private final String actorRole;
    private final String trigger;

    DataModellingJTBDJob(String actorRole, String trigger) {
        this.actorRole = actorRole;
        this.trigger   = trigger;
    }

    /** The business role that performs this job (e.g. {@code "DataEngineer"}). */
    public String actorRole() { return actorRole; }

    /** The business trigger that initiates this job (e.g. {@code "ApiDocumentationUpdate"}). */
    public String trigger() { return trigger; }
}
