/**
 * Declares that a class or method implements a specific {@link DataModellingCapability} at
 * a defined bridge layer.
 *
 * <p>The {@link DataModellingCapabilityRegistry} scans all registered classes for this
 * annotation at startup. For each declared {@link DataModellingCapability} (except
 * {@link DataModellingCapability#TOTAL}), there must be at least one annotated element with
 * {@code layer = "L2"} and at least one with {@code layer = "L3"}. Missing either causes
 * the registry to throw {@link DataModellingCapabilityRegistryException}.</p>
 *
 * <p>Usage on a class (coarse-grained, for L2 where one class handles many capabilities):
 * <pre>
 *   &#64;DataModellingMapsToCapability(value = DataModellingCapability.SOME_CAP, layer = "L2")
 *   &#64;DataModellingMapsToCapability(value = DataModellingCapability.OTHER_CAP, layer = "L2")
 *   public class DataModellingL2 { ... }
 * </pre>
 *
 * <p>Usage on a method (fine-grained, preferred for L3 public API):
 * <pre>
 *   &#64;DataModellingMapsToCapability(value = DataModellingCapability.SOME_CAP, layer = "L3")
 *   public String someCapability(String request) { ... }
 * </pre>
 *
 * @generated by ggen from ontology
 * @pattern WCP-NB-05
 * @see DataModellingCapabilityRegistry
 * @see DataModellingCapability
 */
package org.yawlfoundation.yawl.datamodelling.bridge;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Documented
@Repeatable(DataModellingMapsToCapability.Repeatable.class)
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface DataModellingMapsToCapability {

    /** The capability this element implements. */
    DataModellingCapability value();

    /**
     * The bridge layer this implementation belongs to.
     *
     * <p>Must be exactly {@code "L2"} (FFI transport, Panama FFM types allowed internally)
     * or {@code "L3"} (domain API, no Panama FFM types in public signatures).</p>
     */
    String layer();

    /** Container for repeated {@link DataModellingMapsToCapability} annotations. */
    @Documented
    @Target({ElementType.TYPE, ElementType.METHOD})
    @Retention(RetentionPolicy.RUNTIME)
    @interface Repeatable {
        DataModellingMapsToCapability[] value();
    }
}
