/**
 * DataModellingCapabilityRegistry — startup gate for the DataModelling native bridge.
 *
 * <p>Scans registered L2/L3 class lists for {@code @MapsToCapability} annotations and
 * test classes for {@code @CapabilityTest} annotations, then verifies that every
 * {@link DataModellingCapability} (except {@code TOTAL}) has all three coverages.</p>
 *
 * <p>If any capability is missing, {@link #validate()} throws
 * {@link DataModellingCapabilityRegistryException}, aborting startup with a full report.</p>
 *
 * <p>Usage:
 * <pre>
 *   DataModellingCapabilityRegistry registry = new DataModellingCapabilityRegistry(
 *       List.of(DataModellingL2.class),
 *       List.of(DataModellingL3.class),
 *       List.of(DataModellingBridgeTest.class));
 *   registry.validate();
 * </pre>
 *
 * @generated by ggen from ontology
 * @pattern WCP-NB-02
 */
package org.yawlfoundation.yawl.datamodelling.bridge;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;
import java.util.Set;

public final class DataModellingCapabilityRegistry {

    private final List<Class<?>> layer2Classes;
    private final List<Class<?>> layer3Classes;
    private final List<Class<?>> testClasses;

    /**
     * Creates a registry with the given class lists.
     *
     * @param layer2Classes FFI transport layer classes (may use Panama MemorySegment internally)
     * @param layer3Classes domain API layer classes (pure Java public signatures)
     * @param testClasses   classes containing {@code @DataModellingCapabilityTest}-annotated methods
     * @throws IllegalArgumentException if any argument is null
     */
    public DataModellingCapabilityRegistry(
            List<Class<?>> layer2Classes,
            List<Class<?>> layer3Classes,
            List<Class<?>> testClasses) {
        if (layer2Classes == null) {
            throw new IllegalArgumentException("layer2Classes must not be null");
        }
        if (layer3Classes == null) {
            throw new IllegalArgumentException("layer3Classes must not be null");
        }
        if (testClasses == null) {
            throw new IllegalArgumentException("testClasses must not be null");
        }
        this.layer2Classes = List.copyOf(layer2Classes);
        this.layer3Classes = List.copyOf(layer3Classes);
        this.testClasses   = List.copyOf(testClasses);
    }

    /**
     * Validates that all capabilities are implemented and tested.
     *
     * @throws DataModellingCapabilityRegistryException if any capability is missing L2, L3, or test coverage
     */
    public void validate() {
        Set<DataModellingCapability> coveredL2   = EnumSet.noneOf(DataModellingCapability.class);
        Set<DataModellingCapability> coveredL3   = EnumSet.noneOf(DataModellingCapability.class);
        Set<DataModellingCapability> coveredTest = EnumSet.noneOf(DataModellingCapability.class);

        for (Class<?> cls : layer2Classes) {
            scanMapsToCapability(cls, coveredL2);
        }
        for (Class<?> cls : layer3Classes) {
            scanMapsToCapability(cls, coveredL3);
        }
        for (Class<?> cls : testClasses) {
            scanCapabilityTests(cls, coveredTest);
        }

        List<String> missing = new ArrayList<>();
        for (DataModellingCapability cap : DataModellingCapability.values()) {
            if (cap == DataModellingCapability.TOTAL) {
                continue;
            }
            if (!coveredL2.contains(cap)) {
                missing.add("L2 missing: " + cap.name());
            }
            if (!coveredL3.contains(cap)) {
                missing.add("L3 missing: " + cap.name());
            }
            if (!coveredTest.contains(cap)) {
                missing.add("Test missing: " + cap.name());
            }
        }

        if (!missing.isEmpty()) {
            throw new DataModellingCapabilityRegistryException(missing);
        }
    }

    private void scanMapsToCapability(Class<?> cls, Set<DataModellingCapability> target) {
        DataModellingMapsToCapability single = cls.getAnnotation(DataModellingMapsToCapability.class);
        if (single != null) {
            target.add(single.value());
        }
        DataModellingMapsToCapability.Repeatable container =
            cls.getAnnotation(DataModellingMapsToCapability.Repeatable.class);
        if (container != null) {
            for (DataModellingMapsToCapability ann : container.value()) {
                target.add(ann.value());
            }
        }
        for (Method method : cls.getDeclaredMethods()) {
            DataModellingMapsToCapability ms = method.getAnnotation(DataModellingMapsToCapability.class);
            if (ms != null) {
                target.add(ms.value());
            }
            DataModellingMapsToCapability.Repeatable mc =
                method.getAnnotation(DataModellingMapsToCapability.Repeatable.class);
            if (mc != null) {
                for (DataModellingMapsToCapability ann : mc.value()) {
                    target.add(ann.value());
                }
            }
        }
    }

    private void scanCapabilityTests(Class<?> cls, Set<DataModellingCapability> target) {
        for (Method method : cls.getDeclaredMethods()) {
            DataModellingCapabilityTest single =
                method.getAnnotation(DataModellingCapabilityTest.class);
            if (single != null) {
                target.add(single.value());
            }
            DataModellingCapabilityTest.Repeatable container =
                method.getAnnotation(DataModellingCapabilityTest.Repeatable.class);
            if (container != null) {
                for (DataModellingCapabilityTest ann : container.value()) {
                    target.add(ann.value());
                }
            }
        }
    }
}
