/**
 * DataModellingL2 — Layer 2 FFI transport for {@code libdatamodelling.so}.
 *
 * <p>Thin Panama FFM wrapper over data-modelling-sdk v2.3.0. All 55 native functions
 * follow a uniform {@code char* → char*} (JSON in, JSON out) C ABI, implemented via
 * a single {@link #callDm(MethodHandle, String)} helper that handles encoding,
 * invocation, result extraction, and native memory release.</p>
 *
 * <p>Architecture:
 * <pre>
 *   L3 domain API (DataModellingL3)
 *        ↓ delegates
 *   L2 FFI transport (DataModellingL2)   ← this class
 *        ↓ downcall
 *   libdatamodelling.so (native Rust/C)
 * </pre>
 *
 * <p>Graceful degradation: all methods throw {@link UnsupportedOperationException}
 * when the native library is not loaded. Set system property
 * {@code -Dyawl.datamodelling.lib=/path/to/libdatamodelling.so} to enable.</p>
 *
 * @generated by ggen from ontology
 * @pattern WCP-NB-03 (data-modelling custom variant)
 * @see DataModellingL3
 */
package org.yawlfoundation.yawl.datamodelling.bridge;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.Optional;


@DataModellingMapsToCapability(value = DataModellingCapability.CONVERT_BPMN_TO_DMN, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.CONVERT_ODCS_TO_ODPS, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.CONVERT_ODCS_TO_OPENAPI, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.CONVERT_SCHEMA_TO_TEMPLATE, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.CONVERT_VOCABULARY_TO_ODCS, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_BPMN_PROCESS, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_CADS_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_CONFIGURATION, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_CONSTRAINT_SET, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_DECISION_RECORD, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_DMN_DECISION, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_DOMAIN_ORG, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_KNOWLEDGE_BASE, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_ODCS_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_ODPS_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_OPENAPI_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_SKETCH, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_TEMPLATE, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.EXPORT_VOCABULARY, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_BPMN_PROCESS, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_CADS_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_CONFIGURATION, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_CONSTRAINT_SET, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_DECISION_RECORD, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_DMN_DECISION, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_DOMAIN_ORG, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_KNOWLEDGE_BASE, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_ODCS_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_ODPS_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_OPENAPI_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_SKETCH, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_TEMPLATE, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.IMPORT_VOCABULARY, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.INFER_CONSTRAINTS, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.INFER_DECISION_RULES, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.INFER_DOMAIN_ORG, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.INFER_KNOWLEDGE_GAPS, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.INFER_SCHEMA_RECOMMENDATIONS, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.INFER_VOCABULARY, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.MAP_BPMN_TO_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.MAP_DOMAIN_TO_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.MAP_SCHEMAS, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.MAP_VOCABULARIES, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_BPMN_PROCESS, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_CADS_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_CONFIGURATION, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_CONSTRAINT_SET, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_DECISION_RECORD, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_DMN_DECISION, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_DOMAIN_ORG, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_KNOWLEDGE_BASE, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_ODCS_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_ODPS_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_OPENAPI_SCHEMA, layer = "L2")
@DataModellingMapsToCapability(value = DataModellingCapability.VALIDATE_SKETCH, layer = "L2")
public final class DataModellingL2 implements AutoCloseable {

    /** System property for the path to {@code libdatamodelling.so}. */
    public static final String LIB_PATH_PROP = "yawl.datamodelling.lib";

    private static final FunctionDescriptor DM_DESCRIPTOR =
        FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS);

    private static final Linker LINKER = Linker.nativeLinker();

    private final Arena arena;
    private final Optional<SymbolLookup> library;

    private final MethodHandle mh$dm_convert_bpmn_to_dmn;
    private final MethodHandle mh$dm_convert_odcs_to_odps;
    private final MethodHandle mh$dm_convert_odcs_to_openapi;
    private final MethodHandle mh$dm_convert_schema_to_template;
    private final MethodHandle mh$dm_convert_vocabulary_to_odcs;
    private final MethodHandle mh$dm_export_bpmn_process;
    private final MethodHandle mh$dm_export_cads_schema;
    private final MethodHandle mh$dm_export_configuration;
    private final MethodHandle mh$dm_export_constraint_set;
    private final MethodHandle mh$dm_export_decision_record;
    private final MethodHandle mh$dm_export_dmn_decision;
    private final MethodHandle mh$dm_export_domain_org;
    private final MethodHandle mh$dm_export_knowledge_base;
    private final MethodHandle mh$dm_export_odcs_schema;
    private final MethodHandle mh$dm_export_odps_schema;
    private final MethodHandle mh$dm_export_openapi_schema;
    private final MethodHandle mh$dm_export_sketch;
    private final MethodHandle mh$dm_export_template;
    private final MethodHandle mh$dm_export_vocabulary;
    private final MethodHandle mh$dm_import_bpmn_process;
    private final MethodHandle mh$dm_import_cads_schema;
    private final MethodHandle mh$dm_import_configuration;
    private final MethodHandle mh$dm_import_constraint_set;
    private final MethodHandle mh$dm_import_decision_record;
    private final MethodHandle mh$dm_import_dmn_decision;
    private final MethodHandle mh$dm_import_domain_org;
    private final MethodHandle mh$dm_import_knowledge_base;
    private final MethodHandle mh$dm_import_odcs_schema;
    private final MethodHandle mh$dm_import_odps_schema;
    private final MethodHandle mh$dm_import_openapi_schema;
    private final MethodHandle mh$dm_import_sketch;
    private final MethodHandle mh$dm_import_template;
    private final MethodHandle mh$dm_import_vocabulary;
    private final MethodHandle mh$dm_infer_constraints;
    private final MethodHandle mh$dm_infer_decision_rules;
    private final MethodHandle mh$dm_infer_domain_org;
    private final MethodHandle mh$dm_infer_knowledge_gaps;
    private final MethodHandle mh$dm_infer_schema_recommendations;
    private final MethodHandle mh$dm_infer_vocabulary;
    private final MethodHandle mh$dm_map_bpmn_to_schema;
    private final MethodHandle mh$dm_map_domain_to_schema;
    private final MethodHandle mh$dm_map_schemas;
    private final MethodHandle mh$dm_map_vocabularies;
    private final MethodHandle mh$dm_validate_bpmn_process;
    private final MethodHandle mh$dm_validate_cads_schema;
    private final MethodHandle mh$dm_validate_configuration;
    private final MethodHandle mh$dm_validate_constraint_set;
    private final MethodHandle mh$dm_validate_decision_record;
    private final MethodHandle mh$dm_validate_dmn_decision;
    private final MethodHandle mh$dm_validate_domain_org;
    private final MethodHandle mh$dm_validate_knowledge_base;
    private final MethodHandle mh$dm_validate_odcs_schema;
    private final MethodHandle mh$dm_validate_odps_schema;
    private final MethodHandle mh$dm_validate_openapi_schema;
    private final MethodHandle mh$dm_validate_sketch;
    private final MethodHandle mh$dm_string_free;

    /**
     * Creates an L2 transport with the native library loaded from the given path.
     *
     * <p>If {@code libraryPath} is null or blank, all operations throw
     * {@link UnsupportedOperationException} — graceful degradation at startup.</p>
     *
     * @param libraryPath absolute path to {@code libdatamodelling.so}, or null
     */
    public DataModellingL2(String libraryPath) {
        this.arena = Arena.ofShared();
        Optional<SymbolLookup> lib = Optional.empty();
        if (libraryPath != null && !libraryPath.isBlank()) {
            lib = Optional.of(SymbolLookup.libraryLookup(Path.of(libraryPath), arena));
        }
        this.library = lib;

        this.mh$dm_convert_bpmn_to_dmn = library.isPresent()
            ? resolveHandle("dm_convert_bpmn_to_dmn")
            : null;
        this.mh$dm_convert_odcs_to_odps = library.isPresent()
            ? resolveHandle("dm_convert_odcs_to_odps")
            : null;
        this.mh$dm_convert_odcs_to_openapi = library.isPresent()
            ? resolveHandle("dm_convert_odcs_to_openapi")
            : null;
        this.mh$dm_convert_schema_to_template = library.isPresent()
            ? resolveHandle("dm_convert_schema_to_template")
            : null;
        this.mh$dm_convert_vocabulary_to_odcs = library.isPresent()
            ? resolveHandle("dm_convert_vocabulary_to_odcs")
            : null;
        this.mh$dm_export_bpmn_process = library.isPresent()
            ? resolveHandle("dm_export_bpmn_process")
            : null;
        this.mh$dm_export_cads_schema = library.isPresent()
            ? resolveHandle("dm_export_cads_schema")
            : null;
        this.mh$dm_export_configuration = library.isPresent()
            ? resolveHandle("dm_export_configuration")
            : null;
        this.mh$dm_export_constraint_set = library.isPresent()
            ? resolveHandle("dm_export_constraint_set")
            : null;
        this.mh$dm_export_decision_record = library.isPresent()
            ? resolveHandle("dm_export_decision_record")
            : null;
        this.mh$dm_export_dmn_decision = library.isPresent()
            ? resolveHandle("dm_export_dmn_decision")
            : null;
        this.mh$dm_export_domain_org = library.isPresent()
            ? resolveHandle("dm_export_domain_org")
            : null;
        this.mh$dm_export_knowledge_base = library.isPresent()
            ? resolveHandle("dm_export_knowledge_base")
            : null;
        this.mh$dm_export_odcs_schema = library.isPresent()
            ? resolveHandle("dm_export_odcs_schema")
            : null;
        this.mh$dm_export_odps_schema = library.isPresent()
            ? resolveHandle("dm_export_odps_schema")
            : null;
        this.mh$dm_export_openapi_schema = library.isPresent()
            ? resolveHandle("dm_export_openapi_schema")
            : null;
        this.mh$dm_export_sketch = library.isPresent()
            ? resolveHandle("dm_export_sketch")
            : null;
        this.mh$dm_export_template = library.isPresent()
            ? resolveHandle("dm_export_template")
            : null;
        this.mh$dm_export_vocabulary = library.isPresent()
            ? resolveHandle("dm_export_vocabulary")
            : null;
        this.mh$dm_import_bpmn_process = library.isPresent()
            ? resolveHandle("dm_import_bpmn_process")
            : null;
        this.mh$dm_import_cads_schema = library.isPresent()
            ? resolveHandle("dm_import_cads_schema")
            : null;
        this.mh$dm_import_configuration = library.isPresent()
            ? resolveHandle("dm_import_configuration")
            : null;
        this.mh$dm_import_constraint_set = library.isPresent()
            ? resolveHandle("dm_import_constraint_set")
            : null;
        this.mh$dm_import_decision_record = library.isPresent()
            ? resolveHandle("dm_import_decision_record")
            : null;
        this.mh$dm_import_dmn_decision = library.isPresent()
            ? resolveHandle("dm_import_dmn_decision")
            : null;
        this.mh$dm_import_domain_org = library.isPresent()
            ? resolveHandle("dm_import_domain_org")
            : null;
        this.mh$dm_import_knowledge_base = library.isPresent()
            ? resolveHandle("dm_import_knowledge_base")
            : null;
        this.mh$dm_import_odcs_schema = library.isPresent()
            ? resolveHandle("dm_import_odcs_schema")
            : null;
        this.mh$dm_import_odps_schema = library.isPresent()
            ? resolveHandle("dm_import_odps_schema")
            : null;
        this.mh$dm_import_openapi_schema = library.isPresent()
            ? resolveHandle("dm_import_openapi_schema")
            : null;
        this.mh$dm_import_sketch = library.isPresent()
            ? resolveHandle("dm_import_sketch")
            : null;
        this.mh$dm_import_template = library.isPresent()
            ? resolveHandle("dm_import_template")
            : null;
        this.mh$dm_import_vocabulary = library.isPresent()
            ? resolveHandle("dm_import_vocabulary")
            : null;
        this.mh$dm_infer_constraints = library.isPresent()
            ? resolveHandle("dm_infer_constraints")
            : null;
        this.mh$dm_infer_decision_rules = library.isPresent()
            ? resolveHandle("dm_infer_decision_rules")
            : null;
        this.mh$dm_infer_domain_org = library.isPresent()
            ? resolveHandle("dm_infer_domain_org")
            : null;
        this.mh$dm_infer_knowledge_gaps = library.isPresent()
            ? resolveHandle("dm_infer_knowledge_gaps")
            : null;
        this.mh$dm_infer_schema_recommendations = library.isPresent()
            ? resolveHandle("dm_infer_schema_recommendations")
            : null;
        this.mh$dm_infer_vocabulary = library.isPresent()
            ? resolveHandle("dm_infer_vocabulary")
            : null;
        this.mh$dm_map_bpmn_to_schema = library.isPresent()
            ? resolveHandle("dm_map_bpmn_to_schema")
            : null;
        this.mh$dm_map_domain_to_schema = library.isPresent()
            ? resolveHandle("dm_map_domain_to_schema")
            : null;
        this.mh$dm_map_schemas = library.isPresent()
            ? resolveHandle("dm_map_schemas")
            : null;
        this.mh$dm_map_vocabularies = library.isPresent()
            ? resolveHandle("dm_map_vocabularies")
            : null;
        this.mh$dm_validate_bpmn_process = library.isPresent()
            ? resolveHandle("dm_validate_bpmn_process")
            : null;
        this.mh$dm_validate_cads_schema = library.isPresent()
            ? resolveHandle("dm_validate_cads_schema")
            : null;
        this.mh$dm_validate_configuration = library.isPresent()
            ? resolveHandle("dm_validate_configuration")
            : null;
        this.mh$dm_validate_constraint_set = library.isPresent()
            ? resolveHandle("dm_validate_constraint_set")
            : null;
        this.mh$dm_validate_decision_record = library.isPresent()
            ? resolveHandle("dm_validate_decision_record")
            : null;
        this.mh$dm_validate_dmn_decision = library.isPresent()
            ? resolveHandle("dm_validate_dmn_decision")
            : null;
        this.mh$dm_validate_domain_org = library.isPresent()
            ? resolveHandle("dm_validate_domain_org")
            : null;
        this.mh$dm_validate_knowledge_base = library.isPresent()
            ? resolveHandle("dm_validate_knowledge_base")
            : null;
        this.mh$dm_validate_odcs_schema = library.isPresent()
            ? resolveHandle("dm_validate_odcs_schema")
            : null;
        this.mh$dm_validate_odps_schema = library.isPresent()
            ? resolveHandle("dm_validate_odps_schema")
            : null;
        this.mh$dm_validate_openapi_schema = library.isPresent()
            ? resolveHandle("dm_validate_openapi_schema")
            : null;
        this.mh$dm_validate_sketch = library.isPresent()
            ? resolveHandle("dm_validate_sketch")
            : null;
        this.mh$dm_string_free = library.isPresent()
            ? resolveVoidHandle("dm_string_free")
            : null;
    }

    private MethodHandle resolveHandle(String symbol) {
        return library.get().find(symbol)
            .map(seg -> LINKER.downcallHandle(seg, DM_DESCRIPTOR))
            .orElseThrow(() -> new UnsatisfiedLinkError(
                symbol + " not found in libdatamodelling.so"));
    }

    private MethodHandle resolveVoidHandle(String symbol) {
        return library.get().find(symbol)
            .map(seg -> LINKER.downcallHandle(seg,
                FunctionDescriptor.ofVoid(ValueLayout.ADDRESS)))
            .orElseThrow(() -> new UnsatisfiedLinkError(
                symbol + " not found in libdatamodelling.so"));
    }

    private void requireLibrary() {
        if (library.isEmpty()) {
            throw new UnsupportedOperationException(
                "libdatamodelling.so not loaded. Set -D" + LIB_PATH_PROP
                    + "=/path/to/libdatamodelling.so");
        }
    }

    /**
     * Uniform helper: encodes {@code json} to UTF-8, calls the native function,
     * extracts the result string, frees native memory, and returns the Java String.
     *
     * <p>All 55 data-modelling-sdk functions share this helper because they all follow
     * the same {@code char* → char*} C ABI.</p>
     *
     * @param mh   pre-resolved downcall handle for the target native function
     * @param json UTF-8 JSON request
     * @return UTF-8 JSON response from the native library
     * @throws AssertionError if the native call fails or returns NULL
     */
    private String callDm(MethodHandle mh, String json) {
        try (Arena call = Arena.ofConfined()) {
            MemorySegment jsonSeg = call.allocateFrom(json, StandardCharsets.UTF_8);
            MemorySegment result = (MemorySegment) mh.invokeExact(jsonSeg);
            if (MemorySegment.NULL.equals(result)) {
                throw new AssertionError(
                    "libdatamodelling.so returned NULL — check input JSON");
            }
            String out = result.reinterpret(Long.MAX_VALUE)
                               .getString(0, StandardCharsets.UTF_8);
            this.mh$dm_string_free.invokeExact(result);
            return out;
        } catch (Throwable t) {
            throw new AssertionError("DataModelling native call failed", t);
        }
    }

    /**
     * Calls {@code dm_convert_bpmn_to_dmn} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String convertBpmnToDmn(String json) {
        requireLibrary();
        return callDm(this.mh$dm_convert_bpmn_to_dmn, json);
    }

    /**
     * Calls {@code dm_convert_odcs_to_odps} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String convertOdcsToOdps(String json) {
        requireLibrary();
        return callDm(this.mh$dm_convert_odcs_to_odps, json);
    }

    /**
     * Calls {@code dm_convert_odcs_to_openapi} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String convertOdcsToOpenapi(String json) {
        requireLibrary();
        return callDm(this.mh$dm_convert_odcs_to_openapi, json);
    }

    /**
     * Calls {@code dm_convert_schema_to_template} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String convertSchemaToTemplate(String json) {
        requireLibrary();
        return callDm(this.mh$dm_convert_schema_to_template, json);
    }

    /**
     * Calls {@code dm_convert_vocabulary_to_odcs} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String convertVocabularyToOdcs(String json) {
        requireLibrary();
        return callDm(this.mh$dm_convert_vocabulary_to_odcs, json);
    }

    /**
     * Calls {@code dm_export_bpmn_process} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportBpmnProcess(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_bpmn_process, json);
    }

    /**
     * Calls {@code dm_export_cads_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportCadsSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_cads_schema, json);
    }

    /**
     * Calls {@code dm_export_configuration} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportConfiguration(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_configuration, json);
    }

    /**
     * Calls {@code dm_export_constraint_set} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportConstraintSet(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_constraint_set, json);
    }

    /**
     * Calls {@code dm_export_decision_record} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportDecisionRecord(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_decision_record, json);
    }

    /**
     * Calls {@code dm_export_dmn_decision} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportDmnDecision(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_dmn_decision, json);
    }

    /**
     * Calls {@code dm_export_domain_org} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportDomainOrg(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_domain_org, json);
    }

    /**
     * Calls {@code dm_export_knowledge_base} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportKnowledgeBase(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_knowledge_base, json);
    }

    /**
     * Calls {@code dm_export_odcs_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportOdcsSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_odcs_schema, json);
    }

    /**
     * Calls {@code dm_export_odps_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportOdpsSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_odps_schema, json);
    }

    /**
     * Calls {@code dm_export_openapi_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportOpenapiSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_openapi_schema, json);
    }

    /**
     * Calls {@code dm_export_sketch} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportSketch(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_sketch, json);
    }

    /**
     * Calls {@code dm_export_template} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportTemplate(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_template, json);
    }

    /**
     * Calls {@code dm_export_vocabulary} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String exportVocabulary(String json) {
        requireLibrary();
        return callDm(this.mh$dm_export_vocabulary, json);
    }

    /**
     * Calls {@code dm_import_bpmn_process} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importBpmnProcess(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_bpmn_process, json);
    }

    /**
     * Calls {@code dm_import_cads_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importCadsSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_cads_schema, json);
    }

    /**
     * Calls {@code dm_import_configuration} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importConfiguration(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_configuration, json);
    }

    /**
     * Calls {@code dm_import_constraint_set} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importConstraintSet(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_constraint_set, json);
    }

    /**
     * Calls {@code dm_import_decision_record} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importDecisionRecord(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_decision_record, json);
    }

    /**
     * Calls {@code dm_import_dmn_decision} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importDmnDecision(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_dmn_decision, json);
    }

    /**
     * Calls {@code dm_import_domain_org} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importDomainOrg(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_domain_org, json);
    }

    /**
     * Calls {@code dm_import_knowledge_base} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importKnowledgeBase(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_knowledge_base, json);
    }

    /**
     * Calls {@code dm_import_odcs_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importOdcsSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_odcs_schema, json);
    }

    /**
     * Calls {@code dm_import_odps_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importOdpsSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_odps_schema, json);
    }

    /**
     * Calls {@code dm_import_openapi_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importOpenapiSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_openapi_schema, json);
    }

    /**
     * Calls {@code dm_import_sketch} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importSketch(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_sketch, json);
    }

    /**
     * Calls {@code dm_import_template} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importTemplate(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_template, json);
    }

    /**
     * Calls {@code dm_import_vocabulary} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String importVocabulary(String json) {
        requireLibrary();
        return callDm(this.mh$dm_import_vocabulary, json);
    }

    /**
     * Calls {@code dm_infer_constraints} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String inferConstraints(String json) {
        requireLibrary();
        return callDm(this.mh$dm_infer_constraints, json);
    }

    /**
     * Calls {@code dm_infer_decision_rules} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String inferDecisionRules(String json) {
        requireLibrary();
        return callDm(this.mh$dm_infer_decision_rules, json);
    }

    /**
     * Calls {@code dm_infer_domain_org} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String inferDomainOrg(String json) {
        requireLibrary();
        return callDm(this.mh$dm_infer_domain_org, json);
    }

    /**
     * Calls {@code dm_infer_knowledge_gaps} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String inferKnowledgeGaps(String json) {
        requireLibrary();
        return callDm(this.mh$dm_infer_knowledge_gaps, json);
    }

    /**
     * Calls {@code dm_infer_schema_recommendations} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String inferSchemaRecommendations(String json) {
        requireLibrary();
        return callDm(this.mh$dm_infer_schema_recommendations, json);
    }

    /**
     * Calls {@code dm_infer_vocabulary} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String inferVocabulary(String json) {
        requireLibrary();
        return callDm(this.mh$dm_infer_vocabulary, json);
    }

    /**
     * Calls {@code dm_map_bpmn_to_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String mapBpmnToSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_map_bpmn_to_schema, json);
    }

    /**
     * Calls {@code dm_map_domain_to_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String mapDomainToSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_map_domain_to_schema, json);
    }

    /**
     * Calls {@code dm_map_schemas} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String mapSchemas(String json) {
        requireLibrary();
        return callDm(this.mh$dm_map_schemas, json);
    }

    /**
     * Calls {@code dm_map_vocabularies} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String mapVocabularies(String json) {
        requireLibrary();
        return callDm(this.mh$dm_map_vocabularies, json);
    }

    /**
     * Calls {@code dm_validate_bpmn_process} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String validateBpmnProcess(String json) {
        requireLibrary();
        return callDm(this.mh$dm_validate_bpmn_process, json);
    }

    /**
     * Calls {@code dm_validate_cads_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String validateCadsSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_validate_cads_schema, json);
    }

    /**
     * Calls {@code dm_validate_configuration} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String validateConfiguration(String json) {
        requireLibrary();
        return callDm(this.mh$dm_validate_configuration, json);
    }

    /**
     * Calls {@code dm_validate_constraint_set} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String validateConstraintSet(String json) {
        requireLibrary();
        return callDm(this.mh$dm_validate_constraint_set, json);
    }

    /**
     * Calls {@code dm_validate_decision_record} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String validateDecisionRecord(String json) {
        requireLibrary();
        return callDm(this.mh$dm_validate_decision_record, json);
    }

    /**
     * Calls {@code dm_validate_dmn_decision} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String validateDmnDecision(String json) {
        requireLibrary();
        return callDm(this.mh$dm_validate_dmn_decision, json);
    }

    /**
     * Calls {@code dm_validate_domain_org} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String validateDomainOrg(String json) {
        requireLibrary();
        return callDm(this.mh$dm_validate_domain_org, json);
    }

    /**
     * Calls {@code dm_validate_knowledge_base} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String validateKnowledgeBase(String json) {
        requireLibrary();
        return callDm(this.mh$dm_validate_knowledge_base, json);
    }

    /**
     * Calls {@code dm_validate_odcs_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String validateOdcsSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_validate_odcs_schema, json);
    }

    /**
     * Calls {@code dm_validate_odps_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String validateOdpsSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_validate_odps_schema, json);
    }

    /**
     * Calls {@code dm_validate_openapi_schema} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String validateOpenapiSchema(String json) {
        requireLibrary();
        return callDm(this.mh$dm_validate_openapi_schema, json);
    }

    /**
     * Calls {@code dm_validate_sketch} via the uniform char*→char* transport.
     *
     * @param json UTF-8 JSON request (schema-specific, per data-modelling-sdk docs)
     * @return UTF-8 JSON response
     * @throws UnsupportedOperationException if libdatamodelling.so is not loaded
     * @throws AssertionError if the native invocation fails unexpectedly
     */
    public String validateSketch(String json) {
        requireLibrary();
        return callDm(this.mh$dm_validate_sketch, json);
    }

    /** Returns true if the native library was successfully loaded. */
    public boolean isLibraryLoaded() {
        return library.isPresent();
    }

    /**
     * Releases the shared Arena holding all native SymbolLookup segments.
     * After closing, method calls will fail with {@link IllegalStateException}.
     */
    @Override
    public void close() {
        arena.close();
    }
}