/**
 * DataModellingIntegrationTest — 55 live integration tests for libdatamodelling.so.
 *
 * <p>Each test encodes one domain operation performed by the native library.
 * Tests exercise the L3 domain API and assert plausibility of JSON responses.
 *
 * <p><b>These tests skip gracefully when the native library is absent.</b>
 * The {@code assumeTrue(l3.isAvailable())} guard ensures CI stays green
 * on machines without libdatamodelling.so. Skipped ≠ Failed.
 *
 * <p>Integration tests block <em>release</em>, not merge.
 * They must pass in the native-library-present release environment.
 *
 * <p>Coverage: All 55 domain operations defined in the ontology.
 *
 * @generated by ggen from ontology (WCP-NB-10)
 * @pattern WCP-NB-10 (native bridge integration testing)
 * @see DataModellingL3
 * @see JTBDTestSupport
 */
package org.yawlfoundation.yawl.datamodelling.bridge;

import java.io.IOException;
import java.util.List;

import static org.junit.jupiter.api.Assumptions.assumeTrue;
import static org.yawlfoundation.yawl.datamodelling.bridge.JTBDTestSupport.assertPlausible;
import static org.yawlfoundation.yawl.datamodelling.bridge.JTBDTestSupport.loadFixture;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class DataModellingIntegrationTest {

    private DataModellingL3 l3;

    @BeforeEach
    void setUp() throws Exception {
        var l2 = new DataModellingL2(System.getProperty(DataModellingL2.LIB_PATH_PROP));
        this.l3 = new DataModellingL3(l2);
    }

    @AfterEach
    void tearDown() throws Exception {
        if (l3 != null) {
            l3.close();
        }
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.CONVERT_BPMN_TO_DMN)
    void convertBpmnToDmn_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("bpmn-process");
        String result = l3.convertBpmnToDmn(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.CONVERT_ODCS_TO_OPENAPI)
    void convertOdcsToOpenapi_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("odcs-schema");
        String result = l3.convertOdcsToOpenapi(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.CONVERT_ODCS_TO_ODPS)
    void convertOdcsToOdps_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("odcs-schema");
        String result = l3.convertOdcsToOdps(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.CONVERT_SCHEMA_TO_TEMPLATE)
    void convertSchemaToTemplate_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.convertSchemaToTemplate(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.CONVERT_VOCABULARY_TO_ODCS)
    void convertVocabularyToOdcs_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("odcs-schema");
        String result = l3.convertVocabularyToOdcs(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_BPMN_PROCESS)
    void exportBpmnProcess_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("bpmn-model");
        String result = l3.exportBpmnProcess(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_CADS_SCHEMA)
    void exportCadsSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("cads-asset");
        String result = l3.exportCadsSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_CONFIGURATION)
    void exportConfiguration_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.exportConfiguration(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_CONSTRAINT_SET)
    void exportConstraintSet_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.exportConstraintSet(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_DMN_DECISION)
    void exportDmnDecision_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("dmn-model");
        String result = l3.exportDmnDecision(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_DOMAIN_ORG)
    void exportDomainOrg_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("domain-export");
        String result = l3.exportDomainOrg(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_KNOWLEDGE_BASE)
    void exportKnowledgeBase_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("knowledge-article");
        String result = l3.exportKnowledgeBase(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_ODCS_SCHEMA)
    void exportOdcsSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.exportOdcsSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_ODPS_SCHEMA)
    void exportOdpsSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("odps-product");
        String result = l3.exportOdpsSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_OPENAPI_SCHEMA)
    void exportOpenapiSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.exportOpenapiSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_SKETCH)
    void exportSketch_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("sketch-export");
        String result = l3.exportSketch(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_TEMPLATE)
    void exportTemplate_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.exportTemplate(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_VOCABULARY)
    void exportVocabulary_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.exportVocabulary(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.EXPORT_DECISION_RECORD)
    void exportDecisionRecord_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("decision-record-export");
        String result = l3.exportDecisionRecord(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_BPMN_PROCESS)
    void importBpmnProcess_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("bpmn-process");
        String result = l3.importBpmnProcess(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_CADS_SCHEMA)
    void importCadsSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("cads-schema");
        String result = l3.importCadsSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_CONFIGURATION)
    void importConfiguration_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("config-schema");
        String result = l3.importConfiguration(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_CONSTRAINT_SET)
    void importConstraintSet_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("odcs-schema");
        String result = l3.importConstraintSet(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_DMN_DECISION)
    void importDmnDecision_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("dmn-decision");
        String result = l3.importDmnDecision(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_DOMAIN_ORG)
    void importDomainOrg_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("domain-org");
        String result = l3.importDomainOrg(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_KNOWLEDGE_BASE)
    void importKnowledgeBase_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("knowledge-base");
        String result = l3.importKnowledgeBase(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_ODCS_SCHEMA)
    void importOdcsSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("odcs-schema");
        String result = l3.importOdcsSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_ODPS_SCHEMA)
    void importOdpsSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("odps-schema");
        String result = l3.importOdpsSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_OPENAPI_SCHEMA)
    void importOpenapiSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("openapi-schema");
        String result = l3.importOpenapiSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_SKETCH)
    void importSketch_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("sketch");
        String result = l3.importSketch(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_TEMPLATE)
    void importTemplate_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("odcs-schema");
        String result = l3.importTemplate(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_VOCABULARY)
    void importVocabulary_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("odcs-schema");
        String result = l3.importVocabulary(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.IMPORT_DECISION_RECORD)
    void importDecisionRecord_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("decision-record");
        String result = l3.importDecisionRecord(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.INFER_CONSTRAINTS)
    void inferConstraints_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.inferConstraints(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.INFER_DECISION_RULES)
    void inferDecisionRules_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.inferDecisionRules(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.INFER_DOMAIN_ORG)
    void inferDomainOrg_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.inferDomainOrg(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.INFER_KNOWLEDGE_GAPS)
    void inferKnowledgeGaps_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.inferKnowledgeGaps(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.INFER_SCHEMA_RECOMMENDATIONS)
    void inferSchemaRecommendations_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.inferSchemaRecommendations(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.INFER_VOCABULARY)
    void inferVocabulary_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.inferVocabulary(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.MAP_BPMN_TO_SCHEMA)
    void mapBpmnToSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("bpmn-process");
        String result = l3.mapBpmnToSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.MAP_DOMAIN_TO_SCHEMA)
    void mapDomainToSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("domain-org");
        String result = l3.mapDomainToSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.MAP_SCHEMAS)
    void mapSchemas_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.mapSchemas(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.MAP_VOCABULARIES)
    void mapVocabularies_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("workspace-simple");
        String result = l3.mapVocabularies(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.VALIDATE_BPMN_PROCESS)
    void validateBpmnProcess_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("bpmn-process");
        String result = l3.validateBpmnProcess(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.VALIDATE_CADS_SCHEMA)
    void validateCadsSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("cads-schema");
        String result = l3.validateCadsSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.VALIDATE_CONFIGURATION)
    void validateConfiguration_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("config-schema");
        String result = l3.validateConfiguration(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.VALIDATE_CONSTRAINT_SET)
    void validateConstraintSet_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("odcs-schema");
        String result = l3.validateConstraintSet(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.VALIDATE_DMN_DECISION)
    void validateDmnDecision_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("dmn-decision");
        String result = l3.validateDmnDecision(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.VALIDATE_DOMAIN_ORG)
    void validateDomainOrg_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("domain-org");
        String result = l3.validateDomainOrg(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.VALIDATE_KNOWLEDGE_BASE)
    void validateKnowledgeBase_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("knowledge-base");
        String result = l3.validateKnowledgeBase(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.VALIDATE_ODCS_SCHEMA)
    void validateOdcsSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("odcs-schema");
        String result = l3.validateOdcsSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.VALIDATE_ODPS_SCHEMA)
    void validateOdpsSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("odps-schema");
        String result = l3.validateOdpsSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.VALIDATE_OPENAPI_SCHEMA)
    void validateOpenapiSchema_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("openapi-schema");
        String result = l3.validateOpenapiSchema(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.VALIDATE_SKETCH)
    void validateSketch_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("sketch");
        String result = l3.validateSketch(fixture);
        assertPlausible(result);
    }

    @Test
    @DataModellingCapabilityTest(DataModellingCapability.VALIDATE_DECISION_RECORD)
    void validateDecisionRecord_roundTripsJson_whenLibraryLoaded() throws IOException {
        assumeTrue(l3.isAvailable(),
            "libdatamodelling.so absent — integration test skipped");
        String fixture = loadFixture("decision-record");
        String result = l3.validateDecisionRecord(fixture);
        assertPlausible(result);
    }

    @Test
    void registryValidates_allCapabilitiesCovered() {
        var registry = new DataModellingCapabilityRegistry(
            List.of(DataModellingL2.class),
            List.of(DataModellingL3.class),
            List.of(DataModellingIntegrationTest.class));
        registry.validate();
    }
}
