/*
 * Copyright (c) 2004-2026 The YAWL Foundation. All rights reserved.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.dspy.fluent;

import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;

/**
 * Main entry point for the DSPy fluent API - mirrors Python {@code import dspy}.
 *
 * <p>This class provides a fluent, type-safe Java API that mirrors the Python DSPy
 * library (dspy==3.1.3). It follows the JOR4J (Java > OTP > Rust/Python > OTP > Java)
 * pattern for fault-tolerant polyglot integration.
 *
 * <h2>Python → Java Mapping:</h2>
 * <table border="1">
 *   <tr><th>Python</th><th>Java</th></tr>
 *   <tr><td>{@code dspy.LM(model, api_key)}</td><td>{@code Dspy.lm().model(model).apiKey(key)}</td></tr>
 *   <tr><td>{@code dspy.configure(lm=lm)}</td><td>{@code Dspy.configure(lm -> lm...)}</td></tr>
 *   <tr><td>{@code class Sig(dspy.Signature)}</td><td>{@code Dspy.signature("input -> output")}</td></tr>
 *   <tr><td>{@code dspy.Predict(signature)}</td><td>{@code Dspy.predict(signature)}</td></tr>
 *   <tr><td>{@code dspy.ChainOfThought(sig)}</td><td>{@code Dspy.chainOfThought(signature)}</td></tr>
 *   <tr><td>{@code dspy.Example(input=..., output=...)}</td><td>{@code Dspy.example().input(k,v).output(k,v)}</td></tr>
 *   <tr><td>{@code BootstrapFewShot().compile()}</td><td>{@code Dspy.bootstrap().compile(program)}</td></tr>
 *   <tr><td>{@code program(**inputs)}</td><td>{@code program.predict("key", value)}</td></tr>
 * </table>
 *
 * <h2>Quick Start:</h2>
 * <pre>{@code
 * // Configure the language model
 * Dspy.configure(lm -> lm
 *     .model("groq/gpt-oss-20b")
 *     .apiKey(System.getenv("GROQ_API_KEY"))
 *     .temperature(0.0));
 *
 * // Define a signature
 * DspySignature sig = Dspy.signature("question -> answer");
 *
 * // Create a predictor
 * DspyModule predictor = Dspy.predict(sig);
 *
 * // Run prediction
 * DspyResult result = predictor.predict("question", "What is YAWL?");
 * String answer = result.getString("answer");
 * }</pre>
 *
 * <h2>With Chain of Thought:</h2>
 * <pre>{@code
 * DspyModule cot = Dspy.chainOfThought(sig);
 * DspyResult result = cot.predict("question", "Explain quantum computing");
 * String reasoning = result.getString("reasoning");  // Auto-generated by CoT
 * String answer = result.getString("answer");
 * }</pre>
 *
 * <h2>With Few-Shot Examples:</h2>
 * <pre>{@code
 * DspyExample ex1 = Dspy.example()
 *     .input("question", "What is 2+2?")
 *     .output("answer", "4");
 *
 * DspyExample ex2 = Dspy.example()
 *     .input("question", "What is 3+3?")
 *     .output("answer", "6");
 *
 * DspyModule predictor = Dspy.predict(sig)
 *     .withExamples(List.of(ex1, ex2));
 * }</pre>
 *
 * <h2>Architecture (JOR4J Pattern):</h2>
 * <pre>
 * ┌─────────────────────────────────────────────────────────────────┐
 * │  JAVA 25                                    Layer 3: Domain API  │
 * │  (Virtual Threads, Panama FFM, Records)       Dspy (this)       │
 * └─────────────────────────┬───────────────────────────────────────┘
 *                           │ libei (Erlang Interface)
 *                           ▼
 * ┌─────────────────────────────────────────────────────────────────┐
 * │  Erlang/OTP 28                              Layer 2: Distribution │
 * │  (Process isolation, supervision trees)    dspy_bridge           │
 * └─────────────────────────┬───────────────────────────────────────┘
 *                           │ NIF / PyO3
 *                           ▼
 * ┌─────────────────────────────────────────────────────────────────┐
 * │  Python 3.12                                Layer 1: Native      │
 * │  (dspy==3.1.3, pydantic)                    dspy programs       │
 * └─────────────────────────────────────────────────────────────────┘
 * </pre>
 *
 * @author YAWL Foundation
 * @version 6.0.0
 * @see <a href="https://dspy.ai/">DSPy Documentation</a>
 */
public final class Dspy {

    private static final Logger log = LoggerFactory.getLogger(Dspy.class);

    private static volatile DspyLM configuredLM;
    private static volatile boolean configured = false;

    // Private constructor - static factory methods only
    private Dspy() {}

    // ═══════════════════════════════════════════════════════════════════════════
    // CONFIGURATION (mirrors dspy.configure)
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Configure DSPy with a language model.
     *
     * <p>Python: {@code dspy.configure(lm=dspy.LM(model="groq/gpt-oss-20b"))}
     *
     * <pre>{@code
     * Dspy.configure(lm -> lm
     *     .model("groq/gpt-oss-20b")
     *     .apiKey(System.getenv("GROQ_API_KEY"))
     *     .temperature(0.0));
     * }</pre>
     *
     * @param lmConfigurator Consumer that configures the LM builder
     */
    public static synchronized void configure(Consumer<DspyLM.Builder> lmConfigurator) {
        Objects.requireNonNull(lmConfigurator, "lmConfigurator is required");

        DspyLM.Builder builder = DspyLM.builder();
        lmConfigurator.accept(builder);
        configuredLM = builder.build();
        configured = true;

        log.info("DSPy configured with model: {}", configuredLM.model());
    }

    /**
     * Configure DSPy with a pre-built language model.
     *
     * <p>Python: {@code dspy.configure(lm=lm)}
     */
    public static synchronized void configure(DspyLM lm) {
        Objects.requireNonNull(lm, "lm is required");
        configuredLM = lm;
        configured = true;

        log.info("DSPy configured with model: {}", lm.model());
    }

    /**
     * Configure with default Groq settings (GPT-OSS-20B, recommended).
     *
     * <p>Requires {@code GROQ_API_KEY} environment variable.
     */
    public static void configureGroq() {
        configure(DspyLM.groq());
    }

    /**
     * Configure with Groq Llama 3.3 70B.
     *
     * <p>Requires {@code GROQ_API_KEY} environment variable.
     */
    public static void configureGroqLlama() {
        configure(DspyLM.groqLlama());
    }

    /**
     * Configure with default OpenAI settings (GPT-4).
     *
     * <p>Requires {@code OPENAI_API_KEY} environment variable.
     */
    public static void configureOpenAI() {
        configure(DspyLM.openai());
    }

    /**
     * Configure with default Anthropic settings (Claude 3 Opus).
     *
     * <p>Requires {@code ANTHROPIC_API_KEY} environment variable.
     */
    public static void configureAnthropic() {
        configure(DspyLM.anthropic());
    }

    /**
     * Check if DSPy has been configured.
     */
    public static boolean isConfigured() {
        return configured;
    }

    /**
     * Get the configured language model.
     */
    public static @Nullable DspyLM getConfiguredLM() {
        return configuredLM;
    }

    /**
     * Reset configuration (for testing).
     */
    public static synchronized void reset() {
        configuredLM = null;
        configured = false;
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // SIGNATURES (mirrors dspy.Signature)
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Create a signature from a string shorthand.
     *
     * <p>Python: {@code dspy.Signature("question -> answer")}
     * <p>Python: {@code dspy.Signature("context, question -> answer, confidence")}
     *
     * @param shorthand Input/output specification (e.g., "question -> answer")
     * @return the signature
     */
    public static DspySignature signature(String shorthand) {
        return DspySignature.of(shorthand);
    }

    /**
     * Create a signature builder for more control.
     *
     * <p>Python (class-based):
     * <pre>{@code
     * class MySig(dspy.Signature):
     *     """Description of what this does."""
     *     question: str = dspy.InputField(desc="The question")
     *     answer: str = dspy.OutputField(desc="The answer")
     * }</pre>
     *
     * <p>Java:
     * <pre>{@code
     * DspySignature sig = Dspy.signatureBuilder()
     *     .description("Description of what this does")
     *     .input("question", "The question")
     *     .output("answer", "The answer")
     *     .build();
     * }</pre>
     */
    public static DspySignature.Builder signatureBuilder() {
        return DspySignature.builder();
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // MODULES (mirrors dspy.Predict, dspy.ChainOfThought, etc.)
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Create a basic predictor module.
     *
     * <p>Python: {@code predictor = dspy.Predict(signature)}
     *
     * @param signature The signature defining input/output contract
     * @return A predictor module
     */
    public static DspyModule predict(DspySignature signature) {
        return DspyModule.builder()
            .type(DspyModule.Type.PREDICT)
            .signature(signature)
            .build();
    }

    /**
     * Create a predictor from a signature shorthand.
     *
     * <p>Python: {@code predictor = dspy.Predict("question -> answer")}
     */
    public static DspyModule predict(String signatureShorthand) {
        return predict(signature(signatureShorthand));
    }

    /**
     * Create a chain-of-thought reasoning module.
     *
     * <p>Python: {@code cot = dspy.ChainOfThought(signature)}
     *
     * <p>Chain-of-thought adds an intermediate "reasoning" field that
     * helps the LLM think through the problem before producing the answer.
     *
     * @param signature The signature defining input/output contract
     * @return A chain-of-thought module
     */
    public static DspyModule chainOfThought(DspySignature signature) {
        return DspyModule.builder()
            .type(DspyModule.Type.CHAIN_OF_THOUGHT)
            .signature(signature)
            .build();
    }

    /**
     * Create a chain-of-thought module from a signature shorthand.
     *
     * <p>Python: {@code cot = dspy.ChainOfThought("question -> answer")}
     */
    public static DspyModule chainOfThought(String signatureShorthand) {
        return chainOfThought(signature(signatureShorthand));
    }

    /**
     * Create a ReAct agent module.
     *
     * <p>Python: {@code react = dspy.ReAct(signature, tools=[])}
     *
     * @param signature The signature defining input/output contract
     * @return A ReAct module (tools configured separately)
     */
    public static DspyModule react(DspySignature signature) {
        return DspyModule.builder()
            .type(DspyModule.Type.REACT)
            .signature(signature)
            .build();
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // EXAMPLES (mirrors dspy.Example)
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Create an example builder for few-shot learning.
     *
     * <p>Python: {@code example = dspy.Example(question="...", answer="...")}
     *
     * <pre>{@code
     * DspyExample example = Dspy.example()
     *     .input("question", "What is YAWL?")
     *     .output("answer", "YAWL is a workflow language");
     * }</pre>
     */
    public static DspyExample.Builder example() {
        return DspyExample.builder();
    }

    /**
     * Create an example from input/output maps.
     *
     * <p>Python: {@code dspy.Example(**inputs, **outputs)}
     */
    public static DspyExample example(Map<String, Object> inputs, Map<String, Object> outputs) {
        return DspyExample.of(inputs, outputs);
    }

    /**
     * Create a simple example with single input/output.
     */
    public static DspyExample example(String inputKey, Object inputValue,
                                       String outputKey, Object outputValue) {
        return DspyExample.of(inputKey, inputValue, outputKey, outputValue);
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // LANGUAGE MODEL BUILDER
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Create a language model builder.
     *
     * <p>Python: {@code lm = dspy.LM(model="groq/gpt-oss-20b")}
     *
     * <pre>{@code
     * DspyLM lm = Dspy.lm()
     *     .model("groq/gpt-oss-20b")
     *     .apiKey(System.getenv("GROQ_API_KEY"))
     *     .temperature(0.0)
     *     .build();
     * }</pre>
     */
    public static DspyLM.Builder lm() {
        return DspyLM.builder();
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // TELEPROMPTERS (mirrors dspy.teleprompt)
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Create a BootstrapFewShot optimizer.
     *
     * <p>Python:
     * <pre>{@code
     * from dspy.teleprompt import BootstrapFewShot
     * optimizer = BootstrapFewShot(metric=my_metric, max_bootstrapped_demos=5)
     * compiled = optimizer.compile(program, trainset=trainset)
     * }</pre>
     *
     * <p>Java:
     * <pre>{@code
     * Dspy.Bootstrap optimizer = Dspy.bootstrap()
     *     .maxExamples(5)
     *     .minScore(0.8);
     * DspyModule compiled = optimizer.compile(program, trainset);
     * }</pre>
     */
    public static Bootstrap bootstrap() {
        return new Bootstrap();
    }

    /**
     * BootstrapFewShot optimizer wrapper.
     */
    public static final class Bootstrap {
        private int maxExamples = 5;
        private double minScore = 0.8;
        private int maxRounds = 1;

        private Bootstrap() {}

        /**
         * Set maximum number of few-shot examples to include.
         *
         * <p>Python: {@code max_bootstrapped_demos=5}
         */
        public Bootstrap maxExamples(int maxExamples) {
            this.maxExamples = maxExamples;
            return this;
        }

        /**
         * Set minimum score threshold for including an example.
         */
        public Bootstrap minScore(double minScore) {
            this.minScore = minScore;
            return this;
        }

        /**
         * Set maximum bootstrap rounds.
         */
        public Bootstrap maxRounds(int maxRounds) {
            this.maxRounds = maxRounds;
            return this;
        }

        /**
         * Compile the program with few-shot examples from training data.
         *
         * <p>Python: {@code compiled = optimizer.compile(program, trainset=trainset)}
         *
         * @param program The program to optimize
         * @param trainset Training examples
         * @return Optimized program with few-shot examples
         */
        public DspyModule compile(DspyModule program, List<DspyExample> trainset) {
            Objects.requireNonNull(program, "program is required");
            Objects.requireNonNull(trainset, "trainset is required");

            if (trainset.isEmpty()) {
                log.warn("Empty trainset provided to BootstrapFewShot; returning original program");
                return program;
            }

            // Convert to internal types
            org.yawlfoundation.yawl.dspy.signature.Signature internalSig =
                program.signature().toSignature();

            List<org.yawlfoundation.yawl.dspy.signature.Example> internalExamples =
                trainset.stream()
                    .map(DspyExample::toExample)
                    .toList();

            // Create internal predictor
            org.yawlfoundation.yawl.dspy.module.Predict<?> predictor =
                new org.yawlfoundation.yawl.dspy.module.Predict<>(internalSig, null);

            // Create BootstrapFewShot optimizer
            org.yawlfoundation.yawl.dspy.teleprompter.BootstrapFewShot<
                org.yawlfoundation.yawl.dspy.module.Predict<?>> optimizer =
                org.yawlfoundation.yawl.dspy.teleprompter.BootstrapFewShot.<
                    org.yawlfoundation.yawl.dspy.module.Predict<?>>builder()
                    .maxExamples(maxExamples)
                    .minScore(minScore)
                    .maxRounds(maxRounds)
                    .build();

            // Compile
            org.yawlfoundation.yawl.dspy.module.Predict<?> compiled =
                optimizer.compile(predictor, internalExamples);

            // Convert back to fluent module
            List<DspyExample> bootstrappedExamples = compiled.examples().stream()
                .map(ex -> DspyExample.of(ex.inputs(), ex.outputs()))
                .toList();

            return program.withExamples(bootstrappedExamples);
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // YAWL-SPECIFIC PROGRAMS (Pre-built for common use cases)
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Pre-built POWL generator - converts natural language to POWL workflows.
     *
     * <p>Signature: {@code workflow_description -> powl_json}
     *
     * @return A POWL generator module
     */
    public static DspyModule powlGenerator() {
        DspySignature sig = signatureBuilder()
            .description("Generate POWL workflow from natural language")
            .input("workflow_description", "Natural language description of workflow")
            .output("powl_json", "Generated POWL model as JSON")
            .build();

        return predict(sig);
    }

    /**
     * Pre-built resource router - allocates tasks to agents.
     *
     * <p>Signature: {@code task_context, available_agents -> recommended_agent, confidence}
     *
     * @return A resource router module
     */
    public static DspyModule resourceRouter() {
        DspySignature sig = signatureBuilder()
            .description("Route task to best available agent")
            .input("task_context", "Task description and requirements")
            .input("available_agents", "List of available agents with capabilities")
            .output("recommended_agent", "ID of recommended agent")
            .output("confidence", "Confidence score 0-1")
            .build();

        return predict(sig);
    }

    /**
     * Pre-built anomaly forensics - explains anomalies in process execution.
     *
     * <p>Signature: {@code anomaly_data -> root_cause, remediation_steps}
     *
     * @return An anomaly forensics module
     */
    public static DspyModule anomalyForensics() {
        DspySignature sig = signatureBuilder()
            .description("Analyze process anomalies and suggest remediation")
            .input("anomaly_data", "Anomaly details and context")
            .output("root_cause", "Identified root cause")
            .output("remediation_steps", "Suggested remediation steps")
            .build();

        return chainOfThought(sig);
    }

    /**
     * Pre-built runtime adapter - suggests workflow optimizations.
     *
     * <p>Signature: {@code process_metrics -> optimization_recommendations}
     *
     * @return A runtime adapter module
     */
    public static DspyModule runtimeAdapter() {
        DspySignature sig = signatureBuilder()
            .description("Suggest runtime optimizations based on metrics")
            .input("process_metrics", "Current process performance metrics")
            .output("optimization_recommendations", "List of optimization suggestions")
            .build();

        return predict(sig);
    }

    /**
     * Pre-built worklet selector - chooses appropriate worklets.
     *
     * <p>Signature: {@code work_item_context -> recommended_worklet}
     *
     * @return A worklet selector module
     */
    public static DspyModule workletSelector() {
        DspySignature sig = signatureBuilder()
            .description("Select best worklet for work item context")
            .input("work_item_context", "Work item details and context")
            .output("recommended_worklet", "ID of recommended worklet")
            .build();

        return predict(sig);
    }
}
