PREFIX yawls: <http://www.yawlfoundation.org/yawlschema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?taskId ?taskName ?splitType ?joinType ?documentation ?decomposesTo
WHERE {
  ?task a yawls:Task ;
        yawls:id ?taskId ;
        yawls:name ?taskName .

  ?task yawls:hasSplit ?splitElm .
  ?splitElm yawls:code ?splitType .

  ?task yawls:hasJoin ?joinElm .
  ?joinElm yawls:code ?joinType .

  OPTIONAL {
    ?task rdfs:comment ?documentation
  }

  OPTIONAL {
    ?task yawls:decomposesTo ?decomp .
    ?decomp yawls:id ?decomposesTo
  }
}
ORDER BY ?taskId
