---
# Approval Agent Profile
# Auto-approves expenses under delegation limit
# Escalates large expenses for manual review

apiVersion: agents.marketplace/v1
kind: AgentProfile

metadata:
  id: approval-agent
  name: Approval Agent
  version: 1.0.0
  author: acme-team
  created: 2026-02-21T00:00:00Z
  updated: 2026-02-21T00:00:00Z

spec:
  description: |
    Autonomous agent that approves expense requests under delegation limit.
    Uses rule-based decision engine (no ML) for deterministic approval.

    Features:
    - Auto-approve if amount < delegation limit ($10,000)
    - Auto-escalate if amount >= limit
    - Log all decisions for audit trail
    - Support multiple approval tiers

  # Capabilities this agent can invoke
  capabilities:
    - id: approve-expense
      skillId: yawl.skills.approval.approve
      description: "Approves an expense request"
      params:
        amount:
          type: number
          description: Expense amount in USD
          required: true
          constraints:
            minimum: 0
            maximum: 999999
        requestor:
          type: string
          description: Employee ID requesting approval
          required: true
        category:
          type: string
          description: Expense category (travel, meals, supplies, etc)
          required: true
          constraints:
            enum:
              - travel
              - meals
              - supplies
              - training
              - equipment
              - other
        manager_approval:
          type: boolean
          description: Has direct manager already approved?
          required: false
          defaultValue: false
      returns:
        approved:
          type: boolean
          description: Whether expense was approved
        confidence:
          type: number
          description: Confidence score (0.0-1.0)
          constraints:
            minimum: 0.0
            maximum: 1.0
        reason:
          type: string
          description: Reason for approval/rejection
        approval_tier:
          type: integer
          description: Approval tier (1=manager, 2=department, 3=executive)
      timeout: 10s
      maxRetries: 2

    - id: escalate-approval
      skillId: yawl.skills.approval.escalate
      description: "Escalates approval to higher authority"
      params:
        case_id:
          type: string
          description: Workflow case ID
          required: true
        amount:
          type: number
          description: Expense amount
          required: true
        reason:
          type: string
          description: Reason for escalation
          required: true
      returns:
        escalated_to:
          type: string
          description: Role/person escalated to
        escalation_id:
          type: string
          description: Tracking ID for escalation
      timeout: 5s
      maxRetries: 1

  # Deployment configuration
  deployment:
    type: docker
    image: registry.acme.com/agents/approval-agent:1.0.0
    port: 9001
    environment:
      - name: DELEGATION_LIMIT
        value: "10000"
      - name: LOG_LEVEL
        value: INFO
      - name: MAX_CONCURRENT_REQUESTS
        value: "100"
      - name: CIRCUIT_BREAKER_THRESHOLD
        value: "0.5"  # Open circuit if >50% failures
    resources:
      memory: 512Mi
      cpu: 250m
      disk: 1Gi
    replicas: 2  # Run 2 instances for HA

  # Health check configuration
  healthCheck:
    type: http
    path: /health
    interval: 30s
    timeout: 5s
    successThreshold: 1
    failureThreshold: 3
    initialDelaySeconds: 10

  # Security
  security:
    authentication:
      type: jwt
      issuer: https://auth.acme.com
      audience: yawl-agents
    authorization:
      type: role-based
      requiredRoles:
        - approval-approver
    transport:
      type: https
      tlsVersion: "1.3"
      certificatePin: true

  # Performance & SLA
  metrics:
    successRate: 0.985           # 98.5% of requests succeed
    avgLatency: 250              # Average response time in ms
    p50Latency: 180
    p99Latency: 450
    uptime: 0.9998               # 99.98% uptime (last 30 days)
    costPerInvocation: 0.01      # $0.01 USD
    invocationsThisMonth: 12450

  # Reputation
  reputation:
    score: 4.8                   # Out of 5.0
    reviews: 120
    trustLevel: high
    certifications:
      - accuracy: 98.5%
        period: "2026-01-01T00:00:00Z to 2026-02-21T00:00:00Z"

  # Dependencies
  dependencies:
    - skillsMarketplace: yawl.skills.approval
    - dataStore: approvals-db
    - externalServices:
        - https://approval-rules-engine.acme.com

  # Configuration schema
  configuration:
    delegationLimits:
      description: "Per-role approval limits"
      type: object
      properties:
        employee:
          type: number
          default: 5000
        manager:
          type: number
          default: 25000
        director:
          type: number
          default: 100000
        executive:
          type: number
          default: 1000000

    approvalRules:
      description: "Rules for automatic approval"
      type: array
      items:
        type: object
        properties:
          condition:
            type: string
            description: "JSONPath expression (e.g., $.amount < 5000)"
          action:
            type: string
            enum:
              - approve
              - reject
              - escalate
          reason:
            type: string

  # Logging & debugging
  logging:
    level: INFO
    format: json
    fields:
      - timestamp
      - request_id
      - agent_id
      - decision
      - amount
      - requestor
    enableAuditTrail: true

  # Training data (informational)
  training:
    datasetSize: 50000            # Number of approval decisions used
    modelFamily: "rule-based"     # No ML, deterministic rules
    lastUpdated: 2026-02-01T00:00:00Z
    accuracy: 0.985               # Decision accuracy on validation set

  # Release notes
  releaseNotes:
    version: 1.0.0
    released: 2026-02-21T00:00:00Z
    changes:
      - Initial release
      - Support for 5 expense categories
      - 3-tier approval hierarchy
      - Circuit breaker resilience
    knownLimitations:
      - Does not support custom approval workflows (Phase 2)
      - No support for currency conversion (Phase 2)
