name: Weekly Dependency Security Scan

# This workflow runs comprehensive dependency scanning for YAWL
# - Checks for outdated dependencies
# - Scans for known CVEs using OWASP Dependency-Check
# - Generates detailed security reports
# - Fails build on critical vulnerabilities

on:
  # Run every Monday at 2 AM UTC
  schedule:
    - cron: '0 2 * * 1'

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      module:
        description: 'Specific module to check (leave empty for all)'
        required: false
        type: string
      format:
        description: 'Report format (markdown, html, json, all)'
        required: false
        type: choice
        options:
          - markdown
          - html
          - json
          - all
        default: 'all'

  # Also run on pull requests that modify pom.xml
  pull_request:
    paths:
      - '**/pom.xml'
      - '.github/workflows/dependency-check.yml'

jobs:
  dependency-scan:
    name: Scan Dependencies for Security Issues
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq pandoc

      - name: Run Dependency Health Check
        id: scan
        continue-on-error: true
        run: |
          MODULE_ARG=""
          if [ -n "${{ inputs.module }}" ]; then
            MODULE_ARG="--module=${{ inputs.module }}"
          fi

          FORMAT_ARG="--format=${{ inputs.format || 'all' }}"

          ./.claude/check-dependencies.sh $MODULE_ARG $FORMAT_ARG
          echo "scan_exit_code=$?" >> $GITHUB_OUTPUT

      - name: Upload Dependency Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-reports-${{ github.run_number }}
          path: dependency-reports/
          retention-days: 90

      - name: Parse Report Summary
        id: summary
        if: always()
        run: |
          REPORT_FILE=$(ls dependency-reports/dependency-health-*.md | head -1)
          if [ -f "$REPORT_FILE" ]; then
            CRITICAL=$(grep "Critical Vulnerabilities" "$REPORT_FILE" | grep -oP '\*\*\K\d+' || echo "0")
            HIGH=$(grep "High Severity Issues" "$REPORT_FILE" | grep -oP '\*\*\K\d+' || echo "0")
            MEDIUM=$(grep "Medium Severity Issues" "$REPORT_FILE" | grep -oP '\*\*\K\d+' || echo "0")
            LOW=$(grep "Low Severity Issues" "$REPORT_FILE" | grep -oP '\*\*\K\d+' || echo "0")

            echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
            echo "high=$HIGH" >> $GITHUB_OUTPUT
            echo "medium=$MEDIUM" >> $GITHUB_OUTPUT
            echo "low=$LOW" >> $GITHUB_OUTPUT
            echo "report_file=$REPORT_FILE" >> $GITHUB_OUTPUT
          fi

      - name: Create Job Summary
        if: always()
        run: |
          REPORT_FILE="${{ steps.summary.outputs.report_file }}"

          echo "## ðŸ”’ YAWL Dependency Security Scan" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Scan Date:** $(date '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### Executive Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Severity | Count |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| ðŸš¨ Critical | **${{ steps.summary.outputs.critical }}** |" >> $GITHUB_STEP_SUMMARY
          echo "| âš ï¸  High | **${{ steps.summary.outputs.high }}** |" >> $GITHUB_STEP_SUMMARY
          echo "| ðŸ“‹ Medium | ${{ steps.summary.outputs.medium }} |" >> $GITHUB_STEP_SUMMARY
          echo "| â„¹ï¸  Low | ${{ steps.summary.outputs.low }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -f "$REPORT_FILE" ]; then
            echo "### Critical Vulnerabilities" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            if grep -q "CRITICAL VULNERABILITIES" "$REPORT_FILE"; then
              sed -n '/## ðŸš¨ CRITICAL VULNERABILITIES/,/##/p' "$REPORT_FILE" | head -20 >> $GITHUB_STEP_SUMMARY
            else
              echo "âœ… No critical vulnerabilities detected" >> $GITHUB_STEP_SUMMARY
            fi
            echo "" >> $GITHUB_STEP_SUMMARY
          fi

          echo "### ðŸ“Š Reports Generated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Markdown Report" >> $GITHUB_STEP_SUMMARY
          echo "- OWASP HTML Report" >> $GITHUB_STEP_SUMMARY
          echo "- JSON Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Download artifacts to view detailed reports." >> $GITHUB_STEP_SUMMARY

      - name: Comment on PR (if applicable)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const critical = '${{ steps.summary.outputs.critical }}';
            const high = '${{ steps.summary.outputs.high }}';
            const medium = '${{ steps.summary.outputs.medium }}';
            const low = '${{ steps.summary.outputs.low }}';

            let message = '## ðŸ”’ Dependency Security Scan Results\n\n';
            message += '| Severity | Count |\n';
            message += '|----------|-------|\n';
            message += `| ðŸš¨ Critical | **${critical}** |\n`;
            message += `| âš ï¸  High | **${high}** |\n`;
            message += `| ðŸ“‹ Medium | ${medium} |\n`;
            message += `| â„¹ï¸  Low | ${low} |\n\n`;

            if (critical > 0) {
              message += '### â›” Action Required\n\n';
              message += 'Critical vulnerabilities detected! Please review and update affected dependencies before merging.\n\n';
            } else if (high > 0) {
              message += '### âš ï¸  Warning\n\n';
              message += 'High severity issues detected. Consider updating dependencies.\n\n';
            } else {
              message += '### âœ… All Clear\n\n';
              message += 'No critical or high severity vulnerabilities detected.\n\n';
            }

            message += 'Download the workflow artifacts for detailed reports.';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });

      - name: Fail on Critical Vulnerabilities
        if: steps.summary.outputs.critical > 0
        run: |
          echo "::error::Critical vulnerabilities detected! Scan exit code: ${{ steps.scan.outputs.scan_exit_code }}"
          echo "Review the dependency reports and update affected packages immediately."
          exit 1

      - name: Warn on High Severity Issues
        if: steps.summary.outputs.high > 0 && steps.summary.outputs.critical == 0
        run: |
          echo "::warning::High severity issues detected. Consider updating dependencies in next sprint."

  # Optional: Create issue on critical vulnerabilities
  create-issue:
    name: Create Security Issue
    needs: dependency-scan
    runs-on: ubuntu-latest
    if: failure() && github.event_name == 'schedule'

    steps:
      - name: Create Issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'ðŸš¨ Critical Security Vulnerabilities Detected in Dependencies',
              body: `## Critical Dependency Vulnerabilities

              The weekly dependency scan has detected critical security vulnerabilities.

              **Scan Date:** ${new Date().toISOString()}
              **Workflow Run:** https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}

              ### Action Required

              1. Download the dependency reports from the workflow artifacts
              2. Review the OWASP Dependency-Check report
              3. Update affected dependencies following the recommendations
              4. Test the changes thoroughly
              5. Deploy the security patches

              ### Resources

              - [Dependency Check Script](.claude/check-dependencies.sh)
              - [Dependency Health Template](.claude/DEPENDENCY_HEALTH.md)
              - [Update Guide](.claude/README-DEPENDENCY-CHECK.md)

              ---

              **Priority:** High
              **Type:** Security
              **Auto-created by:** Dependency Security Scan Workflow`,
              labels: ['security', 'dependencies', 'critical']
            });

            console.log(`Created issue #${issue.data.number}`);

# Optional: Slack notification
#  notify-slack:
#    name: Notify Slack
#    needs: dependency-scan
#    runs-on: ubuntu-latest
#    if: always() && github.event_name == 'schedule'
#
#    steps:
#      - name: Send Slack Notification
#        uses: slackapi/slack-github-action@v1
#        with:
#          payload: |
#            {
#              "text": "YAWL Dependency Scan Complete",
#              "blocks": [
#                {
#                  "type": "section",
#                  "text": {
#                    "type": "mrkdwn",
#                    "text": "*YAWL Dependency Security Scan*\n\n*Critical:* ${{ needs.dependency-scan.outputs.critical }}\n*High:* ${{ needs.dependency-scan.outputs.high }}\n*Medium:* ${{ needs.dependency-scan.outputs.medium }}"
#                  }
#                }
#              ]
#            }
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
