# Composite Action - Docker Build and Push
# YAWL Workflow Engine CI/CD
#
# Usage:
#   - uses: ./.github/actions/docker-build-push
#     with:
#       image_name: yawl
#       tags: latest,5.2.0
#       registry: ghcr.io

name: 'Docker Build and Push'
description: 'Builds and pushes multi-arch Docker images'

inputs:
  context:
    description: 'Docker build context'
    required: false
    default: '.'
  dockerfile:
    description: 'Dockerfile path'
    required: false
    default: 'Dockerfile'
  image_name:
    description: 'Image name'
    required: true
  tags:
    description: 'Comma-separated image tags'
    required: true
  registry:
    description: 'Container registry'
    required: false
    default: 'ghcr.io'
  platforms:
    description: 'Build platforms'
    required: false
    default: 'linux/amd64,linux/arm64'
  build_args:
    description: 'Build arguments (multiline)'
    required: false
    default: ''
  push:
    description: 'Push image to registry'
    required: false
    default: 'true'
  cache_from:
    description: 'Cache from image'
    required: false
    default: ''

outputs:
  image_digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  image_tags:
    description: 'Image tags'
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      if: ${{ inputs.registry == 'ghcr.io' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Login to Docker Hub
      if: ${{ inputs.registry == 'docker.io' }}
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: |
          type=raw,value=${{ inputs.tags }}

    - name: Parse tags
      id: parse-tags
      shell: bash
      run: |
        # Convert comma-separated tags to Docker format
        TAGS="${{ inputs.tags }}"
        IFS=',' read -ra TAG_ARRAY <<< "$TAGS"

        DOCKER_TAGS=""
        for tag in "${TAG_ARRAY[@]}"; do
          tag=$(echo "$tag" | xargs)  # trim whitespace
          if [ -n "$DOCKER_TAGS" ]; then
            DOCKER_TAGS="${DOCKER_TAGS},"
          fi
          DOCKER_TAGS="${DOCKER_TAGS}${{ inputs.registry }}/${{ inputs.image_name }}:${tag}"
        done

        echo "tags=${DOCKER_TAGS}" >> $GITHUB_OUTPUT

    - name: Build and push
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push == 'true' }}
        tags: ${{ steps.parse-tags.outputs.tags }}
        build-args: |
          VERSION=${{ inputs.tags }}
          BUILD_DATE=${{ github.event.head_commit.timestamp }}
          VCS_REF=${{ github.sha }}
          ${{ inputs.build_args }}
        cache-from: |
          type=gha
          ${{ inputs.cache_from != '' && format('type=registry,ref={0}', inputs.cache_from) || '' }}
        cache-to: type=gha,mode=max
        provenance: true
        sbom: true

    - name: Output image info
      shell: bash
      run: |
        echo "## Docker Image Built" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Image | ${{ inputs.registry }}/${{ inputs.image_name }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Tags | ${{ inputs.tags }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Digest | ${{ steps.build.outputs.digest }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Platforms | ${{ inputs.platforms }} |" >> $GITHUB_STEP_SUMMARY
