#!/usr/bin/env bash
#
# ggen-generate-diataxis.sh - Generate diataxis documentation from package ontology
#
# This script generates documentation starter files from the YAWL package ontology
# using simple text templating (without requiring the full ggen Rust tool).
#
# Usage:
#   bash scripts/ggen-generate-diataxis.sh [--dry-run]
#
# Options:
#   --dry-run    Show what would be generated without creating files
#
# Output:
#   docs/packages/{package-path}/
#     ├── tutorials/01-getting-started.md
#     ├── how-to/index.md
#     ├── reference/api.md
#     └── explanation/architecture.md
#   docs/packages/INDEX.md
#

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ONTOLOGY_FILE="${REPO_ROOT}/.specify/yawl-packages.ttl"
DOCS_DIR="${REPO_ROOT}/docs/packages"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
    echo "DRY RUN MODE - No files will be created"
fi

# Check ontology exists
if [[ ! -f "$ONTOLOGY_FILE" ]]; then
    echo "ERROR: Ontology file not found: $ONTOLOGY_FILE"
    echo "Run: bash scripts/ggen-parse-packages.sh first"
    exit 1
fi

echo "Generating diataxis documentation from: $ONTOLOGY_FILE"
echo "Output directory: $DOCS_DIR"
echo ""

# Extract packages from ontology
extract_packages() {
    grep 'a javadoc:Package ;' "$ONTOLOGY_FILE" | \
    sed 's/javadoc:\([a-zA-Z0-9_]*\) a javadoc:Package.*/\1/'
}

# Extract field from ontology
extract_field() {
    local package_uri="$1"
    local field="$2"
    grep -A10 "javadoc:${package_uri} a javadoc:Package" "$ONTOLOGY_FILE" 2>/dev/null | \
    grep "javadoc:${field}" | \
    head -1 | \
    sed 's/.*"\(.*\)".*/\1/' || true
}

# Generate short name from package name
get_short_name() {
    local name="$1"
    echo "$name" | rev | cut -d. -f1-2 | rev
}

# Generate category from package name
get_category() {
    local name="$1"
    if [[ "$name" == *"engine.core"* ]]; then
        echo "core"
    elif [[ "$name" == *"engine"* ]]; then
        echo "engine"
    elif [[ "$name" == *"elements"* ]]; then
        echo "elements"
    elif [[ "$name" == *"integration"* ]]; then
        echo "integration"
    elif [[ "$name" == *"resilience"* ]]; then
        echo "resilience"
    elif [[ "$name" == *"security"* ]]; then
        echo "security"
    elif [[ "$name" == *"stateless"* ]]; then
        echo "stateless"
    else
        echo "other"
    fi
}

# Generate tutorial content
generate_tutorial() {
    local package_name="$1"
    local package_short="$2"
    local description="$3"
    local since="$4"

    cat << EOF
# ${package_short} Package Tutorial

**Audience**: Developers new to the ${package_short} package
**Time**: ~15 minutes
**Prerequisites**: Java 25+, Maven 3.9+

## What You'll Learn

By the end of this tutorial, you will:
- Understand the purpose of the ${package_short} package
- Know how to use key classes
- Be able to integrate with other YAWL components

## Overview

${description}

## Step 1: Setup

\`\`\`java
// Import the package classes
import ${package_name}.*;
\`\`\`

## Step 2: Basic Usage

\`\`\`java
// TODO: Add usage example
\`\`\`

## Step 3: Common Patterns

\`\`\`java
// TODO: Add common usage patterns
\`\`\`

## Next Steps

- Read the [How-To Guide](../how-to/)
- Check the [API Reference](../reference/api.md)
- Understand the [Architecture](../explanation/)

---
*Generated by ggen from package-info.java*
*Package: \`${package_name}\`*
*Since: ${since}*
EOF
}

# Generate how-to content
generate_howto() {
    local package_name="$1"
    local package_short="$2"
    local description="$3"

    cat << EOF
# How-To Guide - ${package_short}

${description}

## Getting Started

### Prerequisites

- Java 25 or later
- Maven 3.9+
- YAWL 6.0.0-GA

### Basic Setup

\`\`\`java
import ${package_name}.*;

// TODO: Add package-specific initialization
\`\`\`

## Common Tasks

| Task | Difficulty |
|------|------------|
| Getting Started | Beginner |

## Troubleshooting

| Problem | Solution |
|---------|----------|
| \`ClassNotFoundException\` | Ensure YAWL JAR is on classpath |

## Related Guides

- [Tutorial](../tutorials/01-getting-started.md)
- [API Reference](../reference/api.md)
- [Architecture](../explanation/architecture.md)

---
*Generated by ggen*
*Package: \`${package_name}\`*
EOF
}

# Generate reference content
generate_reference() {
    local package_name="$1"
    local package_short="$2"
    local description="$3"
    local since="$4"
    local author="$5"

    cat << EOF
# API Reference - ${package_short}

${description}

## Package Summary

| Property | Value |
|----------|-------|
| **Package** | \`${package_name}\` |
| **Since** | ${since} |
| **Author** | ${author} |
| **License** | LGPL 3.0 |

## Key Classes

| Class | Description |
|-------|-------------|
| TODO | Add key classes for this package |

## Interfaces

| Interface | Description |
|-----------|-------------|
| TODO | Add interfaces for this package |

## Exceptions

| Exception | When Thrown |
|-----------|-------------|
| TODO | Add exceptions for this package |

## Related Packages

- [YAWL Engine](../../engine/reference/api.md)
- [YAWL Elements](../../elements/reference/api.md)

---
*Generated by ggen from package-info.java*
*Package: \`${package_name}\`*
EOF
}

# Generate explanation content
generate_explanation() {
    local package_name="$1"
    local package_short="$2"
    local description="$3"

    cat << EOF
# ${package_short} - Architecture Explanation

${description}

## Design Philosophy

This package follows YAWL's core design principles:

1. **Separation of concerns**: Each package has a single responsibility
2. **Interface-driven design**: Depend on abstractions, not implementations
3. **Testability**: All components are designed for unit testing

## Key Concepts

### Core Concepts

1. **TODO**: Add concept 1
2. **TODO**: Add concept 2
3. **TODO**: Add concept 3

## Design Decisions

| Decision | Rationale | Alternatives Considered |
|----------|-----------|------------------------|
| TODO | Add design decision | Alternative |

## Performance Considerations

- **TODO**: Add performance considerations for this package

## Security Considerations

- **TODO**: Add security considerations for this package

## Related Explanations

- [YAWL Architecture Overview](../../../architecture/overview.md)
- [Petri Net Semantics](../../../architecture/petri-nets.md)

---
*Generated by ggen from package-info.java*
*Package: \`${package_name}\`*
EOF
}

# Main generation loop
pkg_count=0
skipped=0

while IFS= read -r package_uri; do
    # Convert URI back to package name (replace underscores with dots)
    package_name=$(echo "$package_uri" | tr '_' '.')
    package_short=$(get_short_name "$package_name")
    package_path=$(echo "$package_name" | tr '.' '/')
    category=$(get_category "$package_name")

    # Extract metadata
    description=$(extract_field "$package_uri" "description" | head -c 200)
    since=$(extract_field "$package_uri" "since")
    author=$(extract_field "$package_uri" "author")

    # Skip if no description
    if [[ -z "$description" ]]; then
        description="Part of the YAWL workflow engine."
    fi

    # Create directories
    tutorial_dir="${DOCS_DIR}/${package_path}/tutorials"
    howto_dir="${DOCS_DIR}/${package_path}/how-to"
    reference_dir="${DOCS_DIR}/${package_path}/reference"
    explanation_dir="${DOCS_DIR}/${package_path}/explanation"

    if $DRY_RUN; then
        echo "Would create: ${tutorial_dir}/01-getting-started.md"
        echo "Would create: ${howto_dir}/index.md"
        echo "Would create: ${reference_dir}/api.md"
        echo "Would create: ${explanation_dir}/architecture.md"
        echo ""
    else
        mkdir -p "$tutorial_dir" "$howto_dir" "$reference_dir" "$explanation_dir"

        generate_tutorial "$package_name" "$package_short" "$description" "$since" > \
            "${tutorial_dir}/01-getting-started.md"

        generate_howto "$package_name" "$package_short" "$description" > \
            "${howto_dir}/index.md"

        generate_reference "$package_name" "$package_short" "$description" "$since" "$author" > \
            "${reference_dir}/api.md"

        generate_explanation "$package_name" "$package_short" "$description" > \
            "${explanation_dir}/architecture.md"
    fi

    pkg_count=$((pkg_count + 1))

done < <(extract_packages)

# Generate index
if ! $DRY_RUN; then
    cat > "${DOCS_DIR}/INDEX.md" << 'EOF'
# YAWL Package Documentation Index

This index lists all YAWL packages with generated diataxis documentation.

## Documentation Types

| Type | Purpose | Audience |
|------|---------|----------|
| **Tutorial** | Learning-oriented | Beginners |
| **How-To** | Task-oriented | Practitioners |
| **Reference** | Information-oriented | All users |
| **Explanation** | Understanding-oriented | Architects |

## Statistics

EOF

    echo "- **Total packages**: ${pkg_count}" >> "${DOCS_DIR}/INDEX.md"
    echo "- **Documentation files**: $((pkg_count * 4)) (4 per package)" >> "${DOCS_DIR}/INDEX.md"
    echo "- **YAWL version**: 6.0.0-GA" >> "${DOCS_DIR}/INDEX.md"
    echo "" >> "${DOCS_DIR}/INDEX.md"
    echo "---" >> "${DOCS_DIR}/INDEX.md"
    echo "*Generated by ggen*" >> "${DOCS_DIR}/INDEX.md"
fi

echo "=========================================="
echo "Summary:"
echo "  Packages processed: ${pkg_count}"
echo "  Documentation files: $((pkg_count * 4))"
echo "  Output directory: ${DOCS_DIR}"
echo "=========================================="

exit 0
