#!/usr/bin/env bash
#
# ggen-parse-packages.sh - Parse package-info.java files into RDF ontology
#
# This script scans all package-info.java files in the YAWL source tree
# and generates an RDF/Turtle ontology that can be used by ggen for
# documentation generation.
#
# Usage:
#   bash scripts/ggen-parse-packages.sh
#
# Output:
#   .specify/yawl-packages.ttl - RDF ontology of package metadata
#
# Exit codes:
#   0 - Success
#   1 - Error (no packages found, IO error, etc.)
#

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/.specify/yawl-packages.ttl"

echo "Parsing YAWL package-info.java files..."

# Write header
cat > "$OUTPUT_FILE" << 'HEADER'
# =============================================================================
# YAWL Package Ontology
# Generated by ggen-parse-packages.sh
#
# This ontology contains metadata extracted from package-info.java files.
# It is used by ggen to generate diataxis documentation for each package.
#
# Prefixes:
#   javadoc - http://ggen.io/javadoc#
#   rdfs    - http://www.w3.org/2000/01/rdf-schema#
#   xsd     - http://www.w3.org/2001/XMLSchema#
#
# =============================================================================

@prefix javadoc: <http://ggen.io/javadoc#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix dct: <http://purl.org/dc/terms/> .

HEADER

# Use process substitution to avoid subshell issue with pkg_count
while IFS= read -r -d '' pkg_file; do
    # Extract package path
    dir_path=$(dirname "$pkg_file")
    rel_path="${dir_path#${REPO_ROOT}/src/}"
    package_name=$(echo "$rel_path" | tr '/' '.')
    package_uri=$(echo "$package_name" | tr '.' '_')

    # Extract description from Javadoc (first meaningful paragraph)
    description=$(awk '/\/\*\*/,/\*\//' "$pkg_file" 2>/dev/null | \
        sed '1d;$d' | \
        sed 's/^\s*\*\s*//' | \
        grep -v '^@' | \
        grep -v '^$' | \
        grep -v '^Copyright' | \
        grep -v '^This file is part' | \
        grep -v '^YAWL is' | \
        grep -v '^You should have' | \
        grep -v '^The YAWL Foundation' | \
        head -15 | \
        tr '\n' ' ' | \
        sed 's/<[^>]*>//g' | \
        sed 's/\s\s*/ /g' | \
        sed 's/^\s*//' | \
        sed 's/\s*$//' | \
        head -c 400)

    # Extract @since version
    since=$(grep -E '@since[[:space:]]+[0-9]' "$pkg_file" 2>/dev/null | \
        sed 's/.*@since[[:space:]]*//' | \
        head -1 || true)
    if [[ -z "${since:-}" ]]; then
        since="6.0.0-GA"
    fi

    # Extract @author
    author=$(grep -E '@author[[:space:]]' "$pkg_file" 2>/dev/null | \
        sed 's/.*@author[[:space:]]*//' | \
        sed 's/\s*$//' | \
        head -1 || true)
    if [[ -z "${author:-}" ]]; then
        author="YAWL Foundation"
    fi

    # Skip if no description found
    if [[ -z "${description:-}" ]]; then
        description="Part of the YAWL workflow engine."
    fi

    # Escape special characters for Turtle
    description=$(echo "$description" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')

    # Write RDF triple
    cat >> "$OUTPUT_FILE" << EOF
javadoc:${package_uri} a javadoc:Package ;
    javadoc:name "${package_name}" ;
    javadoc:description """${description}""" ;
    javadoc:since "${since}"^^xsd:string ;
    javadoc:author "${author}" .

EOF

done < <(find "${REPO_ROOT}/src" -name "package-info.java" -print0 | sort -z)

# Add ontology metadata
cat >> "$OUTPUT_FILE" << EOF

# =============================================================================
# Ontology Metadata
# =============================================================================

javadoc:PackageOntology a dct:Dataset ;
    dct:title "YAWL Package Metadata" ;
    dct:description "Package metadata extracted from package-info.java files" ;
    dct:created "$(date -u +%Y-%m-%dT%H:%M:%SZ)"^^xsd:dateTime .

EOF

# Count and report
total_count=$(grep -c 'a javadoc:Package' "$OUTPUT_FILE" 2>/dev/null || echo "0")

echo "Generated package ontology: $OUTPUT_FILE"
echo "Packages processed: $total_count"

if [[ "$total_count" -eq 0 ]]; then
    echo "ERROR: No packages found!" >&2
    exit 1
fi

echo ""
echo "Summary by category:"
echo "  - engine packages: $(grep -c 'yawl\.engine' "$OUTPUT_FILE" 2>/dev/null || echo 0)"
echo "  - elements packages: $(grep -c 'yawl\.elements' "$OUTPUT_FILE" 2>/dev/null || echo 0)"
echo "  - integration packages: $(grep -c 'yawl\.integration' "$OUTPUT_FILE" 2>/dev/null || echo 0)"
echo "  - resilience packages: $(grep -c 'yawl\.resilience' "$OUTPUT_FILE" 2>/dev/null || echo 0)"
echo "  - security packages: $(grep -c 'yawl\.security' "$OUTPUT_FILE" 2>/dev/null || echo 0)"
echo "  - stateless packages: $(grep -c 'yawl\.stateless' "$OUTPUT_FILE" 2>/dev/null || echo 0)"

exit 0
