# GitHub Actions - Publish Artifacts Pipeline
# YAWL Workflow Engine Release CI/CD
#
# Features:
# - Multi-registry container publishing (GHCR, Docker Hub, ECR, ACR, GCR)
# - OIDC authentication support
# - Helm chart publishing
# - SBOM generation
# - GitHub Release creation

name: Publish Artifacts

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 5.2.0)'
        required: true
      publish_to:
        description: 'Publish targets'
        required: true
        default: 'github,docker'
        type: string
      dry_run:
        description: 'Dry run (skip actual publishing)'
        required: false
        default: false
        type: boolean

env:
  JAVA_VERSION: '17'
  REGISTRY_GHCR: ghcr.io
  REGISTRY_DOCKERHUB: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # ============================================
  # Prepare Release
  # ============================================
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      is_prerelease: ${{ steps.version.outputs.is_prerelease }}
      publish_dockerhub: ${{ steps.targets.outputs.dockerhub }}
      publish_github: ${{ steps.targets.outputs.github }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

          if [[ "$VERSION" == *"-alpha"* ]] || [[ "$VERSION" == *"-beta"* ]] || [[ "$VERSION" == *"-rc"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Determine publish targets
        id: targets
        run: |
          PUBLISH_TO="${{ github.event.inputs.publish_to || 'github,docker' }}"

          if [[ "$PUBLISH_TO" == *"docker"* ]]; then
            echo "dockerhub=true" >> $GITHUB_OUTPUT
          else
            echo "dockerhub=false" >> $GITHUB_OUTPUT
          fi

          if [[ "$PUBLISH_TO" == *"github"* ]]; then
            echo "github=true" >> $GITHUB_OUTPUT
          else
            echo "github=false" >> $GITHUB_OUTPUT
          fi

      - name: Validate version format
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$ ]]; then
            echo "Invalid version format: $VERSION"
            exit 1
          fi
          echo "Version: $VERSION"

  # ============================================
  # Build Release Artifacts
  # ============================================
  build-release:
    name: Build Release Artifacts
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java and Ant
        uses: ./.github/actions/setup-java-ant
        with:
          java_version: ${{ env.JAVA_VERSION }}

      - name: Build all artifacts
        run: |
          ant -f build/build.xml buildAll
        env:
          ANT_OPTS: "-Xmx2048m"

      - name: Prepare release artifacts
        run: |
          mkdir -p release

          find build -name "*.war" -exec cp {} release/ \;
          find build -name "yawl*.jar" -exec cp {} release/ \;

          cd release
          tar -czvf yawl-${{ needs.prepare.outputs.version }}-dist.tar.gz *
          zip -r yawl-${{ needs.prepare.outputs.version }}-dist.zip *

          sha256sum * > checksums.sha256

          ls -la

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yawl-release-${{ needs.prepare.outputs.version }}
          path: release/
          retention-days: 90

  # ============================================
  # Build and Push Docker Images
  # ============================================
  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [prepare, build-release]
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: yawl-release-${{ needs.prepare.outputs.version }}
          path: release/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: ${{ needs.prepare.outputs.publish_dockerhub == 'true' && secrets.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_DOCKERHUB }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.prepare.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.prepare.outputs.version }}
            type=raw,value=latest,enable=${{ needs.prepare.outputs.is_prerelease == 'false' }}

      - name: Prepare Docker context
        run: |
          mkdir -p docker/context
          cp release/*.war docker/context/ || true
          if [ -f containerization/Dockerfile.engine ]; then
            cp containerization/Dockerfile.engine docker/context/Dockerfile
          fi

      - name: Build and push Docker image
        if: ${{ github.event.inputs.dry_run != 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./docker/context
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ needs.prepare.outputs.version }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
          provenance: true
          sbom: true

      - name: Generate Docker SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}:${{ needs.prepare.outputs.version }}
          output-file: reports/sbom-docker.spdx.json
          format: spdx-json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ needs.prepare.outputs.version }}
          path: reports/
          retention-days: 90

  # ============================================
  # Publish Helm Chart
  # ============================================
  helm-publish:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    needs: [prepare, build-release]
    if: ${{ github.event.inputs.dry_run != 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.14.0'

      - name: Package Helm chart
        run: |
          helm package helm/yawl \
            --version ${{ needs.prepare.outputs.version }} \
            --app-version ${{ needs.prepare.outputs.version }} \
            --destination ./charts/

      - name: Login to GitHub Container Registry for Helm
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Helm chart to GHCR
        run: |
          helm push ./charts/yawl-${{ needs.prepare.outputs.version }}.tgz \
            oci://${{ env.REGISTRY_GHCR }}/${{ github.repository_owner }}/charts

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart-${{ needs.prepare.outputs.version }}
          path: charts/
          retention-days: 90

  # ============================================
  # Create GitHub Release
  # ============================================
  github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [prepare, build-release, docker-build, helm-publish]
    if: github.event_name == 'push' || github.event.inputs.dry_run != 'true'
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: yawl-release-${{ needs.prepare.outputs.version }}
          path: release/

      - name: Download Helm chart
        uses: actions/download-artifact@v4
        with:
          name: helm-chart-${{ needs.prepare.outputs.version }}
          path: charts/

      - name: Generate Release Notes
        id: release-notes
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: false
          prerelease: ${{ needs.prepare.outputs.is_prerelease == 'true' }}
          tag_name: v${{ needs.prepare.outputs.version }}
          name: YAWL v${{ needs.prepare.outputs.version }}
          files: |
            release/*
            charts/*.tgz
          body: |
            ## YAWL Workflow Engine v${{ needs.prepare.outputs.version }}

            ### Changes
            See [CHANGELOG.md](CHANGELOG.md) for details.

            ### Downloads
            | File | Description |
            |------|-------------|
            | `yawl-${{ needs.prepare.outputs.version }}-dist.tar.gz` | Distribution archive (tar.gz) |
            | `yawl-${{ needs.prepare.outputs.version }}-dist.zip` | Distribution archive (zip) |
            | `*.war` | Individual WAR files |

            ### Docker Images
            ```bash
            docker pull ghcr.io/${{ github.repository }}:${{ needs.prepare.outputs.version }}
            ```

            ### Helm Chart
            ```bash
            helm pull oci://ghcr.io/${{ github.repository_owner }}/charts/yawl --version ${{ needs.prepare.outputs.version }}
            ```

            ### Verification
            Verify downloads using the provided checksums:
            ```bash
            sha256sum -c checksums.sha256
            ```

  # ============================================
  # Post-Release Notifications
  # ============================================
  notify:
    name: Post-Release Notifications
    runs-on: ubuntu-latest
    needs: [github-release]
    if: success()

    steps:
      - name: Send Slack notification
        if: ${{ vars.SLACK_WEBHOOK_URL != '' || secrets.SLACK_WEBHOOK_URL != '' }}
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "YAWL v${{ needs.prepare.outputs.version }} Released",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "YAWL Workflow Engine v${{ needs.prepare.outputs.version }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "A new version of YAWL has been released.\n\n<https://github.com/${{ github.repository }}/releases/tag/v${{ needs.prepare.outputs.version }}|View Release>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
