/**
 * QLever JExtract Bindings - Layer 1 Native Interface
 *
 * This package contains the native bindings generated by JExtract from the
 * QLever C header. These are low-level, direct mappings to the C API.
 *
 * <p>WARNING: This package contains low-level FFI bindings that should not be
 * used directly by application code. Use Layer 2 and 3 for higher-level APIs.
 *
 * @see org.yawlfoundation.yawl.bridge.qlever.native
 * @see org.yawlfoundation.yawl.bridge.qlever.engine
 */
@org.netbeans.api.annotations.common.NonNullAPI
package org.yawlfoundation.yawl.bridge.qlever.jextract;