/*
 * Automatically generated by JExtract from qlever_ffi.h
 * Manual edits will be overwritten!
 */

package org.yawlfoundation.yawl.bridge.qlever.jextract;

import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;
import jdk.incubator.foreign.GroupLayout;

/**
 * Memory layout for QLever status structure
 * Represents the result of QLever operations with error codes and messages
 */
public final class QleverStatus {

    // Memory layout definition matching C struct
    public static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.valueLayout(JAVA_INT, "code"),
        MemoryLayout.sequenceLayout(256, MemoryLayout.valueLayout(JAVA_BYTE, "message"))
    ).withName("QleverStatus");

    // Field offsets
    public static final long CODE_OFFSET = 0;
    public static final long MESSAGE_OFFSET = 4;
    public static final long MESSAGE_LENGTH = 256;

    // Create status from memory segment
    public static QleverStatus of(MemorySegment addr) {
        if (addr == null || addr.byteSize() != $LAYOUT.byteSize()) {
            throw new IllegalArgumentException("Invalid QleverStatus memory segment");
        }
        return new QleverStatus(addr);
    }

    // Create status with success code
    public static QleverStatus success() {
        MemorySegment segment = MemorySegment.allocateNative($LAYOUT, ResourceScope.globalScope());
        setCode(segment, 0);
        setMessage(segment, "");
        return new QleverStatus(segment);
    }

    // Create status with error code and message
    public static QleverStatus error(int code, String message) {
        MemorySegment segment = MemorySegment.allocateNative($LAYOUT, ResourceScope.globalScope());
        setCode(segment, code);
        setMessage(segment, message);
        return new QleverStatus(segment);
    }

    private final MemorySegment segment;

    private QleverStatus(MemorySegment segment) {
        this.segment = segment;
    }

    // Getters
    public int getCode() {
        return (int)segment.get(JAVA_INT, CODE_OFFSET);
    }

    public String getMessage() {
        return getMessage(segment);
    }

    // Setters
    public void setCode(int code) {
        setCode(segment, code);
    }

    public void setMessage(String message) {
        setMessage(segment, message);
    }

    // Utility methods
    public boolean isSuccess() {
        return getCode() == 0;
    }

    public boolean isFailure() {
        return getCode() != 0;
    }

    public static boolean isSuccess(QleverStatus status) {
        return status != null && status.isSuccess();
    }

    public static boolean isFailure(QleverStatus status) {
        return status == null || status.isFailure();
    }

    // Native access helpers
    private static int getCode(MemorySegment segment) {
        return (int)segment.get(JAVA_INT, CODE_OFFSET);
    }

    private static String getMessage(MemorySegment segment) {
        byte[] bytes = new byte[MESSAGE_LENGTH];
        MemorySegment.copy(segment, MESSAGE_OFFSET, bytes, 0, MESSAGE_LENGTH);
        String result = new String(bytes).trim();
        return result.isEmpty() ? "" : result;
    }

    private static void setCode(MemorySegment segment, int code) {
        segment.set(JAVA_INT, CODE_OFFSET, code);
    }

    private static void setMessage(MemorySegment segment, String message) {
        byte[] bytes = message.getBytes();
        int length = Math.min(bytes.length, MESSAGE_LENGTH - 1);
        MemorySegment.copy(MemorySegment.ofArray(bytes), 0L, segment, MESSAGE_OFFSET, length);
        // Null-terminate the string
        if (length < MESSAGE_LENGTH - 1) {
            segment.set(JAVA_BYTE, MESSAGE_OFFSET + length, (byte)0);
        }
    }

    @Override
    public String toString() {
        return "QleverStatus{" +
               "code=" + getCode() +
               ", message='" + getMessage() + '\'' +
               '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        QleverStatus that = (QleverStatus) o;
        return getCode() == that.getCode() &&
               getMessage().equals(that.getMessage());
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(getCode(), getMessage());
    }
}