/*
 * Automatically generated by JExtract from qlever_ffi.h
 * Manual edits will be overwritten!
 */

package org.yawlfoundation.yawl.bridge.qlever.jextract;

import jdk.incubator.foreign.MemoryAddress;
import jdk.incubator.foreign.ResourceScope;

/**
 * Opaque handle for QLever query results
 * Represents a pointer to the C++ QLeverResult object
 */
public final class QleverResultHandle {

    // Pointer value (64-bit on most platforms)
    private final long pointerValue;

    private QleverResultHandle(long pointerValue) {
        if (pointerValue == 0) {
            throw new IllegalArgumentException("Null pointer not allowed for QleverResultHandle");
        }
        this.pointerValue = pointerValue;
    }

    // Create from native address
    public static QleverResultHandle of(MemoryAddress address) {
        if (address == null) {
            throw new IllegalArgumentException("MemoryAddress cannot be null");
        }
        return new QleverResultHandle(address.toRawLongValue());
    }

    // Create from raw pointer value
    public static QleverResultHandle of(long pointerValue) {
        return new QleverResultHandle(pointerValue);
    }

    // Get the raw pointer value
    public long getPointerValue() {
        return pointerValue;
    }

    // Convert to MemoryAddress for FFI calls
    public MemoryAddress toAddress() {
        return MemoryAddress.ofLong(pointerValue);
    }

    // Check if this is a null handle
    public boolean isNull() {
        return pointerValue == 0;
    }

    @Override
    public String toString() {
        return "QleverResultHandle{0x" + Long.toHexString(pointerValue) + "}";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        QleverResultHandle that = (QleverResultHandle) o;
        return pointerValue == that.pointerValue;
    }

    @Override
    public int hashCode() {
        return Long.hashCode(pointerValue);
    }
}