# OCI DevOps Build Specification for YAWL
# Builds YAWL workflow engine with Ant and creates container images
# Version: 1.0.0

version: 0.1.0
component: build
language: java

# Build environment configuration
variables:
  # Build configuration
  ANT_VERSION: "1.10.14"
  JAVA_VERSION: "17"
  TOMCAT_VERSION: "9.0.85"

  # OCI-specific variables (set in OCI DevOps)
  # OCI_REGISTRY: <region>.ocir.io/<tenancy-namespace>
  # IMAGE_NAME: yawl-engine
  # IMAGE_TAG: ${OCI_BUILD_RUN_ID}

  # Database configuration for build
  DATABASE_TYPE: "postgres"
  DATABASE_PATH: "yawl"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "${DB_PASSWORD}"

  # Logging levels
  YAWL_LOGGING_LEVEL: "INFO"
  HIBERNATE_LOGGING_LEVEL: "ERROR"

# Build steps
steps:
  # Step 1: Setup build environment
  - step: SetupEnvironment
    type: Command
    name: "Setup Build Environment"
    command: |
      echo "Setting up build environment..."
      echo "Java version: ${JAVA_VERSION}"
      echo "Ant version: ${ANT_VERSION}"
      echo "Build run ID: ${OCI_BUILD_RUN_ID}"
      echo "Commit SHA: ${OCI_BUILD_COMMIT_SHA}"
    timeoutInSeconds: 60

  # Step 2: Install build dependencies
  - step: InstallDependencies
    type: Command
    name: "Install Build Dependencies"
    command: |
      # Install Ant if not present
      if ! command -v ant &> /dev/null; then
        echo "Installing Apache Ant ${ANT_VERSION}..."
        cd /tmp
        curl -fsSL https://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz | tar xz
        export PATH="/tmp/apache-ant-${ANT_VERSION}/bin:$PATH"
        ant -version
      fi

      # Verify Java version
      java -version
    timeoutInSeconds: 300

  # Step 3: Configure build properties
  - step: ConfigureBuild
    type: Command
    name: "Configure Build Properties"
    command: |
      cd ${OCI_PRIMARY_SOURCE_DIR}

      # Create build configuration from template
      cat > build/build.properties.local << EOF
      # OCI DevOps Build Configuration
      # Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

      catalina.home=/opt/tomcat
      tomcat.treatAsDedicated=true

      database.type=${DATABASE_TYPE}
      database.path=${DATABASE_PATH}
      database.user=${DATABASE_USER}
      database.password=${DATABASE_PASSWORD}

      yawl.logging.level=${YAWL_LOGGING_LEVEL}
      worklet.logging.level=INFO
      resource.logging.level=INFO
      scheduling.logging.level=INFO
      proclet.logging.level=INFO
      hibernate.logging.level=${HIBERNATE_LOGGING_LEVEL}
      root.logging.level=ERROR
      mail.logging.level=INFO

      proxy.host=
      proxy.port=

      # Build metadata
      yawl.build.number=${OCI_BUILD_RUN_ID}
      yawl.build.date=$(date +"%Y-%m-%d %H.%M.%S")
      EOF

      echo "Build properties configured successfully"
    timeoutInSeconds: 60

  # Step 4: Compile source code
  - step: Compile
    type: Command
    name: "Compile YAWL Source"
    command: |
      cd ${OCI_PRIMARY_SOURCE_DIR}

      echo "Compiling YAWL source code..."
      ant -f build/build.xml compile

      echo "Compilation completed successfully"
    timeoutInSeconds: 600

  # Step 5: Run unit tests
  - step: UnitTests
    type: Command
    name: "Run Unit Tests"
    command: |
      cd ${OCI_PRIMARY_SOURCE_DIR}

      echo "Running YAWL unit tests..."

      # Run JUnit tests
      java -cp classes:build/3rdParty/lib/* \
        org.junit.runner.JUnitCore \
        org.yawlfoundation.yawl.TestAllYAWLSuites

      echo "Unit tests completed"
    timeoutInSeconds: 900
    onFailure:
      - type: Command
        command: |
          echo "Unit tests failed. Check test output for details."
          exit 1

  # Step 6: Build WAR files
  - step: BuildWARs
    type: Command
    name: "Build Web Application Archives"
    command: |
      cd ${OCI_PRIMARY_SOURCE_DIR}

      echo "Building YAWL web application archives..."

      # Build all web applications
      ant -f build/build.xml buildWebApps

      # List generated WARs
      echo "Generated WAR files:"
      ls -la webapps/*.war

      # Verify WAR files
      for war in webapps/*.war; do
        if [ -f "$war" ]; then
          size=$(stat -f%z "$war" 2>/dev/null || stat -c%s "$war" 2>/dev/null)
          echo "  $(basename $war): $size bytes"
        fi
      done
    timeoutInSeconds: 900

  # Step 7: Security scanning with Trivy
  - step: SecurityScan
    type: Command
    name: "Security Vulnerability Scan"
    command: |
      cd ${OCI_PRIMARY_SOURCE_DIR}

      echo "Running security vulnerability scan..."

      # Install Trivy if not present
      if ! command -v trivy &> /dev/null; then
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.48.0
      fi

      # Scan dependencies for known vulnerabilities
      trivy fs --severity HIGH,CRITICAL --exit-code 1 build/3rdParty/lib/ || {
        echo "Warning: High/Critical vulnerabilities found in dependencies"
        # Don't fail the build, but report the issue
      }

      # Generate security report
      trivy fs --format json --output security-scan-report.json build/3rdParty/lib/ || true

      echo "Security scan completed"
    timeoutInSeconds: 600

  # Step 8: Build container images
  - step: BuildImages
    type: Command
    name: "Build Container Images"
    command: |
      cd ${OCI_PRIMARY_SOURCE_DIR}

      echo "Building container images..."

      # Create Dockerfile directory
      mkdir -p docker/context

      # Copy WAR files to context
      cp webapps/*.war docker/context/

      # Build engine image
      docker build \
        -t ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-engine:${OCI_BUILD_RUN_ID} \
        -t ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-engine:latest \
        -f ci-cd/oracle-cloud/Dockerfile.engine \
        docker/context/

      # Build resource service image
      docker build \
        -t ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-resource-service:${OCI_BUILD_RUN_ID} \
        -t ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-resource-service:latest \
        -f ci-cd/oracle-cloud/Dockerfile.resource \
        docker/context/

      # Build worklet service image
      docker build \
        -t ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-worklet-service:${OCI_BUILD_RUN_ID} \
        -t ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-worklet-service:latest \
        -f ci-cd/oracle-cloud/Dockerfile.worklet \
        docker/context/

      echo "Container images built successfully"
      docker images | grep yawl
    timeoutInSeconds: 1200

  # Step 9: Push images to OCI Container Registry
  - step: PushImages
    type: Command
    name: "Push Images to OCI Registry"
    command: |
      echo "Pushing images to OCI Container Registry..."

      # Push engine image
      docker push ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-engine:${OCI_BUILD_RUN_ID}
      docker push ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-engine:latest

      # Push resource service image
      docker push ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-resource-service:${OCI_BUILD_RUN_ID}
      docker push ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-resource-service:latest

      # Push worklet service image
      docker push ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-worklet-service:${OCI_BUILD_RUN_ID}
      docker push ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-worklet-service:latest

      echo "Images pushed successfully"
    timeoutInSeconds: 900

# Output artifacts
outputArtifacts:
  - name: yawl-engine-image
    type: DOCKER_IMAGE
    location: ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-engine:${OCI_BUILD_RUN_ID}

  - name: yawl-resource-service-image
    type: DOCKER_IMAGE
    location: ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-resource-service:${OCI_BUILD_RUN_ID}

  - name: yawl-worklet-service-image
    type: DOCKER_IMAGE
    location: ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-worklet-service:${OCI_BUILD_RUN_ID}

  - name: security-scan-report
    type: BINARY
    location: ${OCI_PRIMARY_SOURCE_DIR}/security-scan-report.json

# Build triggers
triggers:
  - type: GitHub
    events:
      - push
      - pull_request
    branches:
      - main
      - develop
      - 'release/*'

# Encryption configuration
encryption:
  kmsKeyId: ${OCI_KMS_KEY_ID}
