# OCI DevOps Pipeline Definition for YAWL
# Complete CI/CD pipeline with build, test, and deployment stages
# Version: 1.0.0

apiVersion: 1.0.0
kind: Pipeline
metadata:
  name: yawl-cicd-pipeline
  description: "YAWL Workflow Engine CI/CD Pipeline for Oracle Cloud Infrastructure"
  displayName: "YAWL CI/CD Pipeline"
  projectId: ${OCI_PROJECT_ID}

# Pipeline configuration
config:
  # Build pipeline configuration
  buildPipelineId: ${OCI_BUILD_PIPELINE_ID}

  # Deploy pipeline configuration
  deployPipelineId: ${OCI_DEPLOY_PIPELINE_ID}

  # Notification configuration
  notifications:
    - type: EMAIL
      recipients:
        - ${NOTIFICATION_EMAIL}
      events:
        - BUILD_STARTED
        - BUILD_FAILED
        - BUILD_SUCCEEDED
        - DEPLOYMENT_STARTED
        - DEPLOYMENT_FAILED
        - DEPLOYMENT_SUCCEEDED

    - type: SLACK
      webhookUrl: ${SLACK_WEBHOOK_URL}
      events:
        - BUILD_FAILED
        - DEPLOYMENT_FAILED

# Pipeline stages
stages:
  # ========================================
  # BUILD STAGE
  # ========================================
  - stage: Build
    name: "Build Stage"
    description: "Build YAWL artifacts and container images"
    buildPipelineId: ${OCI_BUILD_PIPELINE_ID}

    buildPipeline:
      # Build Pipeline Steps
      steps:
        - step: Checkout
          type: Git
          name: "Checkout Source Code"
          repository: ${GIT_REPOSITORY_URL}
          branch: ${GIT_BRANCH:-main}
          timeoutInSeconds: 300

        - step: Setup
          type: Command
          name: "Setup Build Environment"
          command: |
            # Setup Java and Ant
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
            export ANT_HOME=/opt/ant
            export PATH=$JAVA_HOME/bin:$ANT_HOME/bin:$PATH

            java -version
            ant -version
          timeoutInSeconds: 120

        - step: Compile
          type: Command
          name: "Compile Source Code"
          command: |
            cd $OCI_PRIMARY_SOURCE_DIR
            ant -f build/build.xml compile
          timeoutInSeconds: 600

        - step: Test
          type: Command
          name: "Run Unit Tests"
          command: |
            cd $OCI_PRIMARY_SOURCE_DIR
            java -cp classes:build/3rdParty/lib/* \
              org.junit.runner.JUnitCore \
              org.yawlfoundation.yawl.TestAllYAWLSuites
          timeoutInSeconds: 900

        - step: Package
          type: Command
          name: "Build WAR Files"
          command: |
            cd $OCI_PRIMARY_SOURCE_DIR
            ant -f build/build.xml buildWebApps
            ls -la webapps/*.war
          timeoutInSeconds: 600

        - step: SecurityScan
          type: Command
          name: "Security Vulnerability Scan"
          command: |
            cd $OCI_PRIMARY_SOURCE_DIR
            # Scan with Trivy
            trivy fs --severity HIGH,CRITICAL build/3rdParty/lib/ || true
            trivy fs --format json --output security-report.json build/3rdParty/lib/ || true
          timeoutInSeconds: 600

        - step: BuildImages
          type: Command
          name: "Build Container Images"
          command: |
            cd $OCI_PRIMARY_SOURCE_DIR

            # Build all YAWL service images
            for service in engine resource-service worklet-service; do
              docker build \
                -t ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-${service}:${OCI_BUILD_RUN_ID} \
                -t ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-${service}:latest \
                -f ci-cd/oracle-cloud/Dockerfile.${service} \
                .
            done
          timeoutInSeconds: 1200

        - step: PushImages
          type: Command
          name: "Push to OCI Registry"
          command: |
            # Push all images to OCI Container Registry
            for service in engine resource-service worklet-service; do
              docker push ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-${service}:${OCI_BUILD_RUN_ID}
              docker push ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-${service}:latest
            done
          timeoutInSeconds: 900

      # Build artifacts
      artifacts:
        - name: yawl-engine-image
          type: DOCKER_IMAGE
          location: ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-engine:${OCI_BUILD_RUN_ID}

        - name: yawl-resource-service-image
          type: DOCKER_IMAGE
          location: ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-resource-service:${OCI_BUILD_RUN_ID}

        - name: yawl-worklet-service-image
          type: DOCKER_IMAGE
          location: ${OCI_REGISTRY}/${OCI_TENANCY_NAMESPACE}/yawl-worklet-service:${OCI_BUILD_RUN_ID}

        - name: security-report
          type: BINARY
          location: security-report.json

  # ========================================
  # DEPLOY TO DEVELOPMENT
  # ========================================
  - stage: DeployDev
    name: "Deploy to Development"
    description: "Deploy YAWL to development environment"
    dependsOn:
      - Build
    condition:
      type: SUCCESS

    deployPipeline:
      deployStageId: ${OCI_DEPLOY_STAGE_DEV_ID}
      deployEnvironmentId: ${OCI_DEPLOY_ENV_DEV_ID}

      parameters:
        environment: development
        namespace: yawl-dev
        replica_count: 1
        cpu_request: "250m"
        memory_request: "512Mi"
        cpu_limit: "1000m"
        memory_limit: "2Gi"

      steps:
        - step: PreDeploy
          type: Command
          name: "Pre-deployment Setup"
          command: |
            kubectl config use-context ${OKE_DEV_CONTEXT}
            kubectl get namespace yawl-dev || kubectl create namespace yawl-dev

        - step: Deploy
          type: OKE
          name: "Deploy to OKE"
          clusterId: ${OKE_DEV_CLUSTER_ID}
          namespace: yawl-dev
          manifestFile: ci-cd/oracle-cloud/k8s-manifests/deployment.yaml

        - step: Verify
          type: Command
          name: "Verify Deployment"
          command: |
            kubectl rollout status deployment/yawl-engine -n yawl-dev --timeout=300s
            kubectl rollout status deployment/yawl-resource-service -n yawl-dev --timeout=300s

  # ========================================
  # INTEGRATION TESTS
  # ========================================
  - stage: IntegrationTest
    name: "Integration Tests"
    description: "Run integration tests against development deployment"
    dependsOn:
      - DeployDev
    condition:
      type: SUCCESS

    steps:
      - step: RunTests
        type: Command
        name: "Run Integration Test Suite"
        command: |
          # Wait for services to be ready
          sleep 30

          # Get service endpoints
          ENGINE_URL="http://$(kubectl get service yawl-engine -n yawl-dev -o jsonpath='{.status.loadBalancer.ingress[0].ip}'):8080/yawl"

          # Run integration tests
          echo "Running integration tests against $ENGINE_URL"

          # Test 1: Health check
          curl -sf "${ENGINE_URL}/health" && echo "Health check: PASSED" || echo "Health check: FAILED"

          # Test 2: API connectivity
          curl -sf "${ENGINE_URL}/api/connection" && echo "API connectivity: PASSED" || echo "API connectivity: FAILED"

          # Test 3: Database connectivity (via engine health)
          curl -sf "${ENGINE_URL}/health/db" && echo "Database connectivity: PASSED" || echo "Database connectivity: FAILED"

          echo "Integration tests completed"
        timeoutInSeconds: 900

  # ========================================
  # DEPLOY TO STAGING
  # ========================================
  - stage: DeployStaging
    name: "Deploy to Staging"
    description: "Deploy YAWL to staging environment"
    dependsOn:
      - IntegrationTest
    condition:
      type: SUCCESS
    approval:
      type: MANUAL
      approvers:
        - ${APPROVER_GROUP_ID}

    deployPipeline:
      deployStageId: ${OCI_DEPLOY_STAGE_STAGING_ID}
      deployEnvironmentId: ${OCI_DEPLOY_ENV_STAGING_ID}

      parameters:
        environment: staging
        namespace: yawl-staging
        replica_count: 2
        cpu_request: "500m"
        memory_request: "1Gi"
        cpu_limit: "2000m"
        memory_limit: "4Gi"

      steps:
        - step: PreDeploy
          type: Command
          name: "Pre-deployment Setup"
          command: |
            kubectl config use-context ${OKE_STAGING_CONTEXT}
            kubectl get namespace yawl-staging || kubectl create namespace yawl-staging

        - step: Deploy
          type: OKE
          name: "Deploy to OKE"
          clusterId: ${OKE_STAGING_CLUSTER_ID}
          namespace: yawl-staging
          manifestFile: ci-cd/oracle-cloud/k8s-manifests/deployment.yaml

        - step: Verify
          type: Command
          name: "Verify Deployment"
          command: |
            kubectl rollout status deployment/yawl-engine -n yawl-staging --timeout=300s
            kubectl rollout status deployment/yawl-resource-service -n yawl-staging --timeout=300s
            kubectl rollout status deployment/yawl-worklet-service -n yawl-staging --timeout=300s

  # ========================================
  # PERFORMANCE TESTS
  # ========================================
  - stage: PerformanceTest
    name: "Performance Tests"
    description: "Run performance tests against staging deployment"
    dependsOn:
      - DeployStaging
    condition:
      type: SUCCESS

    steps:
      - step: RunPerfTests
        type: Command
        name: "Run Performance Test Suite"
        command: |
          # Get staging service endpoint
          STAGING_URL="http://$(kubectl get service yawl-engine -n yawl-staging -o jsonpath='{.status.loadBalancer.ingress[0].ip}'):8080/yawl"

          echo "Running performance tests against $STAGING_URL"

          # Install k6 for load testing
          curl -fsSL https://github.com/grafana/k6/releases/download/v0.47.0/k6-v0.47.0-linux-amd64.tar.gz | tar xz
          ./k6 run ci-cd/oracle-cloud/tests/load-test.js || true

          echo "Performance tests completed"
        timeoutInSeconds: 1800

  # ========================================
  # DEPLOY TO PRODUCTION
  # ========================================
  - stage: DeployProd
    name: "Deploy to Production"
    description: "Deploy YAWL to production environment"
    dependsOn:
      - PerformanceTest
    condition:
      type: SUCCESS
    approval:
      type: MANUAL
      approvers:
        - ${PROD_APPROVER_GROUP_ID}
      timeoutInMinutes: 1440  # 24 hours

    deployPipeline:
      deployStageId: ${OCI_DEPLOY_STAGE_PROD_ID}
      deployEnvironmentId: ${OCI_DEPLOY_ENV_PROD_ID}

      # Canary deployment for production
      strategy:
        type: CANARY
        canary:
          - percentage: 10
            duration: 600
            analysis:
              enabled: true
              criteria:
                - metric: error_rate
                  threshold: 1
                - metric: latency_p99
                  threshold: 2000
          - percentage: 50
            duration: 600
            analysis:
              enabled: true
          - percentage: 100
            duration: 0

      parameters:
        environment: production
        namespace: yawl-prod
        replica_count: 3
        cpu_request: "1000m"
        memory_request: "2Gi"
        cpu_limit: "4000m"
        memory_limit: "8Gi"

      steps:
        - step: PreDeploy
          type: Command
          name: "Pre-deployment Setup"
          command: |
            kubectl config use-context ${OKE_PROD_CONTEXT}
            kubectl get namespace yawl-prod || kubectl create namespace yawl-prod

        - step: Deploy
          type: OKE
          name: "Deploy to OKE"
          clusterId: ${OKE_PROD_CLUSTER_ID}
          namespace: yawl-prod
          manifestFile: ci-cd/oracle-cloud/k8s-manifests/deployment.yaml

        - step: Verify
          type: Command
          name: "Verify Production Deployment"
          command: |
            kubectl rollout status deployment/yawl-engine -n yawl-prod --timeout=600s
            kubectl rollout status deployment/yawl-resource-service -n yawl-prod --timeout=600s
            kubectl rollout status deployment/yawl-worklet-service -n yawl-prod --timeout=600s

        - step: PostDeploy
          type: Command
          name: "Post-deployment Validation"
          command: |
            # Production smoke tests
            PROD_URL="http://$(kubectl get service yawl-engine -n yawl-prod -o jsonpath='{.status.loadBalancer.ingress[0].ip}'):8080/yawl"

            # Critical endpoint checks
            curl -sf "${PROD_URL}/health" || exit 1
            curl -sf "${PROD_URL}/api/connection" || exit 1

            echo "Production deployment validated successfully"

  # ========================================
  # POST-DEPLOYMENT MONITORING
  # ========================================
  - stage: Monitoring
    name: "Post-deployment Monitoring"
    description: "Monitor deployment health"
    dependsOn:
      - DeployProd
    condition:
      type: SUCCESS

    steps:
      - step: SetupMonitoring
        type: Command
        name: "Setup Monitoring Alerts"
        command: |
          # Configure OCI Monitoring alarms
          oci monitoring alarm create \
            --display-name "yawl-high-error-rate" \
            --compartment-id ${OCI_COMPARTMENT_ID} \
            --metric-compartment-id ${OCI_COMPARTMENT_ID} \
            --namespace "yawl" \
            --query "error_rate[5m].percentile(0.99) > 5" \
            --severity "CRITICAL" \
            --pending-duration "5m" \
            --body "YAWL error rate exceeds 5%"

          echo "Monitoring configured"

      - step: VerifyMonitoring
        type: Command
        name: "Verify Monitoring Setup"
        command: |
          # Verify logs are being collected
          kubectl logs -l app=yawl -n yawl-prod --tail=10

          echo "Monitoring verification completed"

# Pipeline triggers
triggers:
  # Git trigger
  - name: GitPush
    type: GIT
    repository: ${GIT_REPOSITORY_URL}
    events:
      - PUSH
    branches:
      - main
      - release/*

  # Manual trigger
  - name: Manual
    type: MANUAL

  # Schedule trigger (nightly builds)
  - name: NightlyBuild
    type: SCHEDULE
    schedule: "0 2 * * *"  # 2 AM UTC daily
    branches:
      - main

# Variables
variables:
  # OCI Configuration
  OCI_COMPARTMENT_ID: ${OCI_COMPARTMENT_ID}
  OCI_TENANCY_NAMESPACE: ${OCI_TENANCY_NAMESPACE}
  OCI_REGISTRY: ${OCI_REGION}.ocir.io
  OCI_REGION: ${OCI_REGION}

  # OKE Cluster IDs
  OKE_DEV_CLUSTER_ID: ${OKE_DEV_CLUSTER_ID}
  OKE_STAGING_CLUSTER_ID: ${OKE_STAGING_CLUSTER_ID}
  OKE_PROD_CLUSTER_ID: ${OKE_PROD_CLUSTER_ID}

  # Vault configuration
  OCI_VAULT_NAME: ${OCI_VAULT_NAME}

  # Notification settings
  NOTIFICATION_EMAIL: ${NOTIFICATION_EMAIL}
  SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}

# Security configuration
security:
  # Use OCI Vault for secrets
  vault:
    name: ${OCI_VAULT_NAME}
    secrets:
      - name: db-credentials
        key: yawl-db-password
      - name: api-keys
        key: yawl-api-keys

  # KMS encryption
  kms:
    keyId: ${OCI_KMS_KEY_ID}

# Retention policy
retention:
  buildHistory: 30  # days
  artifactExpiry: 90  # days
  logRetention: 365  # days
