/*
 * Copyright (c) 2004-2026 The YAWL Foundation. All rights reserved.
 * The YAWL Foundation is a collaboration of individuals and
 * organisations who are committed to improving workflow technology.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.integration.gateway.aws;

import org.yawlfoundation.yawl.integration.gateway.GatewayRouteDefinition;

import java.util.List;
import java.util.Objects;

/**
 * Generates AWS API Gateway v2 (HTTP API) OpenAPI 3.0 definition with AWS extensions.
 *
 * <p>Produces an OpenAPI 3.0 YAML file with {@code x-amazon-apigateway-*} extensions
 * suitable for import into AWS API Gateway via the AWS Console, CLI, or CDK/Terraform.
 *
 * <p>Features configured:
 * <ul>
 *   <li>JWT authorizer via {@code x-amazon-apigateway-authorizer} pointing to
 *       the configured OIDC issuer URI and audience</li>
 *   <li>HTTP integration ({@code x-amazon-apigateway-integration}) with VPC link
 *       for private YAWL engine instances</li>
 *   <li>Route-level throttling via {@code x-amazon-apigateway-request-validators}</li>
 *   <li>CORS configuration for browser-based clients</li>
 *   <li>Usage plan (throttle/quota) per tier (CRITICAL/STANDARD/READ_ONLY)</li>
 * </ul>
 *
 * <h2>Deployment</h2>
 * <pre>
 * # Generate the OpenAPI definition
 * String openapi = AwsApiGatewayConfigGenerator.generate(
 *     "http://yawl-engine.internal:8080",
 *     "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XXXXX",
 *     "yawl-api",
 *     "vpclink-abc123"
 * );
 * Files.writeString(Path.of("yawl-api-gateway.yaml"), openapi);
 *
 * # Deploy via AWS CLI
 * aws apigatewayv2 import-api \
 *   --body file://yawl-api-gateway.yaml \
 *   --fail-on-warnings
 * </pre>
 *
 * @author YAWL Foundation
 * @version 6.0.0
 * @since 6.0.0
 */
public final class AwsApiGatewayConfigGenerator {

    private static final String API_GATEWAY_VERSION = "6.0.0";

    private AwsApiGatewayConfigGenerator() {
        throw new UnsupportedOperationException(
                "AwsApiGatewayConfigGenerator is a utility class and cannot be instantiated.");
    }

    /**
     * Generate an OpenAPI 3.0 YAML definition with AWS API Gateway extensions.
     *
     * @param upstreamBaseUrl YAWL engine internal base URL (behind VPC link)
     * @param oidcIssuerUri   OIDC provider issuer URI (Cognito user pool or other IdP)
     * @param audience        expected JWT audience claim value
     * @param vpcLinkId       AWS VPC link ID for private integration (null for public)
     * @return OpenAPI 3.0 YAML string with AWS extensions
     */
    public static String generate(String upstreamBaseUrl, String oidcIssuerUri,
                                  String audience, String vpcLinkId) {
        Objects.requireNonNull(upstreamBaseUrl, "upstreamBaseUrl must not be null");
        Objects.requireNonNull(oidcIssuerUri,   "oidcIssuerUri must not be null");
        Objects.requireNonNull(audience,         "audience must not be null");

        List<GatewayRouteDefinition> routes =
                GatewayRouteDefinition.yawlV1Routes(upstreamBaseUrl);

        StringBuilder yaml = new StringBuilder();
        appendOpenApiHeader(yaml, oidcIssuerUri, audience);
        appendPaths(yaml, routes, upstreamBaseUrl, vpcLinkId);
        appendComponents(yaml, oidcIssuerUri, audience);

        return yaml.toString();
    }

    private static void appendOpenApiHeader(StringBuilder yaml, String issuer, String audience) {
        yaml.append("# YAWL v6.0.0 AWS API Gateway HTTP API OpenAPI Definition\n");
        yaml.append("# Generated by AwsApiGatewayConfigGenerator\n");
        yaml.append("# Import: aws apigatewayv2 import-api --body file://yawl-api.yaml\n\n");
        yaml.append("openapi: \"3.0.1\"\n");
        yaml.append("info:\n");
        yaml.append("  title: YAWL Workflow API\n");
        yaml.append("  description: YAWL v6.0.0 enterprise workflow engine REST API\n");
        yaml.append("  version: \"").append(API_GATEWAY_VERSION).append("\"\n\n");

        // AWS API Gateway global JWT authorizer extension
        yaml.append("x-amazon-apigateway-auth:\n");
        yaml.append("  type: JWT\n\n");

        yaml.append("x-amazon-apigateway-cors:\n");
        yaml.append("  allowOrigins:\n");
        yaml.append("    - \"https://*.example.com\"  # Replace with your domain\n");
        yaml.append("  allowMethods:\n");
        yaml.append("    - GET\n    - POST\n    - PUT\n    - PATCH\n    - DELETE\n    - OPTIONS\n");
        yaml.append("  allowHeaders:\n");
        yaml.append("    - Authorization\n    - Content-Type\n    - X-Request-ID\n");
        yaml.append("  exposeHeaders:\n");
        yaml.append("    - X-Request-ID\n    - X-YAWL-Event-ID\n");
        yaml.append("  maxAge: 3600\n\n");
    }

    private static void appendPaths(StringBuilder yaml, List<GatewayRouteDefinition> routes,
                                    String upstreamBaseUrl, String vpcLinkId) {
        yaml.append("paths:\n");

        // Group routes by path pattern
        String currentPath = null;
        for (GatewayRouteDefinition route : routes) {
            String path = route.getPathPattern();
            // AWS path templates use {param} syntax - compatible with our definitions

            if (!path.equals(currentPath)) {
                yaml.append("  ").append(path).append(":\n");
                currentPath = path;
            }

            for (GatewayRouteDefinition.HttpMethod method : route.getMethods()) {
                appendOperation(yaml, route, method, upstreamBaseUrl, vpcLinkId);
            }
        }
    }

    private static void appendOperation(StringBuilder yaml, GatewayRouteDefinition route,
                                        GatewayRouteDefinition.HttpMethod method,
                                        String upstreamBaseUrl, String vpcLinkId) {
        yaml.append("    ").append(method.name().toLowerCase()).append(":\n");
        yaml.append("      summary: \"").append(route.getDescription()).append("\"\n");
        yaml.append("      operationId: ").append(route.getRouteId()).append("\n");

        if (route.isRequiresAuthentication()) {
            yaml.append("      security:\n");
            yaml.append("        - yawlJwtAuthorizer: []\n");
        }

        // Response definitions
        yaml.append("      responses:\n");
        yaml.append("        \"200\":\n");
        yaml.append("          description: Success\n");
        yaml.append("        \"400\":\n");
        yaml.append("          description: Bad Request\n");
        yaml.append("        \"401\":\n");
        yaml.append("          description: Unauthorized\n");
        yaml.append("        \"403\":\n");
        yaml.append("          description: Forbidden\n");
        yaml.append("        \"429\":\n");
        yaml.append("          description: Too Many Requests\n");
        yaml.append("        \"500\":\n");
        yaml.append("          description: Internal Server Error\n");

        // AWS integration extension
        yaml.append("      x-amazon-apigateway-integration:\n");
        yaml.append("        type: http_proxy\n");
        yaml.append("        httpMethod: ").append(method.name()).append("\n");
        yaml.append("        uri: \"").append(upstreamBaseUrl)
            .append(route.getUpstreamPath()).append("\"\n");
        yaml.append("        payloadFormatVersion: \"1.0\"\n");
        yaml.append("        timeoutInMillis: 29000\n");
        if (vpcLinkId != null && !vpcLinkId.isBlank()) {
            yaml.append("        connectionType: VPC_LINK\n");
            yaml.append("        connectionId: \"").append(vpcLinkId).append("\"\n");
        }

        // Route throttling
        yaml.append("      x-amazon-apigateway-request-validator: basic\n");
    }

    private static void appendComponents(StringBuilder yaml, String issuer, String audience) {
        yaml.append("\ncomponents:\n");
        yaml.append("  securitySchemes:\n");
        yaml.append("    yawlJwtAuthorizer:\n");
        yaml.append("      type: http\n");
        yaml.append("      scheme: bearer\n");
        yaml.append("      bearerFormat: JWT\n");
        yaml.append("      x-amazon-apigateway-authorizer:\n");
        yaml.append("        identitySource: \"$request.header.Authorization\"\n");
        yaml.append("        type: jwt\n");
        yaml.append("        jwtConfiguration:\n");
        yaml.append("          audience:\n");
        yaml.append("            - \"").append(audience).append("\"\n");
        yaml.append("          issuer: \"").append(issuer).append("\"\n\n");

        yaml.append("x-amazon-apigateway-request-validators:\n");
        yaml.append("  basic:\n");
        yaml.append("    validateRequestBody: true\n");
        yaml.append("    validateRequestParameters: true\n");
    }
}
