// Generated by gen-ttl. DO NOT EDIT.
package org.yawlfoundation.yawl.erlang.processmining;

import java.util.List;
import java.util.Map;

/**
* Static registry of all process_mining bridge capabilities.
*/
public final class CapabilityRegistry {

private CapabilityRegistry() {}

/** All capabilities keyed by Erlang function name. */
public static final Map<String, ProcessMiningCapability> BY_ERL_FUNCTION =
Map.copyOf(buildByErlFunction());

/** All capabilities grouped by group name. */
public static final Map<String, List<ProcessMiningCapability>> BY_GROUP =
Map.copyOf(buildByGroup());

private static java.util.HashMap<String, ProcessMiningCapability> buildByErlFunction() {
var m = new java.util.HashMap<String, ProcessMiningCapability>();
        m.put("get_dotted_chart", ProcessMiningCapability.GET_DOTTED_CHART);
        m.put("get_event_timestamps", ProcessMiningCapability.GET_EVENT_TIMESTAMPS);
        m.put("get_object_attribute_changes", ProcessMiningCapability.GET_OBJECT_ATTRIBUTE_CHANGES);
        m.put("oc_declare_conformance", ProcessMiningCapability.OC_DECLARE_CONFORMANCE);
        m.put("discover_alpha_ppp", ProcessMiningCapability.DISCOVER_ALPHA_PPP);
        m.put("discover_dfg", ProcessMiningCapability.DISCOVER_DFG);
        m.put("discover_dfg_from_ocel", ProcessMiningCapability.DISCOVER_DFG_FROM_OCEL);
        m.put("discover_oc_declare", ProcessMiningCapability.DISCOVER_OC_DECLARE);
        m.put("add_init_exit_events_to_ocel", ProcessMiningCapability.ADD_INIT_EXIT_EVENTS_TO_OCEL);
        m.put("export_dfg_image_png", ProcessMiningCapability.EXPORT_DFG_IMAGE_PNG);
        m.put("export_dfg_image_svg", ProcessMiningCapability.EXPORT_DFG_IMAGE_SVG);
        m.put("export_dfg_png", ProcessMiningCapability.EXPORT_DFG_PNG);
        m.put("export_petri_net_image_png", ProcessMiningCapability.EXPORT_PETRI_NET_IMAGE_PNG);
        m.put("export_petri_net_image_svg", ProcessMiningCapability.EXPORT_PETRI_NET_IMAGE_SVG);
        m.put("flatten_ocel_on", ProcessMiningCapability.FLATTEN_OCEL_ON);
        m.put("log_to_activity_projection", ProcessMiningCapability.LOG_TO_ACTIVITY_PROJECTION);
        m.put("locel_add_e2o", ProcessMiningCapability.LOCEL_ADD_E2O);
        m.put("locel_add_event", ProcessMiningCapability.LOCEL_ADD_EVENT);
        m.put("locel_add_event_type", ProcessMiningCapability.LOCEL_ADD_EVENT_TYPE);
        m.put("locel_add_o2o", ProcessMiningCapability.LOCEL_ADD_O2O);
        m.put("locel_add_object", ProcessMiningCapability.LOCEL_ADD_OBJECT);
        m.put("locel_add_object_type", ProcessMiningCapability.LOCEL_ADD_OBJECT_TYPE);
        m.put("locel_construct_ocel", ProcessMiningCapability.LOCEL_CONSTRUCT_OCEL);
        m.put("locel_delete_e2o", ProcessMiningCapability.LOCEL_DELETE_E2O);
        m.put("locel_delete_o2o", ProcessMiningCapability.LOCEL_DELETE_O2O);
        m.put("locel_get_e2o", ProcessMiningCapability.LOCEL_GET_E2O);
        m.put("locel_get_e2o_rev", ProcessMiningCapability.LOCEL_GET_E2O_REV);
        m.put("locel_get_ev_attr_val", ProcessMiningCapability.LOCEL_GET_EV_ATTR_VAL);
        m.put("locel_get_ev_by_id", ProcessMiningCapability.LOCEL_GET_EV_BY_ID);
        m.put("locel_get_ev_id", ProcessMiningCapability.LOCEL_GET_EV_ID);
        m.put("locel_get_ev_time", ProcessMiningCapability.LOCEL_GET_EV_TIME);
        m.put("locel_get_ev_type", ProcessMiningCapability.LOCEL_GET_EV_TYPE);
        m.put("locel_get_ev_type_of", ProcessMiningCapability.LOCEL_GET_EV_TYPE_OF);
        m.put("locel_get_ev_types", ProcessMiningCapability.LOCEL_GET_EV_TYPES);
        m.put("locel_get_evs_of_type", ProcessMiningCapability.LOCEL_GET_EVS_OF_TYPE);
        m.put("locel_get_full_ev", ProcessMiningCapability.LOCEL_GET_FULL_EV);
        m.put("locel_get_full_ob", ProcessMiningCapability.LOCEL_GET_FULL_OB);
        m.put("locel_get_o2o", ProcessMiningCapability.LOCEL_GET_O2O);
        m.put("locel_get_o2o_rev", ProcessMiningCapability.LOCEL_GET_O2O_REV);
        m.put("locel_get_ob_attr_vals", ProcessMiningCapability.LOCEL_GET_OB_ATTR_VALS);
        m.put("locel_get_ob_by_id", ProcessMiningCapability.LOCEL_GET_OB_BY_ID);
        m.put("locel_get_ob_id", ProcessMiningCapability.LOCEL_GET_OB_ID);
        m.put("locel_get_ob_type", ProcessMiningCapability.LOCEL_GET_OB_TYPE);
        m.put("locel_get_ob_type_of", ProcessMiningCapability.LOCEL_GET_OB_TYPE_OF);
        m.put("locel_get_ob_types", ProcessMiningCapability.LOCEL_GET_OB_TYPES);
        m.put("locel_get_obs_of_type", ProcessMiningCapability.LOCEL_GET_OBS_OF_TYPE);
        m.put("locel_new", ProcessMiningCapability.LOCEL_NEW);
        m.put("index_link_ocel", ProcessMiningCapability.INDEX_LINK_OCEL);
        m.put("num_events", ProcessMiningCapability.NUM_EVENTS);
        m.put("num_objects", ProcessMiningCapability.NUM_OBJECTS);
        m.put("ocel_type_stats", ProcessMiningCapability.OCEL_TYPE_STATS);
        m.put("slim_link_ocel", ProcessMiningCapability.SLIM_LINK_OCEL);
        m.put("test_some_inputs", ProcessMiningCapability.TEST_SOME_INPUTS);
        return m;
}

private static java.util.HashMap<String, List<ProcessMiningCapability>> buildByGroup() {
var m = new java.util.HashMap<String, List<ProcessMiningCapability>>();
        m.put("analysis", List.of(ProcessMiningCapability.GET_DOTTED_CHART, ProcessMiningCapability.GET_EVENT_TIMESTAMPS, ProcessMiningCapability.GET_OBJECT_ATTRIBUTE_CHANGES));
        m.put("conformance", List.of(ProcessMiningCapability.OC_DECLARE_CONFORMANCE));
        m.put("discovery", List.of(ProcessMiningCapability.DISCOVER_ALPHA_PPP, ProcessMiningCapability.DISCOVER_DFG, ProcessMiningCapability.DISCOVER_DFG_FROM_OCEL, ProcessMiningCapability.DISCOVER_OC_DECLARE));
        m.put("io", List.of(ProcessMiningCapability.ADD_INIT_EXIT_EVENTS_TO_OCEL, ProcessMiningCapability.EXPORT_DFG_IMAGE_PNG, ProcessMiningCapability.EXPORT_DFG_IMAGE_SVG, ProcessMiningCapability.EXPORT_DFG_PNG, ProcessMiningCapability.EXPORT_PETRI_NET_IMAGE_PNG, ProcessMiningCapability.EXPORT_PETRI_NET_IMAGE_SVG, ProcessMiningCapability.FLATTEN_OCEL_ON, ProcessMiningCapability.LOG_TO_ACTIVITY_PROJECTION));
        m.put("locel", List.of(ProcessMiningCapability.LOCEL_ADD_E2O, ProcessMiningCapability.LOCEL_ADD_EVENT, ProcessMiningCapability.LOCEL_ADD_EVENT_TYPE, ProcessMiningCapability.LOCEL_ADD_O2O, ProcessMiningCapability.LOCEL_ADD_OBJECT, ProcessMiningCapability.LOCEL_ADD_OBJECT_TYPE, ProcessMiningCapability.LOCEL_CONSTRUCT_OCEL, ProcessMiningCapability.LOCEL_DELETE_E2O, ProcessMiningCapability.LOCEL_DELETE_O2O, ProcessMiningCapability.LOCEL_GET_E2O, ProcessMiningCapability.LOCEL_GET_E2O_REV, ProcessMiningCapability.LOCEL_GET_EV_ATTR_VAL, ProcessMiningCapability.LOCEL_GET_EV_BY_ID, ProcessMiningCapability.LOCEL_GET_EV_ID, ProcessMiningCapability.LOCEL_GET_EV_TIME, ProcessMiningCapability.LOCEL_GET_EV_TYPE, ProcessMiningCapability.LOCEL_GET_EV_TYPE_OF, ProcessMiningCapability.LOCEL_GET_EV_TYPES, ProcessMiningCapability.LOCEL_GET_EVS_OF_TYPE, ProcessMiningCapability.LOCEL_GET_FULL_EV, ProcessMiningCapability.LOCEL_GET_FULL_OB, ProcessMiningCapability.LOCEL_GET_O2O, ProcessMiningCapability.LOCEL_GET_O2O_REV, ProcessMiningCapability.LOCEL_GET_OB_ATTR_VALS, ProcessMiningCapability.LOCEL_GET_OB_BY_ID, ProcessMiningCapability.LOCEL_GET_OB_ID, ProcessMiningCapability.LOCEL_GET_OB_TYPE, ProcessMiningCapability.LOCEL_GET_OB_TYPE_OF, ProcessMiningCapability.LOCEL_GET_OB_TYPES, ProcessMiningCapability.LOCEL_GET_OBS_OF_TYPE, ProcessMiningCapability.LOCEL_NEW));
        m.put("utility", List.of(ProcessMiningCapability.INDEX_LINK_OCEL, ProcessMiningCapability.NUM_EVENTS, ProcessMiningCapability.NUM_OBJECTS, ProcessMiningCapability.OCEL_TYPE_STATS, ProcessMiningCapability.SLIM_LINK_OCEL, ProcessMiningCapability.TEST_SOME_INPUTS));
        return m;
}
}
