/**
 * Comprehensive Java 25 Feature Test Suite.
 *
 * <h2>Overview</h2>
 * <p>This package contains real integration tests for Java 25 features
 * using Chicago TDD approach (real objects, no mocks, collaboration tests).
 *
 * <h2>Test Categories</h2>
 *
 * <h3>1. Records ({@link org.yawlfoundation.yawl.util.java25.records})</h3>
 * <ul>
 *   <li>{@link org.yawlfoundation.yawl.util.java25.records.RecordSerializationTest}
 *     - Serialization/deserialization with Java object streams</li>
 *   <li>{@link org.yawlfoundation.yawl.util.java25.records.RecordCompactConstructorTest}
 *     - Compact constructor validation logic</li>
 *   <li>{@link org.yawlfoundation.yawl.util.java25.records.RecordAutoGeneratedMethodsTest}
 *     - Auto-generated equals, hashCode, toString, accessors</li>
 * </ul>
 *
 * <h3>2. Sealed Classes ({@link org.yawlfoundation.yawl.util.java25.sealed})</h3>
 * <ul>
 *   <li>{@link org.yawlfoundation.yawl.util.java25.sealed.SealedClassPatternMatchingTest}
 *     - Exhaustive pattern matching and type safety</li>
 * </ul>
 *
 * <h3>3. Virtual Threads ({@link org.yawlfoundation.yawl.util.java25.virtual})</h3>
 * <ul>
 *   <li>{@link org.yawlfoundation.yawl.util.java25.virtual.VirtualThreadConcurrencyTest}
 *     - Creation, execution, cancellation (up to 10K threads)</li>
 *   <li>{@link org.yawlfoundation.yawl.util.java25.virtual.ScopedValuePropagationTest}
 *     - Context value propagation replacing ThreadLocal</li>
 * </ul>
 *
 * <h3>4. Structured Concurrency ({@link org.yawlfoundation.yawl.util.java25.structured})</h3>
 * <ul>
 *   <li>{@link org.yawlfoundation.yawl.util.java25.structured.StructuredConcurrencyTest}
 *     - Fan-out/fan-in, error handling, cancellation semantics</li>
 * </ul>
 *
 * <h3>5. Performance ({@link org.yawlfoundation.yawl.util.java25.performance})</h3>
 * <ul>
 *   <li>{@link org.yawlfoundation.yawl.util.java25.performance.PerformanceComparisonTest}
 *     - Records vs classes, virtual vs platform threads, ScopedValue vs ThreadLocal</li>
 * </ul>
 *
 * <h2>Key Design Principles</h2>
 *
 * <h3>Chicago TDD Approach</h3>
 * <ol>
 *   <li><strong>Real Objects</strong> - No mocks, stubs, or fake implementations</li>
 *   <li><strong>Integration Testing</strong> - Tests real Java 25 platform features</li>
 *   <li><strong>Collaboration Tests</strong> - Multiple threads/tasks interact</li>
 *   <li><strong>End-to-End Confidence</strong> - Complete workflow verification</li>
 * </ol>
 *
 * <h3>Standards Compliance (HYPER_STANDARDS)</h3>
 * <ul>
 *   <li>NO TODO/FIXME/XXX/HACK comments</li>
 *   <li>NO mock objects or stub implementations</li>
 *   <li>Real implementation OR UnsupportedOperationException</li>
 *   <li>NO silent fallbacks on errors</li>
 *   <li>Code behavior matches documentation exactly</li>
 * </ul>
 *
 * <h2>Test Statistics</h2>
 * <table border="1">
 *   <tr><th>Category</th><th>Test Class</th><th>Test Methods</th></tr>
 *   <tr><td>Records</td><td>3</td><td>36</td></tr>
 *   <tr><td>Sealed Classes</td><td>1</td><td>12</td></tr>
 *   <tr><td>Virtual Threads</td><td>2</td><td>24</td></tr>
 *   <tr><td>Structured Concurrency</td><td>1</td><td>14</td></tr>
 *   <tr><td>Performance</td><td>1</td><td>13</td></tr>
 *   <tr><td><strong>Total</strong></td><td><strong>8</strong></td><td><strong>99+</strong></td></tr>
 * </table>
 *
 * <h2>Running Tests</h2>
 *
 * <pre>
 * # All Java 25 tests
 * mvn test -Dtest=org.yawlfoundation.yawl.util.java25.**
 *
 * # Specific category
 * mvn test -Dtest=RecordSerializationTest
 * mvn test -Dtest=VirtualThreadConcurrencyTest
 * mvn test -Dtest=StructuredConcurrencyTest
 *
 * # With coverage
 * mvn clean test -P analysis
 * </pre>
 *
 * <h2>Java 25 Feature Overview</h2>
 *
 * <h3>Records (JEP 395)</h3>
 * <p>Immutable data carriers with auto-generated equals, hashCode, toString.</p>
 * <pre>
 * record WorkItem(String caseId, String taskId, String status) {
 *     // Compact constructor for validation
 *     public WorkItem {
 *         if (caseId == null) throw new IllegalArgumentException("caseId required");
 *     }
 * }
 * </pre>
 *
 * <h3>Sealed Classes (JEP 409, 420)</h3>
 * <p>Restrict which classes can extend or implement a sealed type.</p>
 * <pre>
 * sealed interface WorkflowElement permits Task, Gateway, Event { }
 * final class Task implements WorkflowElement { }
 * sealed class Gateway permits AndGateway, OrGateway { }
 * </pre>
 *
 * <h3>Virtual Threads (JEP 425, 428, 429, 444)</h3>
 * <p>Lightweight threads for high-throughput concurrent applications.</p>
 * <pre>
 * Thread.ofVirtual()
 *     .name("case-" + caseId)
 *     .start(() -> processCase(caseId));
 *
 * ExecutorService executor = Executors.newVirtualThreadPerTaskExecutor();
 * executor.submit(() -> realWork());
 * </pre>
 *
 * <h3>Structured Concurrency (JEP 428, 429, 437)</h3>
 * <p>Treat multiple concurrent tasks as a single unit with parent-child relationships.</p>
 * <pre>
 * try (var scope = new StructuredTaskScope.ShutdownOnFailure()) {
 *     scope.fork(() -> task1());
 *     scope.fork(() -> task2());
 *     scope.join();  // Waits for all, cancels on failure
 * }
 * </pre>
 *
 * <h3>ScopedValues (JEP 429, 446, 447)</h3>
 * <p>Immutable context values replacing ThreadLocal for virtual threads.</p>
 * <pre>
 * static final ScopedValue<WorkflowContext> CONTEXT = ScopedValue.newInstance();
 *
 * ScopedValue.callWhere(CONTEXT, myContext, () -> {
 *     WorkflowContext ctx = CONTEXT.get();  // Propagates to virtual threads
 *     // ...
 * });
 * </pre>
 *
 * <h2>Coverage Targets</h2>
 * <ul>
 *   <li>Line Coverage: 80%+</li>
 *   <li>Branch Coverage: 70%+</li>
 *   <li>Mutation Testing: Ready for pit-test</li>
 * </ul>
 *
 * <h2>Performance Benchmarks</h2>
 * <p>All performance tests use real measurements, not mocked results:</p>
 * <ul>
 *   <li>Record creation: 1M instances</li>
 *   <li>Virtual thread execution: 10K concurrent threads</li>
 *   <li>Structured scope operations: 1K subtasks</li>
 *   <li>ScopedValue propagation: Multi-layer testing</li>
 * </ul>
 *
 * <h2>Future Enhancements</h2>
 * <ul>
 *   <li>Pattern Matching for Switch (JEP 441) - guard patterns</li>
 *   <li>Record Patterns - destructuring in switch</li>
 *   <li>Implicit Classes - preview feature tests</li>
 *   <li>Module system integration with sealed classes</li>
 * </ul>
 *
 * @since Java 25
 * @version 6.0.0
 * @see <a href="https://openjdk.org/projects/amber/">Project Amber</a>
 * @see <a href="https://openjdk.org/jeps/395">JEP 395: Records</a>
 * @see <a href="https://openjdk.org/jeps/409">JEP 409: Sealed Classes</a>
 * @see <a href="https://openjdk.org/jeps/425">JEP 425: Virtual Threads</a>
 * @see <a href="https://openjdk.org/jeps/428">JEP 428: Structured Concurrency</a>
 */
package org.yawlfoundation.yawl.util.java25;
