/**
 * Thrown by {@link DataModellingCapabilityRegistry#validate()} when one or more capabilities
 * are missing L2, L3, or test coverage at startup.
 *
 * <p>Extends {@link RuntimeException} to abort startup fast without requiring callers
 * to declare checked exceptions. The detail message lists all missing coverages so
 * engineers can fix all violations in a single read.</p>
 *
 * <p>Example message:
 * <pre>
 *   DataModelling bridge validation failed — 3 missing coverages:
 *     L2 missing: SOME_CAPABILITY
 *     L3 missing: OTHER_CAPABILITY
 *     Test missing: THIRD_CAPABILITY
 * </pre>
 *
 * @generated by ggen from ontology
 * @pattern WCP-NB-07
 * @see DataModellingCapabilityRegistry
 */
package org.yawlfoundation.yawl.datamodelling.bridge;

import java.util.List;

public final class DataModellingCapabilityRegistryException extends RuntimeException {

    private final List<String> missingCoverages;

    /**
     * Creates the exception with the given list of missing coverage descriptions.
     *
     * @param missing non-null, non-empty list of missing coverage strings
     *                (e.g. {@code "L2 missing: SOME_CAPABILITY"})
     */
    public DataModellingCapabilityRegistryException(List<String> missing) {
        super(buildMessage(missing));
        this.missingCoverages = List.copyOf(missing);
    }

    /**
     * Returns an unmodifiable view of all missing coverage descriptions.
     *
     * <p>Each entry has the form {@code "L2 missing: CAPABILITY_NAME"},
     * {@code "L3 missing: CAPABILITY_NAME"}, or {@code "Test missing: CAPABILITY_NAME"}.</p>
     *
     * @return unmodifiable list of missing coverage descriptions
     */
    public List<String> getMissingCoverages() {
        return missingCoverages;
    }

    private static String buildMessage(List<String> missing) {
        StringBuilder sb = new StringBuilder();
        sb.append("DataModelling bridge validation failed — ")
          .append(missing.size())
          .append(" missing coverage")
          .append(missing.size() == 1 ? "" : "s")
          .append(":\n");
        for (String m : missing) {
            sb.append("  ").append(m).append('\n');
        }
        return sb.toString().stripTrailing();
    }
}
